// ==========================================================================
//  GENERATED FILE -- DO NOT EDIT.
//  Produced by build/build.py from components/Bottle_Control_Cage_v1.scad
//  Turtle Body version 1.6.0
//  Edit lib/ and src/ instead, then run: python3 build/build.py
// ==========================================================================
/*
 Hope Turtle — scalloped, reinforced PLA cage. Units: mm.
 Matched to the control cap: 100 mm cap disk, 102 mm cavity, 1 mm radial
 clearance. One continuous sinusoidal wall -> four rounded crests roof-down;
 each batten groove + its two M3 holes centred on a crest. No separate tabs.

 FABRICATION: this part is 3D-PRINTED ROOF-FACE-DOWN — the flat top surface
 goes on the printer bed (part="print" flips it). Any change to the roof top
 must stay self-supporting in that pose: bevels flare OUTWARD from the bed
 (<= 45 deg), no undercut, no downward-facing pocket/lip/overhang. Flag any
 change that would need support material instead of making it silently.
 The clip pocket + horizontal M3 bores already bridge in the slicer.
 Prototype: not load-tested. Test fit, torsion, bending, layer adhesion.

 SOURCE FILE — geometry lives in lib/control_cage.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [View] */
part = "print"; // [print,upright]
curve_segments = 120; // [48:12:240]
wave_segments  = 240;  // [120:24:480]

/* [Cage body] */
cage_wall   = 6.5;
cage_roof   = 6;
skirt_height = 44;      // roof underside -> ORIGINAL skirt rim
notch_width = 22.5;
notch_depth = 3.7;
m3_hole_diameter = 3.2;
roof_ring_height = 10;  // minimum skirt depth between mounts
mount_extension  = 20;  // crest past the original rim
lower_hole_from_tip = 10;
roof_bevel = 4;         // 45-deg outward chamfer on the roof-top edge (0 = sharp); prints face-down

/* [Bearings and button] */
bump_d = 9;
button_diameter = 18;
button_r = 24;
button_angle = 90; // [0:0.5:359.5]

/* [Shaft hub and clip pocket] */
cage_hex_af = 10.3;
cage_hub_d = 29;
clip_pocket_depth = 4;
pocket_d = 26;

// [bundle] begin use <../../lib/control_cage.scad>
// ==========================================================================
//  Turtle Body -- rotating control cage  (lib module)
// --------------------------------------------------------------------------
//  An inverted open-bottom cup. One continuous sinusoidal annular wall
//  forms four rounded crests; each batten groove and its two M3 holes are
//  centred on a crest. Eight solid hemispherical bearing bumps ride on the
//  cap's flat face. No bottom plate, no separate tabs. See CLAUDE.md s6.
//
//  Native "installed" reference: bearing tips touch cap Z = 0.
//    roof underside  Z = bump_d/2         (= 4.5 default)
//    roof top        Z = bump_d/2 + roof  (= 10.5)
//    longest tip     Z = -(skirt + extension) + bump_d/2   (= -59.5)
//
//  FABRICATION -- READ BEFORE CHANGING THE ROOF: this part is 3D-PRINTED
//  ROOF-FACE-DOWN. The flat top surface goes on the printer bed (the
//  wrapper's part="print" pose flips it; see CLAUDE.md s6 / s16). Every
//  roof-top feature must be self-supporting in that orientation:
//    * a bevel/chamfer on the roof-top edge must flare OUTWARD as it rises
//      from the bed (<= 45 deg from vertical) -- p_cage_roof_bevel() is a
//      true 45-deg outward chamfer and is printable as-is;
//    * do NOT add a downward-facing pocket, lip or overhang to the roof top,
//      and do NOT make the bevel an undercut (radius growing then shrinking).
//  A change that would need support material in the roof-down pose must be
//  flagged to the user, not silently made. The clip pocket + the horizontal
//  M3 bores already bridge in the slicer; keep them inspectable.
//
//  Definitions only. Geometry is emitted by control_cage(); the wrapper /
//  full assembly applies the print-pose or installed transform.
// ==========================================================================

// [bundle] begin use <params.scad>
// ==========================================================================
//  Turtle Body -- shared dimension contract
// --------------------------------------------------------------------------
//  The single source of truth for every dimension that more than one
//  subsystem depends on. Values are exposed as zero-argument functions so
//  this file can be pulled in with `use <params.scad>` (which ignores
//  top-level variable assignments) without polluting any namespace.
//
//  lib/ modules take these as DEFAULT argument values:
//      module control_cap(roof_t = p_cap_roof_t(), ...) { ... }
//  so a src/ wrapper can still override one value from its customizer block
//  while every other subsystem keeps the shared number.
//
//  Rules:
//   * one function per concept, canonical name (see CLAUDE.md cross-file table)
//   * derived values are functions of other p_*() functions, never re-typed
//   * mm throughout; names say _d (diameter), _r (radius), _t (thickness),
//     _len / _h (axial), _af (hex across-flats)
//   * do NOT add a bare `x = ...;` here -- bundle.py / lint.py will reject it
// ==========================================================================

// ---- tolerances and render quality --------------------------------------
function p_eps()          = 0.02;   // Boolean overlap / cut-through fudge
function p_fit_clearance() = 0.2;   // wood joint: TOTAL extra slot width, centred on the board
function p_fn_plastic()   = 120;    // printed PLA parts (cap, cage, axle, mold)
function p_fn_wood()      = 96;     // cut wooden parts
function p_fn_curve()     = 180;    // fine profile curves (bottle, sails)

// ---- bottle (the foundation reference) ---------------------------------
function p_bottle_d()        = 82;    // outside diameter
function p_bottle_h()        = 305;   // total height incl. ordinary screw cap
function p_bottle_wall_t()   = 0.5;   // modelling assumption, not a measurement
function p_bottle_cap_d()    = 31;    // ordinary screw cap (NOT the control-cap disk)
function p_bottle_cap_h()    = 17;    // ordinary screw cap height (rear-fin / ballast formulas)
function p_collar_d()        = 34;    // bottle collar, independent of cap diameter
function p_top_dome_h()      = 62;
function p_bottom_dome_h()   = 25;
function p_dome_power()      = 2.5;   // superellipse exponent
function p_bottle_neck_h()   = 5;
function p_bottle_collar_h() = 1;
function p_bottle_neck_d()   = p_bottle_cap_d() - 3;   // 28: neck is 3 mm under the cap
function p_bottle_base_ratio() = 0.88; // slightly narrower footprint at the base
function p_bottle_profile_steps() = 16;
// cut bottle (control head): the lower dome is removed and a short socket is
// bored so the control-cap insert slides in. Cut plane sits 5 mm above the
// bottom dome height.
function p_bottle_cut_extra()  = 5;
function p_bottle_cut_height() = p_bottom_dome_h() + p_bottle_cut_extra();   // 30

// nominal bottle interior and the cap insert that enters it
function p_bottle_socket_d() = p_bottle_d() - 2 * p_bottle_wall_t();          // 81
function p_insert_shaft_radial_clearance() = 1;
function p_insert_shaft_d()  = p_bottle_socket_d()
                             - 2 * p_insert_shaft_radial_clearance();          // 79

// ---- wooden stock -----------------------------------------------------
function p_wood_t()          = 12;    // shared board / slat thickness
function p_fin_board_w()     = 93;    // shared fin-system stock width
function p_screw_side_offset() = 25;  // mounting-hole inset from a John end

// ---- Ecojoiner port --------------------------------------------------
function p_port_length()     = 82;                 // axial length of a port
function p_port_height()     = p_bottle_d();       // opening height == bottle diameter (asserted)

// ---- M6 hardware ---------------------------------------------------
function p_m6_clearance_d()  = 6.4;   // M6 clearance hole
function p_m6_bolt_shaft_d() = 6;     // visual placeholder only
function p_m6_bolt_head_d()  = 12;
function p_m6_bolt_head_t()  = 4;

// ---- control cap (large stationary disk; see CLAUDE.md s7) ----------
//  TB-03 resolution: repository 5 mm roof / 2 mm boss is authoritative;
//  the axle (below) is derived to this datum.
function p_cap_disk_d()      = 100;   // control-cap disk (independent of p_bottle_cap_d)
function p_cap_roof_t()      = 5;     // disk / roof thickness
function p_cap_boss_depth()  = 2;     // extra projection of the centre boss into the hollow cap
function p_cap_boss_d()      = 18;
function p_cap_insert_len()  = 35;    // straight insert shaft length
function p_cap_insert_wall_t() = 4;
function p_cap_entry_chamfer_h()     = 1;
function p_cap_entry_chamfer_delta() = 1;
function p_cap_axle_bore_d() = 8.6;   // 0.3 mm radial clearance to the Ø8 shaft
function p_cap_cage_radial_clearance() = 1;   // cap disk -> cage inner wall (radial)
function p_cap_total_h()     = p_cap_roof_t() + p_cap_insert_len();           // 40
function p_cap_bearing_len() = p_cap_roof_t() + p_cap_boss_depth();           // 7

// buttons (through both cap and cage)
function p_button_upper_d()  = 17;    // clearance hole in the cap
function p_button_axis()     = "y";   // "x" or "y"
function p_button_radius()   = 24;    // radial position of the two button centres (48 mm apart)

// ---- silicone seal grooves + rings (CLAUDE.md s8) ------------------
function p_seal_groove_count()      = 2;
function p_seal_groove_axial_h()    = 2;   // groove height
function p_seal_groove_radial_depth() = 2; // groove depth
function p_seal_groove1_from_shoulder() = 12;  // groove centre, measured from the insert SHOULDER
function p_seal_groove2_from_shoulder() = 25;
function p_seal_ring_axial_t()      = 1.5;  // cast ring thickness
function p_seal_ring_radial_w()     = 5;    // NOT validated; 3.5 was a suggested milder prototype
function p_seal_groove_root_d() = p_insert_shaft_d()
                                - 2 * p_seal_groove_radial_depth();            // 75

// ---- round / hex centre axle (CLAUDE.md s9) -----------------------
//  Derived to the 5/2 cap datum (TB-03/TB-04). round_inside_cap is measured
//  from the roof underside and INCLUDES the boss -- do not add the boss again.
function p_axle_round_d()        = 8;
function p_axle_round_ext()      = 1;    // projection above the cap's outer face
function p_axle_round_inside_cap() = p_cap_insert_len() - 5;  // 30: roof underside to round end (incl. boss)
function p_axle_round_len()      = p_axle_round_inside_cap() + p_cap_roof_t() + p_axle_round_ext();  // 36
function p_axle_hex_af()         = 10.0; // shaft across-flats (0.3 mm to the Ø10.3 cage bore)
function p_axle_hex_len()        = 23;
function p_axle_join_overlap()   = 0.2;  // hex<->round Boolean overlap
function p_axle_total_len()      = p_axle_hex_len() + p_axle_round_len();
function p_axle_hex_corner_d()   = p_axle_hex_af() / cos(30);                  // ~11.55
function p_magnet_d()            = 3;    // AS5600 sensing magnet recess
function p_magnet_t()            = 1;

// ---- axle rotary shaft O-ring (waterproofs the axle bore; cast in the mold) ----
//  A round-section O-ring seated in a gland in the control-cap bore, sealing
//  against the spinning round section of the axle. ID is tied to the shaft.
function p_axle_oring_cs()     = 2.0;                                   // cross-section
function p_axle_oring_id()     = p_axle_round_d();                      // 8 -- hugs the shaft
function p_axle_oring_od()     = p_axle_oring_id() + 2 * p_axle_oring_cs();          // 12
function p_axle_oring_mean_r() = (p_axle_oring_id() + p_axle_oring_cs()) / 2;        // 5
//  gland cut into the cap bore for it
function p_cap_oring_squeeze()      = 0.25;  // radial squeeze on the seal
function p_cap_oring_gland_od()     = p_axle_oring_od() - 2 * p_cap_oring_squeeze(); // 11.5
function p_cap_oring_gland_w()      = 1.3 * p_axle_oring_cs();                       // 2.6 axial
function p_cap_oring_gland_from_face() = 3.5; // gland centre, from the cap outer face, along the bore

// ---- rotating control cage (CLAUDE.md s6) ------------------------
function p_cage_wall_t()     = 6.5;   // radial wall thickness
function p_cage_roof_t()     = 6;     // roof / surface plate thickness
function p_cage_inner_d()    = p_cap_disk_d() + 2 * p_cap_cage_radial_clearance();   // 102
function p_cage_outer_d()    = p_cage_inner_d() + 2 * p_cage_wall_t();               // 115
function p_cage_skirt_depth()   = 44;   // roof underside to the ORIGINAL skirt rim
function p_cage_peak_extension() = 20;  // crest extends this far past the original rim
function p_cage_valley_wall_h()  = 10;  // minimum wall depth between mounts
function p_cage_total_h()    = p_cage_skirt_depth() + p_cage_roof_t();              // 50 (native)
function p_cage_notch_count()   = 4;
function p_cage_notch_w()    = 22.5;  // batten groove width
function p_cage_notch_depth() = 3.7;
function p_cage_wave_segments() = 240;
function p_cage_hub_d()      = 29;
function p_cage_pocket_d()   = 26;    // top clip pocket
function p_cage_pocket_depth() = 4;
function p_cage_hex_bore_af() = 10.3; // central hex bore (0.3 mm to the Ø10.0 shaft)
function p_cage_bearing_d()  = 9;     // hemispherical bearing bump
function p_cage_bearing_count() = 8;
function p_cage_bearing_pcd() = p_cap_disk_d() - p_cage_bearing_d() + 0.5;          // 91.5
function p_cage_top_hole_d() = 18;    // central button / access hole through the roof
function p_cage_mount_hole_d() = 3.2; // two M3 clearance holes per batten / groove
function p_cage_mount_pitch()  = 32;  // vertical pitch of the pair
function p_cage_lower_hole_from_tip() = 10;
// 45-deg outward chamfer on the roof-top outer edge (0 = sharp). The cage
// prints roof-face-down, so this bevel flares OUT from the bed and stays
// printable; it is masked away around each batten groove. See lib/control_cage.scad.
function p_cage_roof_bevel() = 4;

// ---- sail apparatus (CLAUDE.md s10) ---------------------------
function p_side_batten_h()   = 205;
function p_side_batten_w()   = 20;
function p_side_batten_radial_t() = 10;
function p_top_crossbar_len() = 6 * p_bottle_d();   // 492
function p_top_crossbar_w()  = 22;
function p_top_crossbar_t()  = p_wood_t();          // 12
function p_sail_bar_axle_hole_d() = 12;             // Ø12; fits the ~11.55 hex corner dia
function p_bottom_rail_len() = 3 * p_bottle_d();    // 246
function p_bottom_rail_bottle_clearance() = 1;
function p_sail_rail_color()  = [0.56, 0.39, 0.39]; // brown (top AND bottom rails)
function p_c_piece_color()    = [1.0, 0.52, 0.20];  // orange, retained

// ---- rear fin + solar support (CLAUDE.md s11) ----------------
function p_solar_panel_w() = 148;
function p_solar_panel_h() = 223;
function p_solar_panel_t() = 2.5;    // real panel, independent of wood thickness
function p_rear_shaft_len() = p_bottle_h()
                            + (2/3) * (p_fin_board_w() - 2 * p_wood_t())
                            - p_bottle_cap_h();                                 // 334
function p_rear_half_lap_engagement() = 42;   // green/yellow interlock depth
function p_rear_fin_tab_width() = 15;
function p_rear_shaft_width()   = 59;
// TB-07: the green-slat mounting hole follows the mating Ecojoiner John, not a
// fixed 50 mm. Derived from the install transform; the john_length/2 terms
// cancel, leaving a pure function of the shared contract (= 103 at defaults).
function p_rear_shaft_hole_from_front() =
    p_rear_shaft_len() - p_screw_side_offset() - p_bottle_h()
    + p_bottle_cap_h() + p_port_height();

// ---- ballast attachment (CLAUDE.md s12) ---------------------
function p_ballast_core_w()   = p_bottle_d() - 2 * p_wood_t();                  // 58
function p_ballast_core_len() = p_bottle_h() - p_bottle_cap_h() + 6 * p_wood_t();  // 360
function p_ballast_slat_gap() = p_bottle_d();          // clear inner-face gap
function p_ballast_slat_spacing() = p_bottle_d() + p_wood_t();                  // 94
function p_ballast_board_len() = 3.5 * p_bottle_d();   // 287
function p_ballast_fin_len()   = 3 * p_bottle_d();     // 246
function p_ballast_lock_w()    = 5 * p_wood_t();       // 60
// [bundle] end   <params.scad>

// ---- native-frame Z references (for the full-assembly transform) --------
function cage_under_z(bearing_d = p_cage_bearing_d()) = bearing_d / 2;
function cage_roof_top_z(bearing_d = p_cage_bearing_d(), roof_t = p_cage_roof_t()) =
    bearing_d / 2 + roof_t;
function cage_wall_tip_z(bearing_d = p_cage_bearing_d(),
                         skirt = p_cage_skirt_depth(),
                         extension = p_cage_peak_extension()) =
    bearing_d / 2 - skirt - extension;

module control_cage(inner_d       = p_cage_inner_d(),
                    outer_d       = p_cage_outer_d(),
                    roof_t        = p_cage_roof_t(),
                    skirt         = p_cage_skirt_depth(),
                    extension     = p_cage_peak_extension(),
                    valley_wall_h = p_cage_valley_wall_h(),
                    notch_w       = p_cage_notch_w(),
                    notch_depth   = p_cage_notch_depth(),
                    notch_count   = p_cage_notch_count(),
                    m3_d          = p_cage_mount_hole_d(),
                    lower_hole_from_tip = p_cage_lower_hole_from_tip(),
                    bump_d        = p_cage_bearing_d(),
                    bump_count    = p_cage_bearing_count(),
                    bump_pcd      = p_cage_bearing_pcd(),
                    hub_d         = p_cage_hub_d(),
                    hex_bore_af   = p_cage_hex_bore_af(),
                    pocket_d      = p_cage_pocket_d(),
                    pocket_depth  = p_cage_pocket_depth(),
                    button_d      = p_cage_top_hole_d(),
                    button_r      = p_button_radius(),
                    button_angle  = 90,
                    scallops      = true,
                    roof_bevel    = p_cage_roof_bevel(),
                    wave_segments = p_cage_wave_segments(),
                    fn            = undef) {
    nn  = fn == undef ? p_fn_plastic() : fn;
    eps = p_eps();
    ri  = inner_d / 2;
    ro  = outer_d / 2;
    groove_r = ro - notch_depth;

    cage_under      = bump_d / 2;
    cage_top        = cage_under + roof_t;
    cage_bottom     = cage_under - skirt;
    cage_hub_bottom = 1;
    pocket_floor    = cage_top - pocket_depth;
    wall_tip_z      = cage_bottom - extension;
    max_wall_h      = skirt + extension;
    wave_n          = max(48, 4 * ceil(wave_segments / 4));
    mount_hole_z    = cage_bottom + skirt / 2;
    lower_hole_z    = wall_tip_z + lower_hole_from_tip;
    cut_start       = ri - m3_d;
    cut_length      = ro - cut_start + 2 * eps;

    // four identical rounded crests: max wall height at 0/90/180/270
    function edge_z(a) = wall_tip_z + (scallops ?
        (max_wall_h - valley_wall_h) * (1 - cos(4 * a)) / 2 : 0);
    hole_edge_angle = asin((m3_d / 2) / ri);

    assert(inner_d > 0 && p_cap_cage_radial_clearance() > 0);
    assert(p_cage_wall_t() > notch_depth && notch_depth > 0 && notch_w > 0);
    assert(m3_d > 0 && m3_d < notch_w);
    assert(roof_t > pocket_depth && pocket_depth > 0);
    assert(valley_wall_h > 0 && valley_wall_h < skirt);
    assert(extension >= 0);
    assert(lower_hole_from_tip > m3_d / 2 + 2
           && lower_hole_from_tip < max_wall_h - m3_d / 2);
    assert(bump_d > 0 && bump_pcd / 2 + bump_d / 2 < ri);
    assert(hex_bore_af > 10 && hex_bore_af / cos(30) < pocket_d);
    assert(hub_d > pocket_d && pocket_d > 25 && pocket_floor > cage_hub_bottom);
    assert(pocket_floor <= 6.5 && cage_top > 10.2,
           "control_cage: keep the shaft / clip axial clearances.");
    assert(button_r - button_d / 2 > hub_d / 2 && button_r + button_d / 2 < ri);
    assert(button_r + button_d / 2 < bump_pcd / 2 - bump_d / 2,
           "control_cage: button must clear the bearings at every angle.");
    assert(lower_hole_z - m3_d / 2 > edge_z(hole_edge_angle) + 2,
           "control_cage: lower M3 hole needs 2 mm material to the sine edge.");
    // FABRICATION: roof prints face-down. Bevel is chamfered off that face,
    // must leave a flat central landing, and must not undercut.
    assert(roof_bevel >= 0 && roof_bevel < roof_t,
           "control_cage: roof_bevel must be 0..roof_t.");
    assert(roof_bevel < ro - hub_d / 2 - 2,
           "control_cage: roof_bevel leaves no flat roof-top landing.");

    module groove_cuts_2d()
        for (a = [0 : 360 / notch_count : 359]) rotate(a)
            translate([groove_r, -notch_w / 2])
                square([notch_depth + eps, notch_w]);

    module outer_profile()
        difference() { circle(r = ro, $fn = nn); groove_cuts_2d(); }

    // 45-deg OUTWARD chamfer on the roof-top outer edge, masked away within
    // (notch_w/2 + roof_bevel) of each batten groove so the groove walls stay
    // square. Printable roof-down: radius only grows from the bed upward.
    module roof_bevel_cutter() {
        difference() {
            rotate_extrude($fn = nn)
                polygon([[ro - roof_bevel, cage_top + eps],
                         [ro + 1,          cage_top + eps],
                         [ro + 1,          cage_top - roof_bevel]]);
            translate([0, 0, cage_top - roof_bevel - 2 * eps])
                linear_extrude(height = roof_bevel + 4 * eps)
                    for (a = [0 : 360 / notch_count : 359]) rotate(a)
                        translate([ro - roof_bevel - eps,
                                   -(notch_w / 2 + roof_bevel)])
                            square([roof_bevel + notch_depth + 1 + 2 * eps,
                                    notch_w + 2 * roof_bevel]);
        }
    }

    module wave_ring() {
        pts = [for (i = [0 : wave_n - 1]) each let(a = i * 360 / wave_n,
                lo = edge_z(a), hi = cage_under + eps) [
            [ro * cos(a), ro * sin(a), lo], [ri * cos(a), ri * sin(a), lo],
            [ro * cos(a), ro * sin(a), hi], [ri * cos(a), ri * sin(a), hi]
        ]];
        faces = [for (i = [0 : wave_n - 1]) each let(b = 4 * i, c = 4 * ((i + 1) % wave_n)) [
            [b, c, c + 2], [b, c + 2, b + 2],
            [b + 1, b + 3, c + 3], [b + 1, c + 3, c + 1],
            [b + 2, c + 2, c + 3], [b + 2, c + 3, b + 3],
            [b, b + 1, c + 1], [b, c + 1, c]
        ]];
        polyhedron(points = pts,
                   faces = [for (f = faces) [f[2], f[1], f[0]]], convexity = 12);
    }

    module scalloped_wall() {
        difference() {
            wave_ring();
            translate([0, 0, wall_tip_z - eps])
                linear_extrude(height = max_wall_h + 3 * eps) groove_cuts_2d();
        }
    }

    module hemisphere()
        intersection() {
            sphere(d = bump_d, $fn = nn);
            translate([-bump_d, -bump_d, -bump_d])
                cube([2 * bump_d, 2 * bump_d, bump_d + eps]);
        }

    $fn = nn;
    difference() {
        union() {
            scalloped_wall();
            translate([0, 0, cage_under])
                linear_extrude(height = roof_t) outer_profile();
            translate([0, 0, cage_hub_bottom])
                cylinder(d = hub_d, h = cage_top - cage_hub_bottom);
            for (a = [0 : 360 / bump_count : 359]) rotate([0, 0, a])
                translate([bump_pcd / 2, 0, cage_under]) hemisphere();
        }
        translate([0, 0, cage_hub_bottom - eps])
            cylinder(d = hex_bore_af / cos(30),
                     h = cage_top - cage_hub_bottom + 2 * eps, $fn = 6);
        translate([0, 0, pocket_floor])
            cylinder(d = pocket_d, h = pocket_depth + eps);
        rotate([0, 0, button_angle]) translate([button_r, 0, cage_under - eps])
            cylinder(d = button_d, h = roof_t + 2 * eps);
        for (a = [0 : 90 : 270]) rotate([0, 0, a])
            for (z = [mount_hole_z, lower_hole_z])
                translate([cut_start, 0, z]) rotate([0, 90, 0])
                    cylinder(d = m3_d, h = cut_length);
        if (roof_bevel > 0) roof_bevel_cutter();
    }

    echo("CAGE: OD / ID / roof-to-tip = ", outer_d, inner_d, cage_top - wall_tip_z);
    echo("CAGE: groove w / d = ", notch_w, notch_depth,
         " | M3 dia / pitch = ", m3_d, mount_hole_z - lower_hole_z);
    echo("CAGE: prints ROOF-FACE-DOWN (flat top on the bed). roof_bevel = ",
         roof_bevel, " mm, a 45-deg OUTWARD chamfer (printable). Any new ",
         "roof-top feature must be self-supporting in that pose -- no undercut, ",
         "no downward pocket, no >45-deg overhang.");
}
// [bundle] end   <../../lib/control_cage.scad>

module _cage()
    control_cage(outer_d = (100 + cage_wall * 2 + 2),  // cap 100 + 2 clearance + 2*wall
                 roof_t = cage_roof,
                 skirt = skirt_height,
                 extension = mount_extension,
                 valley_wall_h = roof_ring_height,
                 notch_w = notch_width,
                 notch_depth = notch_depth,
                 m3_d = m3_hole_diameter,
                 lower_hole_from_tip = lower_hole_from_tip,
                 bump_d = bump_d,
                 hub_d = cage_hub_d,
                 hex_bore_af = cage_hex_af,
                 pocket_d = pocket_d,
                 pocket_depth = clip_pocket_depth,
                 button_d = button_diameter,
                 button_r = button_r,
                 button_angle = button_angle,
                 roof_bevel = roof_bevel,
                 wave_segments = wave_segments,
                 fn = curve_segments);

color([0.74, 0.77, 0.79]) {
    if (part == "print")
        translate([0, 0, cage_roof_top_z(bump_d, cage_roof)])
            rotate([180, 0, 0]) _cage();
    else if (part == "upright")
        translate([0, 0, -cage_wall_tip_z(bump_d, skirt_height, mount_extension)])
            _cage();
    else
        assert(false, str("Unknown view: ", part));
}
