// ==========================================================================
//  GENERATED FILE -- DO NOT EDIT.
//  Produced by build/build.py from components/Silicone_Ring_Mold.scad
//  Turtle Body version 2.3.1
//  Edit lib/ and src/ instead, then run: python3 build/build.py
// ==========================================================================
/*
 Hope Turtle — silicone ring mold. Units: mm. License: CERN-OHL-S-2.0.

 ONE two-part pressed mold that casts, in a single session:
  * ring_count FLAT insert-seal rings (Ø75/Ø85 × 1.5, for the cap insert
    grooves);
  * ring_count round AXLE O-RINGS, one nested in the centre of EVERY flat
    mold, so the default 2-ring mold gives two chances at a good O-ring.
    O-ring ID is tied to the sealing (round) section of the hex-shaft axle.

 The bottom plate has the flat-ring channels + a lower O-ring half-torus
 per ring + 3 male alignment pegs. The top plate has the upper O-ring
 half-tori + 3 female holes + one fill/vent per O-ring. Press together
 (pegs seat in holes), fill, cure, split, peel.

 part=mold lays BOTH plates flat and side by side (working faces up) so the
 one exported STL prints in a single job. mold_bottom / mold_top are the
 same plates alone. Nominal dims; no shrinkage. Seals NOT validated
 (CLAUDE.md s8).

 SOURCE FILE — geometry lives in lib/silicone_ring_mold.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Output] */
part = "mold"; // [mold,mold_bottom,mold_top,rings,oring]
ring_count = 2;
curve_segments = 240; // [120:24:480]

/* [Mold body] */
mold_floor_thickness = 3;
mold_spacing = 8; // gap between flat mold bodies

/* [Flat seal ring -- the LARGE ring, for the cap insert grooves]
   Tweak these to re-size the flat ring's mold cavity for a one-off STL
   export without touching lib/params.scad (which also feeds the cap
   groove geometry). Defaults below are the as-cast values that match the
   current lib/params.scad groove spec: inner Ø59.25 / outer Ø79.25 x 2.6
   thick, derived from a 79 mm groove root shrunk 25% for stretch-fit
   tension plus a 10 mm radial width. The nested axle O-ring (small ring,
   ID/OD 8/12) is not affected by these three values. */
flat_ring_inner_d  = 59.25; // mm, as-cast inner diameter
flat_ring_outer_d  = 79.25; // mm, as-cast outer diameter
flat_ring_axial_t  = 2.6;   // mm, cast thickness

// [bundle] begin use <../../lib/silicone_ring_mold.scad>
// ==========================================================================
//  Turtle Body -- silicone ring mold  (lib module)
// --------------------------------------------------------------------------
//  ONE two-part pressed mold that casts, in a single session:
//
//    * `ring_count` FLAT insert-seal rings   -- Ø75 ID / Ø85 OD x 1.5, for
//      the cap insert grooves. Tied to p_seal_groove_root_d().
//    * `ring_count` round AXLE O-RINGS       -- one nested in the centre of
//      EVERY flat-ring mold ("an additional mold circle" per ring), so the
//      default 2-ring mold yields TWO O-rings and you get two chances at a
//      good one. ID is tied to the sealing (round) section of the hex-shaft
//      axle, p_axle_oring_id() = p_axle_round_d() (8); CS 2, OD 12.
//
//  The bottom plate carries the flat-ring channels (full depth, scrape-fill),
//  the LOWER half of each O-ring torus, and THREE male alignment pegs. The
//  top plate carries the UPPER half of each O-ring torus, THREE female holes,
//  and one O-ring fill + vent per ring. Press the plates together (pegs seat
//  in holes), fill, cure, split, peel out the rings.
//
//  part = "mold"        PRINTABLE layout -- both plates flat on the bed,
//                       working faces UP, laid side by side so one STL prints
//                       both halves in a single job.
//  part = "mold_bottom" the bottom plate alone, printable (channels + pegs up)
//  part = "mold_top"    the top plate alone, printable (channel + holes up)
//  part = "rings"       every cast ring (flat rings + the O-ring tori)
//  part = "oring"       a single bare O-ring torus
//
//  Nominal dimensions; no shrinkage compensation. Seals NOT validated (s8).
//
//  Definitions only. Geometry is emitted by silicone_ring_molds().
// ==========================================================================

// [bundle] begin use <params.scad>
// ==========================================================================
//  Turtle Body -- shared dimension contract
// --------------------------------------------------------------------------
//  The single source of truth for every dimension that more than one
//  subsystem depends on. Values are exposed as zero-argument functions so
//  this file can be pulled in with `use <params.scad>` (which ignores
//  top-level variable assignments) without polluting any namespace.
//
//  lib/ modules take these as DEFAULT argument values:
//      module control_cap(roof_t = p_cap_roof_t(), ...) { ... }
//  so a src/ wrapper can still override one value from its customizer block
//  while every other subsystem keeps the shared number.
//
//  Rules:
//   * one function per concept, canonical name (see CLAUDE.md cross-file table)
//   * derived values are functions of other p_*() functions, never re-typed
//   * mm throughout; names say _d (diameter), _r (radius), _t (thickness),
//     _len / _h (axial), _af (hex across-flats)
//   * do NOT add a bare `x = ...;` here -- bundle.py / lint.py will reject it
// ==========================================================================

// ---- tolerances and render quality --------------------------------------
function p_eps()          = 0.02;   // Boolean overlap / cut-through fudge
function p_fit_clearance() = 0.2;   // wood joint: TOTAL extra slot width, centred on the board
function p_fn_plastic()   = 120;    // printed PLA parts (cap, cage, axle, mold)
function p_fn_wood()      = 96;     // cut wooden parts
function p_fn_curve()     = 180;    // fine profile curves (bottle, sails)

// ---- bottle (the foundation reference) ---------------------------------
function p_bottle_d()        = 86;    // outside diameter (was 82; other bottle dims held)
function p_bottle_h()        = 305;   // total height incl. ordinary screw cap
function p_bottle_wall_t()   = 0.5;   // modelling assumption, not a measurement
function p_bottle_cap_d()    = 31;    // ordinary screw cap (NOT the control-cap disk)
function p_bottle_cap_h()    = 17;    // ordinary screw cap height (rear-fin / ballast formulas)
function p_collar_d()        = 34;    // bottle collar, independent of cap diameter
function p_top_dome_h()      = 62;
function p_bottom_dome_h()   = 25;
function p_dome_power()      = 2.5;   // superellipse exponent
function p_bottle_neck_h()   = 5;
function p_bottle_collar_h() = 1;
function p_bottle_neck_d()   = p_bottle_cap_d() - 3;   // 28: neck is 3 mm under the cap
function p_bottle_base_ratio() = 0.88; // slightly narrower footprint at the base
function p_bottle_profile_steps() = 16;
// cut bottle (control head): the lower dome is removed and a short socket is
// bored so the control-cap insert slides in. Cut plane sits 5 mm above the
// bottom dome height.
function p_bottle_cut_extra()  = 5;
function p_bottle_cut_height() = p_bottom_dome_h() + p_bottle_cut_extra();   // 30

// nominal bottle interior and the cap insert that enters it
function p_bottle_socket_d() = p_bottle_d() - 2 * p_bottle_wall_t();          // 81
function p_insert_shaft_radial_clearance() = 1;
function p_insert_shaft_d()  = p_bottle_socket_d()
                             - 2 * p_insert_shaft_radial_clearance();          // 79

// ---- wooden stock -----------------------------------------------------
function p_wood_t()          = 12;    // shared board / slat thickness
function p_fin_board_w()     = 93;    // shared fin-system stock width
function p_screw_side_offset() = 25;  // mounting-hole inset from a John end

// ---- Ecojoiner port --------------------------------------------------
// A port must swallow the bottle's tapered top (the top dome) plus a seating
// allowance, so its axial length is DERIVED from the bottle, not fixed. This
// is the same rule the HopeTurtles.org generators use
// (port_length = taper_height + port_allowance); until 2026-09-08 lib carried
// the evaluated constant 82 instead, which silently broke the rule for any
// bottle other than the reference one. Ballast and Ecojoiner both read it.
function p_port_allowance()  = 20;                 // seating allowance beyond the dome
function p_port_length()     = p_top_dome_h() + p_port_allowance();   // 62 + 20 = 82
function p_port_height()     = p_bottle_d();       // opening height == bottle diameter (asserted)

// ---- M6 hardware ---------------------------------------------------
function p_m6_clearance_d()  = 6.4;   // M6 clearance hole
function p_m6_bolt_shaft_d() = 6;     // visual placeholder only
function p_m6_bolt_head_d()  = 12;
function p_m6_bolt_head_t()  = 4;

// ---- control cap (large stationary disk; see CLAUDE.md s7) ----------
//  TB-03 resolution: repository 5 mm roof / 2 mm boss is authoritative;
//  the axle (below) is derived to this datum.
function p_cap_disk_d()      = 100;   // control-cap disk (independent of p_bottle_cap_d)
function p_cap_roof_t()      = 5;     // disk / roof thickness
function p_cap_boss_depth()  = 1.5;   // extra projection of the centre boss into the hollow cap
                                       // (was 2; lowered 0.5 mm -> 6.5 mm axle bearing length)
function p_cap_boss_d()      = 18;
function p_cap_insert_len()  = 35;    // straight insert shaft length
function p_cap_insert_wall_t() = 4;
function p_cap_entry_chamfer_h()     = 1;
function p_cap_entry_chamfer_delta() = 1;
function p_cap_axle_bore_d() = 8.7;   // 0.35 mm radial clearance to the Ø8 shaft (was 8.6 / 0.3 mm)
function p_cap_cage_radial_clearance() = 1;   // cap disk -> cage inner wall (radial)
function p_cap_total_h()     = p_cap_roof_t() + p_cap_insert_len();           // 40
function p_cap_bearing_len() = p_cap_roof_t() + p_cap_boss_depth();           // 6.5 (was 7)

// buttons (through both cap and cage)
function p_button_upper_d()  = 17;    // clearance hole in the cap
function p_button_axis()     = "y";   // "x" or "y"
function p_button_radius()   = 25;    // radial position of the two button centres (50 mm apart;
                                       // was 24 / 48 mm -- shared with the cage's matching bore)

// ---- silicone seal grooves + rings (CLAUDE.md s8) ------------------
function p_seal_groove_count()      = 2;
function p_seal_groove_axial_h()    = 2.7; // groove height (was 3.5; retuned to just clear
                                            // the 2.6 mm ring axial thickness below, 0.1 mm margin)
function p_seal_groove_radial_depth() = 2; // groove depth
function p_seal_groove1_from_shoulder() = 12;  // groove centre, measured from the insert SHOULDER
function p_seal_groove2_from_shoulder() = 25;
function p_seal_ring_axial_t()      = 2.6;  // cast ring thickness (was 3)
function p_seal_ring_radial_w()     = 10;   // cast ring radial width (was 5; doubled). NOT validated.
function p_seal_ring_elasticity_reduction() = 0.25;
    // Cast the ring's inner diameter this fraction SMALLER than the groove
    // root it mates to, so real (stretchy) silicone is under tension --
    // and therefore actually grips -- once stretched onto the cap, instead
    // of sitting at a 1:1 as-cast fit. Tweak this here as real silicone
    // behaviour is characterized; NOT validated (see lib/silicone_ring_mold.scad).
function p_seal_groove_root_d() = p_insert_shaft_d()
                                - 2 * p_seal_groove_radial_depth();            // 79 at the 86 mm bottle

// ---- round / hex centre axle (CLAUDE.md s9) -----------------------
//  Derived to the 5/2 cap datum (TB-03/TB-04). round_inside_cap is measured
//  from the roof underside and INCLUDES the boss -- do not add the boss again.
function p_axle_round_d()        = 8;
function p_axle_round_ext()      = 1;    // projection above the cap's outer face
function p_axle_round_inside_cap() = p_cap_insert_len() - 5;  // 30: roof underside to round end (incl. boss)
function p_axle_round_len()      = p_axle_round_inside_cap() + p_cap_roof_t() + p_axle_round_ext();  // 36
function p_axle_hex_af()         = 10.0; // shaft across-flats (0.3 mm to the Ø10.3 cage bore)
function p_axle_hex_len()        = 23;
function p_axle_join_overlap()   = 0.2;  // hex<->round Boolean overlap
function p_axle_total_len()      = p_axle_hex_len() + p_axle_round_len();
function p_axle_hex_corner_d()   = p_axle_hex_af() / cos(30);                  // ~11.55
function p_magnet_d()            = 3;    // AS5600 sensing magnet recess
function p_magnet_t()            = 1;

// ---- axle rotary shaft O-ring (waterproofs the axle bore; cast in the mold) ----
//  A round-section O-ring seated in a gland in the control-cap bore, sealing
//  against the spinning round section of the axle. ID is tied to the shaft.
function p_axle_oring_cs()     = 2.0;                                   // cross-section
function p_axle_oring_id()     = p_axle_round_d();                      // 8 -- hugs the shaft
function p_axle_oring_od()     = p_axle_oring_id() + 2 * p_axle_oring_cs();          // 12
function p_axle_oring_mean_r() = (p_axle_oring_id() + p_axle_oring_cs()) / 2;        // 5
//  gland cut into the cap bore for it
function p_cap_oring_squeeze()      = 0.25;  // radial squeeze on the seal
function p_cap_oring_gland_od()     = p_axle_oring_od() - 2 * p_cap_oring_squeeze(); // 11.5
function p_cap_oring_gland_w()      = 1.3 * p_axle_oring_cs();                       // 2.6 axial
function p_cap_oring_gland_from_face() = 3.5; // gland centre, from the cap outer face, along the bore

// ---- rotating control cage (CLAUDE.md s6) ------------------------
function p_cage_wall_t()     = 6.5;   // radial wall thickness
function p_cage_roof_t()     = 4;     // roof / surface plate thickness
function p_cage_inner_d()    = p_cap_disk_d() + 2 * p_cap_cage_radial_clearance();   // 102
function p_cage_outer_d()    = p_cage_inner_d() + 2 * p_cage_wall_t();               // 115
function p_cage_skirt_depth()   = 44;   // roof underside to the ORIGINAL skirt rim
function p_cage_peak_extension() = 20;  // crest extends this far past the original rim
function p_cage_valley_wall_h()  = 10;  // minimum wall depth between mounts
function p_cage_total_h()    = p_cage_skirt_depth() + p_cage_roof_t();              // 48 (native)
function p_cage_notch_count()   = 4;
function p_cage_notch_w()    = 22.5;  // batten groove width
function p_cage_notch_depth() = 3.7;
function p_cage_wave_segments() = 240;
function p_cage_hub_d()      = 29;
function p_cage_pocket_d()   = 26;    // top clip pocket (control_cage top_pocket, OFF by default)
function p_cage_pocket_depth() = 4;   //   "        "     "
function p_cage_hex_bore_af() = 10.3; // central hex bore (0.3 mm to the Ø10.0 shaft)
function p_cage_bearing_d()  = 9;     // hemispherical bearing bump
function p_cage_bearing_count() = 8;
function p_cage_bearing_pcd() = p_cap_disk_d() - p_cage_bearing_d() + 0.5;          // 91.5
function p_cage_top_hole_d() = 18;    // central button / access hole through the roof
function p_cage_mount_hole_d() = 3.2; // two M3 clearance holes per batten / groove
function p_cage_mount_pitch()  = 32;  // vertical pitch of the pair
function p_cage_lower_hole_from_tip() = 10;
// 45-deg outward chamfer on the roof-top outer edge (0 = sharp). The cage
// prints roof-face-down, so this bevel flares OUT from the bed and stays
// printable; it runs the full perimeter, batten grooves included. See
// lib/control_cage.scad.
function p_cage_roof_bevel() = 3;

// ---- sail apparatus (CLAUDE.md s10) ---------------------------
function p_side_batten_h()   = 205;
function p_side_batten_w()   = 20;
function p_side_batten_radial_t() = 10;
function p_top_crossbar_len() = 6 * p_bottle_d();   // 492
function p_top_crossbar_w()  = 22;
function p_top_crossbar_t()  = p_wood_t();          // 12
function p_sail_bar_axle_hole_d() = 12;             // Ø12; fits the ~11.55 hex corner dia
function p_bottom_rail_len() = 3 * p_bottle_d();    // 246
function p_bottom_rail_bottle_clearance() = 1;
function p_sail_rail_color()  = [0.56, 0.39, 0.39]; // brown (top AND bottom rails)
function p_c_piece_color()    = [1.0, 0.52, 0.20];  // orange, retained

// ---- rear fin + solar support (CLAUDE.md s11) ----------------
function p_solar_panel_w() = 148;
function p_solar_panel_h() = 223;
function p_solar_panel_t() = 2.5;    // real panel, independent of wood thickness
function p_rear_shaft_len() = p_bottle_h()
                            + (2/3) * (p_fin_board_w() - 2 * p_wood_t())
                            - p_bottle_cap_h();                                 // 334
function p_rear_half_lap_engagement() = 42;   // green/yellow interlock depth
function p_rear_fin_tab_width() = 15;
function p_rear_shaft_width()   = 59;
// TB-07: the green-slat mounting hole follows the mating Ecojoiner John, not a
// fixed 50 mm. Derived from the install transform; the john_length/2 terms
// cancel, leaving a pure function of the shared contract (= 103 at defaults).
function p_rear_shaft_hole_from_front() =
    p_rear_shaft_len() - p_screw_side_offset() - p_bottle_h()
    + p_bottle_cap_h() + p_port_height();

// ---- ballast attachment (CLAUDE.md s12) ---------------------
function p_ballast_core_w()   = p_bottle_d() - 2 * p_wood_t();                  // 58
function p_ballast_core_len() = p_bottle_h() - p_bottle_cap_h() + 6 * p_wood_t();  // 360
function p_ballast_slat_gap() = p_bottle_d();          // clear inner-face gap
function p_ballast_slat_spacing() = p_bottle_d() + p_wood_t();                  // 94
function p_ballast_board_len() = 3.5 * p_bottle_d();   // 287
function p_ballast_fin_len()   = 3 * p_bottle_d();     // 246
function p_ballast_lock_w()    = 5 * p_wood_t();       // 60

// ---- neutral wood shades (used when enable_color_coding = false) -------
// With the full colour code off, every wooden subsystem still renders in its
// OWN shade of brown so the parts stay visually separable. All are warm browns
// (R > G > B) spaced by lightness. The two large fins share one darker shade so
// they read as a matched pair, distinct from the rest of their own assembly.
function p_wood_shade_sail()     = [0.85, 0.66, 0.47]; // sail frame  (lightest)
function p_wood_shade_rear_fin() = [0.72, 0.50, 0.33]; // rear-fin shafts + solar holder
function p_wood_shade_eco()      = [0.62, 0.44, 0.28]; // Ecojoiner core
function p_wood_shade_ballast()  = [0.52, 0.34, 0.22]; // ballast slats / board / locks
function p_wood_shade_fin()      = [0.40, 0.26, 0.17]; // rear fin + ballast fin, shared (darkest)
// [bundle] end   <params.scad>

// ---- cast shapes ------------------------------------------------------
// The ring is cast SMALLER than the groove it mates to (see
// p_seal_ring_elasticity_reduction()) so the stretchy silicone is under
// radial tension -- and therefore actually grips -- once stretched onto
// the cap, rather than sitting at a 1:1 as-cast fit.
function _srm_cast_inner_d(mate_d = p_seal_groove_root_d(),
                           reduction = p_seal_ring_elasticity_reduction()) =
    mate_d * (1 - reduction);

// one flat cast ring / flat-channel cutter
module ring_shape(height,
                  inner_d = _srm_cast_inner_d(),          // 59.25 (79 mating x 0.75)
                  outer_d = _srm_cast_inner_d() + 2 * p_seal_ring_radial_w(),  // 79.25
                  fn = 240) {
    difference() {
        cylinder(d = outer_d, h = height, $fn = fn);
        translate([0, 0, -p_eps()])
            cylinder(d = inner_d, h = height + 2 * p_eps(), $fn = fn);
    }
}

// the cast O-ring itself (round cross-section torus)
module oring_torus(mean_r = p_axle_oring_mean_r(),
                   tube_r = p_axle_oring_cs() / 2, fn = 240) {
    rotate_extrude($fn = fn)
        translate([mean_r, 0]) circle(r = tube_r, $fn = max(24, floor(fn / 4)));
}

// ---- the two-part pressed mold -------------------------------------
function _srm_flat_od() = _srm_cast_inner_d() + 2 * p_seal_ring_radial_w();  // 79.25 at reference params
// NOTE: outer_d is a parameter (not always _srm_flat_od()) so a caller can
// override the flat ring's outer diameter -- the rim/peg layout must follow
// whatever ring size is actually being cast.
function _srm_flat_mold_d(outer_d = _srm_flat_od()) = outer_d + 2 * _srm_press_wall();  // 101 at reference params
function _srm_press_wall() = 8;                                                 // rim for the pegs
function _srm_top_floor() = 3;                                                  // top-plate floor over the half-torus
function _srm_centres(n, spacing, outer_d = _srm_flat_od()) =
    [for (i = [0 : n - 1])
        [_srm_flat_mold_d(outer_d) / 2 + i * (_srm_flat_mold_d(outer_d) + spacing),
         _srm_flat_mold_d(outer_d) / 2]];

// bottom plate: flat-ring channels (full depth), a lower half-torus in the
// centre of EVERY flat mold, three male pegs on the parting face.
//
// PEG ANGLES ARE MIRRORED (-90/-210/-330, i.e. 270/150/30) RELATIVE TO THE
// TOP PLATE'S HOLE ANGLES (90/210/330) ON PURPOSE. srm_top_plate is modelled
// parting-face-down (its natural "as used" pose); to print it without
// support it is Z-mirrored into a face-up pose (see "mold_top" below), and
// the user then has to physically turn that printed part back over to seat
// it on the bottom plate. A physical 180 deg turn is a rotation about an
// in-plane (X or Y) axis, not a pure Z-mirror -- it also negates Y, which a
// software mirror(0,0,1) does not. So the top plate's holes land at
// (-90,-210,-330) once the printed part is actually turned over. The bottom
// plate's pegs are placed at that same mirrored set of angles so the two
// physically line up; using the *unmirrored* angles (matching the raw SCAD
// coordinates of both modules) looks right on screen but the printed pegs
// and holes end up diametrically misaligned.
module srm_bottom_plate(ring_count = 2, floor_t = 3, spacing = 8,
                        ring_axial_t = p_seal_ring_axial_t(),
                        ring_inner_d = _srm_cast_inner_d(),
                        ring_outer_d = _srm_flat_od(),
                        tube_r = p_axle_oring_cs() / 2,
                        peg_d = 4, peg_h = 4, fn = 240) {
    cs      = _srm_centres(ring_count, spacing, ring_outer_d);
    fmd     = _srm_flat_mold_d(ring_outer_d);
    part_z  = floor_t + ring_axial_t;                 // parting face
    align_r = ring_outer_d / 2 + peg_d / 2 + 2;       // pegs sit in the rim

    difference() {
        union() {
            hull() for (c = cs) translate(c) cylinder(d = fmd, h = part_z, $fn = fn);
            for (a = [-90, -210, -330])
                translate(cs[0] + align_r * [cos(a), sin(a), 0])
                    translate([0, 0, part_z - p_eps()])
                        cylinder(d = peg_d, h = peg_h + p_eps(), $fn = 32);
        }
        // flat-ring channels
        for (c = cs) translate([c[0], c[1], floor_t])
            ring_shape(ring_axial_t + p_eps(), ring_inner_d, ring_outer_d, fn);
        // lower half of the O-ring torus, centre of every flat mold
        for (c = cs) translate([c[0], c[1], part_z])
            oring_torus(tube_r = tube_r, fn = fn);
    }
}

// top plate: an upper half-torus in the centre of every flat mold, three
// female holes, one fill + vent per O-ring cavity.
// built parting-face-DOWN (Z = 0); "mold_top" flips it for printing.
// Hole angles (90/210/330) are the "as modelled" pose -- see the long note
// on srm_bottom_plate for why the bottom plate's pegs use the mirrored set.
module srm_top_plate(ring_count = 2, top_floor = _srm_top_floor(), spacing = 8,
                     tube_r = p_axle_oring_cs() / 2,
                     mean_r = p_axle_oring_mean_r(),
                     ring_axial_t = p_seal_ring_axial_t(),
                     ring_outer_d = _srm_flat_od(),
                     peg_d = 4, peg_h = 4, peg_fit = 0.35,
                     fill_d = 2, fn = 240) {
    cs      = _srm_centres(ring_count, spacing, ring_outer_d);
    fmd     = _srm_flat_mold_d(ring_outer_d);
    plate_t = top_floor + tube_r;
    align_r = ring_outer_d / 2 + peg_d / 2 + 2;

    difference() {
        hull() for (c = cs) translate(c) cylinder(d = fmd, h = plate_t, $fn = fn);
        // upper half of the O-ring torus (recessed up from the parting face)
        for (c = cs) translate([c[0], c[1], 0])
            oring_torus(tube_r = tube_r, fn = fn);
        // 3 female alignment holes
        for (a = [90, 210, 330])
            translate(cs[0] + align_r * [cos(a), sin(a), 0])
                translate([0, 0, -p_eps()])
                    cylinder(d = peg_d + peg_fit, h = peg_h + 0.5, $fn = 32);
        // fill + vent for each O-ring cavity, 180 deg apart, over the channel
        for (c = cs)
            for (a = [45, 225])
                translate([c[0], c[1], -p_eps()])
                    rotate([0, 0, a]) translate([mean_r, 0, 0])
                        cylinder(d = fill_d, h = plate_t + 2 * p_eps(), $fn = 24);
    }
}

// ---- dispatch --------------------------------------------------------
// ring_inner_d / ring_outer_d / ring_axial_t override the FLAT insert-seal
// ring's cast dimensions (default: derived from lib/params.scad's groove +
// elasticity-reduction formula). The axle O-ring nested inside each flat
// mold is not affected -- it stays tied to p_axle_oring_*().
module silicone_ring_molds(part = "mold", ring_count = 2,
                           floor_t = 3, outer_wall = 3, spacing = 8,
                           fn = 240,
                           ring_inner_d = _srm_cast_inner_d(),
                           ring_outer_d = _srm_flat_od(),
                           ring_axial_t = p_seal_ring_axial_t()) {
    tube_r  = p_axle_oring_cs() / 2;
    part_z  = floor_t + ring_axial_t;
    y_gap   = 20;   // bed gap between the two plates in the "mold" print layout
    ring_radial_w = (ring_outer_d - ring_inner_d) / 2;

    assert(ring_count >= 1 && ring_count == floor(ring_count),
           "silicone_ring_molds: ring_count must be a positive integer.");
    assert(ring_axial_t > 0 && ring_axial_t <= p_seal_groove_axial_h(),
           "Cast ring must not be taller than the groove it seats in.");
    assert(ring_outer_d > ring_inner_d,
           "silicone_ring_molds: ring_outer_d must exceed ring_inner_d.");
    assert(ring_radial_w > p_seal_groove_radial_depth(),
           "Ring must project past the groove root to grip.");
    assert(floor_t > 0 && spacing > 0);
    assert(p_axle_oring_id() > 0 && p_axle_oring_cs() > 0);
    assert(p_axle_oring_od() < ring_inner_d,
           "silicone_ring_molds: O-ring must fit inside the flat-ring bore.");

    cs = _srm_centres(ring_count, spacing, ring_outer_d);

    if (part == "mold") {
        // PRINTABLE layout: both plates flat on the bed, working faces UP,
        // side by side -- one STL, one print job, no support.
        srm_bottom_plate(ring_count, floor_t, spacing, ring_axial_t,
                         ring_inner_d, ring_outer_d, fn = fn);
        translate([0, _srm_flat_mold_d(ring_outer_d) + y_gap, 0])
            translate([0, 0, _srm_top_floor() + tube_r]) mirror([0, 0, 1])
                srm_top_plate(ring_count, spacing = spacing,
                             ring_axial_t = ring_axial_t,
                             ring_outer_d = ring_outer_d, fn = fn);
    }
    else if (part == "mold_bottom")
        srm_bottom_plate(ring_count, floor_t, spacing, ring_axial_t,
                         ring_inner_d, ring_outer_d, fn = fn);
    else if (part == "mold_top")
        // flip about Z so the channel + holes face up for printing; Y stays positive
        translate([0, 0, _srm_top_floor() + tube_r]) mirror([0, 0, 1])
            srm_top_plate(ring_count, spacing = spacing,
                         ring_axial_t = ring_axial_t,
                         ring_outer_d = ring_outer_d, fn = fn);
    else if (part == "rings") {
        for (c = cs) {
            translate([c[0], c[1], 0])
                ring_shape(ring_axial_t, ring_inner_d, ring_outer_d, fn);
            translate([c[0], c[1], tube_r]) oring_torus(fn = fn);
        }
    }
    else if (part == "oring")
        oring_torus(fn = fn);
    else
        assert(false, str("silicone_ring_molds: unknown part '", part, "'"));

    echo("MOLD: two-part pressed, plates printed side by side. Flat ring AS-CAST ID/OD/axial = ",
         ring_inner_d, ring_outer_d, ring_axial_t, " x ", ring_count,
         "; mates to groove root dia ", p_seal_groove_root_d(),
         " (elasticity_reduction ", p_seal_ring_elasticity_reduction(), ")",
         "; one centre O-ring per ring (x ", ring_count,
         "), ID/OD/CS = ", p_axle_oring_id(), p_axle_oring_od(),
         p_axle_oring_cs(), " (ID tied to axle round dia ", p_axle_round_d(),
         "). 3 pegs (bottom) + 3 holes (top) align the halves.");
}
// [bundle] end   <../../lib/silicone_ring_mold.scad>

silicone_ring_molds(part = part, ring_count = ring_count,
                    floor_t = mold_floor_thickness,
                    spacing = mold_spacing,
                    fn = curve_segments,
                    ring_inner_d = flat_ring_inner_d,
                    ring_outer_d = flat_ring_outer_d,
                    ring_axial_t = flat_ring_axial_t);
