// ==========================================================================
//  GENERATED FILE -- DO NOT EDIT.
//  Produced by build/build.py from components/Turtle_Core_Ecojoiner_v1.scad
//  Turtle Body version 1.8.3
//  Edit lib/ and src/ instead, then run: python3 build/build.py
// ==========================================================================
/*
 Hope Turtle — standalone Ecojoiner assembly. Units: mm.
 License: CERN-OHL-S-2.0.
 Six Long Johns, six Little Johns, four Final Keys, twelve pressers with M6
 bolt placeholders. All six ports keep their pressers. No bottles/fins/sails.

 SOURCE FILE — geometry lives in lib/ecojoiner.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

enable_color_coding = true;

// [bundle] begin use <../../lib/ecojoiner.scad>
// ==========================================================================
//  Turtle Body -- Ecojoiner core frame  (lib module)
// --------------------------------------------------------------------------
//  Three interlocked rectangles of Long + Little Johns, four Final Keys and
//  up to twelve pressers with visual M6 bolts. One of the six Little Johns is
//  a "Master John": identical outline, but its two top slots are cut deeper so
//  it can be dropped in last, past the already-seated Johns of the almost-
//  closed frame. Bottle dimensions are sizing inputs only -- this module never
//  emits a bottle. See CLAUDE.md s13.
//
//  Standalone output restores all six ports' pressers. The full Turtle
//  suppresses selected pressers where the rear fin and ballast attach; pass
//  the suppress flags through eco_centered_rectangle().
//
//  Definitions only. Geometry is emitted by eco_ecojoiner_only() or, for the
//  full assembly, by eco_centered_rectangle() + eco_inserted_final_key().
// ==========================================================================

// [bundle] begin use <params.scad>
// ==========================================================================
//  Turtle Body -- shared dimension contract
// --------------------------------------------------------------------------
//  The single source of truth for every dimension that more than one
//  subsystem depends on. Values are exposed as zero-argument functions so
//  this file can be pulled in with `use <params.scad>` (which ignores
//  top-level variable assignments) without polluting any namespace.
//
//  lib/ modules take these as DEFAULT argument values:
//      module control_cap(roof_t = p_cap_roof_t(), ...) { ... }
//  so a src/ wrapper can still override one value from its customizer block
//  while every other subsystem keeps the shared number.
//
//  Rules:
//   * one function per concept, canonical name (see CLAUDE.md cross-file table)
//   * derived values are functions of other p_*() functions, never re-typed
//   * mm throughout; names say _d (diameter), _r (radius), _t (thickness),
//     _len / _h (axial), _af (hex across-flats)
//   * do NOT add a bare `x = ...;` here -- bundle.py / lint.py will reject it
// ==========================================================================

// ---- tolerances and render quality --------------------------------------
function p_eps()          = 0.02;   // Boolean overlap / cut-through fudge
function p_fit_clearance() = 0.2;   // wood joint: TOTAL extra slot width, centred on the board
function p_fn_plastic()   = 120;    // printed PLA parts (cap, cage, axle, mold)
function p_fn_wood()      = 96;     // cut wooden parts
function p_fn_curve()     = 180;    // fine profile curves (bottle, sails)

// ---- bottle (the foundation reference) ---------------------------------
function p_bottle_d()        = 82;    // outside diameter
function p_bottle_h()        = 305;   // total height incl. ordinary screw cap
function p_bottle_wall_t()   = 0.5;   // modelling assumption, not a measurement
function p_bottle_cap_d()    = 31;    // ordinary screw cap (NOT the control-cap disk)
function p_bottle_cap_h()    = 17;    // ordinary screw cap height (rear-fin / ballast formulas)
function p_collar_d()        = 34;    // bottle collar, independent of cap diameter
function p_top_dome_h()      = 62;
function p_bottom_dome_h()   = 25;
function p_dome_power()      = 2.5;   // superellipse exponent
function p_bottle_neck_h()   = 5;
function p_bottle_collar_h() = 1;
function p_bottle_neck_d()   = p_bottle_cap_d() - 3;   // 28: neck is 3 mm under the cap
function p_bottle_base_ratio() = 0.88; // slightly narrower footprint at the base
function p_bottle_profile_steps() = 16;
// cut bottle (control head): the lower dome is removed and a short socket is
// bored so the control-cap insert slides in. Cut plane sits 5 mm above the
// bottom dome height.
function p_bottle_cut_extra()  = 5;
function p_bottle_cut_height() = p_bottom_dome_h() + p_bottle_cut_extra();   // 30

// nominal bottle interior and the cap insert that enters it
function p_bottle_socket_d() = p_bottle_d() - 2 * p_bottle_wall_t();          // 81
function p_insert_shaft_radial_clearance() = 1;
function p_insert_shaft_d()  = p_bottle_socket_d()
                             - 2 * p_insert_shaft_radial_clearance();          // 79

// ---- wooden stock -----------------------------------------------------
function p_wood_t()          = 12;    // shared board / slat thickness
function p_fin_board_w()     = 93;    // shared fin-system stock width
function p_screw_side_offset() = 25;  // mounting-hole inset from a John end

// ---- Ecojoiner port --------------------------------------------------
// A port must swallow the bottle's tapered top (the top dome) plus a seating
// allowance, so its axial length is DERIVED from the bottle, not fixed. This
// is the same rule the HopeTurtles.org generators use
// (port_length = taper_height + port_allowance); until 2026-09-08 lib carried
// the evaluated constant 82 instead, which silently broke the rule for any
// bottle other than the reference one. Ballast and Ecojoiner both read it.
function p_port_allowance()  = 20;                 // seating allowance beyond the dome
function p_port_length()     = p_top_dome_h() + p_port_allowance();   // 62 + 20 = 82
function p_port_height()     = p_bottle_d();       // opening height == bottle diameter (asserted)

// ---- M6 hardware ---------------------------------------------------
function p_m6_clearance_d()  = 6.4;   // M6 clearance hole
function p_m6_bolt_shaft_d() = 6;     // visual placeholder only
function p_m6_bolt_head_d()  = 12;
function p_m6_bolt_head_t()  = 4;

// ---- control cap (large stationary disk; see CLAUDE.md s7) ----------
//  TB-03 resolution: repository 5 mm roof / 2 mm boss is authoritative;
//  the axle (below) is derived to this datum.
function p_cap_disk_d()      = 100;   // control-cap disk (independent of p_bottle_cap_d)
function p_cap_roof_t()      = 5;     // disk / roof thickness
function p_cap_boss_depth()  = 2;     // extra projection of the centre boss into the hollow cap
function p_cap_boss_d()      = 18;
function p_cap_insert_len()  = 35;    // straight insert shaft length
function p_cap_insert_wall_t() = 4;
function p_cap_entry_chamfer_h()     = 1;
function p_cap_entry_chamfer_delta() = 1;
function p_cap_axle_bore_d() = 8.6;   // 0.3 mm radial clearance to the Ø8 shaft
function p_cap_cage_radial_clearance() = 1;   // cap disk -> cage inner wall (radial)
function p_cap_total_h()     = p_cap_roof_t() + p_cap_insert_len();           // 40
function p_cap_bearing_len() = p_cap_roof_t() + p_cap_boss_depth();           // 7

// buttons (through both cap and cage)
function p_button_upper_d()  = 17;    // clearance hole in the cap
function p_button_axis()     = "y";   // "x" or "y"
function p_button_radius()   = 24;    // radial position of the two button centres (48 mm apart)

// ---- silicone seal grooves + rings (CLAUDE.md s8) ------------------
function p_seal_groove_count()      = 2;
function p_seal_groove_axial_h()    = 2;   // groove height
function p_seal_groove_radial_depth() = 2; // groove depth
function p_seal_groove1_from_shoulder() = 12;  // groove centre, measured from the insert SHOULDER
function p_seal_groove2_from_shoulder() = 25;
function p_seal_ring_axial_t()      = 1.5;  // cast ring thickness
function p_seal_ring_radial_w()     = 5;    // NOT validated; 3.5 was a suggested milder prototype
function p_seal_groove_root_d() = p_insert_shaft_d()
                                - 2 * p_seal_groove_radial_depth();            // 75

// ---- round / hex centre axle (CLAUDE.md s9) -----------------------
//  Derived to the 5/2 cap datum (TB-03/TB-04). round_inside_cap is measured
//  from the roof underside and INCLUDES the boss -- do not add the boss again.
function p_axle_round_d()        = 8;
function p_axle_round_ext()      = 1;    // projection above the cap's outer face
function p_axle_round_inside_cap() = p_cap_insert_len() - 5;  // 30: roof underside to round end (incl. boss)
function p_axle_round_len()      = p_axle_round_inside_cap() + p_cap_roof_t() + p_axle_round_ext();  // 36
function p_axle_hex_af()         = 10.0; // shaft across-flats (0.3 mm to the Ø10.3 cage bore)
function p_axle_hex_len()        = 23;
function p_axle_join_overlap()   = 0.2;  // hex<->round Boolean overlap
function p_axle_total_len()      = p_axle_hex_len() + p_axle_round_len();
function p_axle_hex_corner_d()   = p_axle_hex_af() / cos(30);                  // ~11.55
function p_magnet_d()            = 3;    // AS5600 sensing magnet recess
function p_magnet_t()            = 1;

// ---- axle rotary shaft O-ring (waterproofs the axle bore; cast in the mold) ----
//  A round-section O-ring seated in a gland in the control-cap bore, sealing
//  against the spinning round section of the axle. ID is tied to the shaft.
function p_axle_oring_cs()     = 2.0;                                   // cross-section
function p_axle_oring_id()     = p_axle_round_d();                      // 8 -- hugs the shaft
function p_axle_oring_od()     = p_axle_oring_id() + 2 * p_axle_oring_cs();          // 12
function p_axle_oring_mean_r() = (p_axle_oring_id() + p_axle_oring_cs()) / 2;        // 5
//  gland cut into the cap bore for it
function p_cap_oring_squeeze()      = 0.25;  // radial squeeze on the seal
function p_cap_oring_gland_od()     = p_axle_oring_od() - 2 * p_cap_oring_squeeze(); // 11.5
function p_cap_oring_gland_w()      = 1.3 * p_axle_oring_cs();                       // 2.6 axial
function p_cap_oring_gland_from_face() = 3.5; // gland centre, from the cap outer face, along the bore

// ---- rotating control cage (CLAUDE.md s6) ------------------------
function p_cage_wall_t()     = 6.5;   // radial wall thickness
function p_cage_roof_t()     = 6;     // roof / surface plate thickness
function p_cage_inner_d()    = p_cap_disk_d() + 2 * p_cap_cage_radial_clearance();   // 102
function p_cage_outer_d()    = p_cage_inner_d() + 2 * p_cage_wall_t();               // 115
function p_cage_skirt_depth()   = 44;   // roof underside to the ORIGINAL skirt rim
function p_cage_peak_extension() = 20;  // crest extends this far past the original rim
function p_cage_valley_wall_h()  = 10;  // minimum wall depth between mounts
function p_cage_total_h()    = p_cage_skirt_depth() + p_cage_roof_t();              // 50 (native)
function p_cage_notch_count()   = 4;
function p_cage_notch_w()    = 22.5;  // batten groove width
function p_cage_notch_depth() = 3.7;
function p_cage_wave_segments() = 240;
function p_cage_hub_d()      = 29;
function p_cage_pocket_d()   = 26;    // top clip pocket
function p_cage_pocket_depth() = 4;
function p_cage_hex_bore_af() = 10.3; // central hex bore (0.3 mm to the Ø10.0 shaft)
function p_cage_bearing_d()  = 9;     // hemispherical bearing bump
function p_cage_bearing_count() = 8;
function p_cage_bearing_pcd() = p_cap_disk_d() - p_cage_bearing_d() + 0.5;          // 91.5
function p_cage_top_hole_d() = 18;    // central button / access hole through the roof
function p_cage_mount_hole_d() = 3.2; // two M3 clearance holes per batten / groove
function p_cage_mount_pitch()  = 32;  // vertical pitch of the pair
function p_cage_lower_hole_from_tip() = 10;
// 45-deg outward chamfer on the roof-top outer edge (0 = sharp). The cage
// prints roof-face-down, so this bevel flares OUT from the bed and stays
// printable; it is masked away around each batten groove. See lib/control_cage.scad.
function p_cage_roof_bevel() = 4;

// ---- sail apparatus (CLAUDE.md s10) ---------------------------
function p_side_batten_h()   = 205;
function p_side_batten_w()   = 20;
function p_side_batten_radial_t() = 10;
function p_top_crossbar_len() = 6 * p_bottle_d();   // 492
function p_top_crossbar_w()  = 22;
function p_top_crossbar_t()  = p_wood_t();          // 12
function p_sail_bar_axle_hole_d() = 12;             // Ø12; fits the ~11.55 hex corner dia
function p_bottom_rail_len() = 3 * p_bottle_d();    // 246
function p_bottom_rail_bottle_clearance() = 1;
function p_sail_rail_color()  = [0.56, 0.39, 0.39]; // brown (top AND bottom rails)
function p_c_piece_color()    = [1.0, 0.52, 0.20];  // orange, retained

// ---- rear fin + solar support (CLAUDE.md s11) ----------------
function p_solar_panel_w() = 148;
function p_solar_panel_h() = 223;
function p_solar_panel_t() = 2.5;    // real panel, independent of wood thickness
function p_rear_shaft_len() = p_bottle_h()
                            + (2/3) * (p_fin_board_w() - 2 * p_wood_t())
                            - p_bottle_cap_h();                                 // 334
function p_rear_half_lap_engagement() = 42;   // green/yellow interlock depth
function p_rear_fin_tab_width() = 15;
function p_rear_shaft_width()   = 59;
// TB-07: the green-slat mounting hole follows the mating Ecojoiner John, not a
// fixed 50 mm. Derived from the install transform; the john_length/2 terms
// cancel, leaving a pure function of the shared contract (= 103 at defaults).
function p_rear_shaft_hole_from_front() =
    p_rear_shaft_len() - p_screw_side_offset() - p_bottle_h()
    + p_bottle_cap_h() + p_port_height();

// ---- ballast attachment (CLAUDE.md s12) ---------------------
function p_ballast_core_w()   = p_bottle_d() - 2 * p_wood_t();                  // 58
function p_ballast_core_len() = p_bottle_h() - p_bottle_cap_h() + 6 * p_wood_t();  // 360
function p_ballast_slat_gap() = p_bottle_d();          // clear inner-face gap
function p_ballast_slat_spacing() = p_bottle_d() + p_wood_t();                  // 94
function p_ballast_board_len() = 3.5 * p_bottle_d();   // 287
function p_ballast_fin_len()   = 3 * p_bottle_d();     // 246
function p_ballast_lock_w()    = 5 * p_wood_t();       // 60
// [bundle] end   <params.scad>
// [bundle] begin use <util.scad>
// ==========================================================================
//  Turtle Body -- shared helper modules and functions
// --------------------------------------------------------------------------
//  Small pieces that were copy-pasted across the standalone files. Geometry
//  lives in the per-subsystem lib/ modules; this file is only glue.
//
//  Definitions only -- no top-level geometry, no top-level assignments.
// ==========================================================================

// [bundle] begin use <params.scad>
// [bundle] already inlined: params.scad
// [bundle] end   <params.scad>

// Colour wrapper for wooden parts. When colour coding is off, every wooden
// component renders in one neutral wood tone; bottles, hardware, sails and
// printed parts keep their own colours and never call this.
module wood_color(coded_color, enabled = true, neutral = [0.94, 0.83, 0.62]) {
    color(enabled ? coded_color : neutral) children();
}

// scalar clamp
function clamp(v, lo, hi) = v < lo ? lo : (v > hi ? hi : v);

// Visual-only M6 bolt: plain shaft + hex-less cylindrical head. No thread,
// no torque rating -- a placeholder for fit inspection.
//  Local Z=0 is the underside of the head; the shaft runs toward +Z from Z=0
//  (plus an optional tip_extension), the head sits at Z=-head_t..0. Matches
//  the standalone files.
module m6_bolt_placeholder(grip_length, tip_extension = 1,
                           shaft_d = undef, head_d = undef, head_t = undef,
                           color_rgb = [0.15, 0.15, 0.15], fn = 48) {
    sd = shaft_d == undef ? p_m6_bolt_shaft_d() : shaft_d;
    hd = head_d  == undef ? p_m6_bolt_head_d()  : head_d;
    ht = head_t  == undef ? p_m6_bolt_head_t()  : head_t;
    assert(grip_length > 0, "m6_bolt_placeholder: grip_length must be positive.");
    color(color_rgb)
        union() {
            cylinder(d = sd, h = grip_length + tip_extension, $fn = fn);
            translate([0, 0, -ht])
                cylinder(d = hd, h = ht, $fn = fn);
        }
}

// Regular hexagonal prism specified by across-flats width (OpenSCAD's
// cylinder($fn=6) is specified across corners, which is the usual trap).
module hex_prism_af(across_flats, h, center = false) {
    cylinder(d = across_flats / cos(30), h = h, $fn = 6, center = center);
}
// [bundle] end   <util.scad>

// ---- derived dimensions (shared contract in, one definition each) -------
function eco_slat_t()        = p_wood_t();
function eco_port_length()   = p_port_length();
function eco_port_height()   = p_port_height();
function eco_john_height()   = eco_port_height() - 2 * eco_slat_t();          // 58
function eco_john_length()   = 2 * eco_port_length() + eco_port_height()
                             + 4 * eco_slat_t();                             // 294
function eco_slot_width()    = eco_slat_t() + p_fit_clearance();             // 12.2
function eco_slot_depth()    = ceil(eco_john_height() / 2);                  // 29
// The Master John is inserted last, into an almost-closed frame, so its two
// top slots run deeper than a standard John's -- normally half the port
// height, capped at 60% of the slat's own height so enough material stays
// below the groove. Rule lifted from the HopeTurtles.org 6FC generator
// (objects/ecojoiner_6fc.py :: master_slot_depth) -- see CLAUDE.md s19.
function eco_master_slot_depth() = min(floor(eco_port_height() / 2),
                                      floor(eco_john_height() * 0.6));      // 34
function eco_long_end_span()   = eco_port_length();
function eco_little_end_span()  = eco_port_length() + eco_slat_t();
function eco_screw_y_center()  = eco_john_height() / 2;
function eco_final_key_length() = eco_port_height() + 4 * eco_slat_t();      // 130
function eco_final_key_width()  = 2 * eco_slat_t();                          // 24
function eco_presser_d()       = max(1, p_bottle_cap_d() - 1);              // 30
function eco_little_slot_1_x() = eco_little_end_span() + eco_slat_t() / 2;
function eco_little_slot_2_x() = eco_john_length() - eco_little_end_span() - eco_slat_t() / 2;
function eco_long_slot_2_x()   = eco_john_length() - eco_long_end_span() - eco_slat_t() / 2;
function eco_rectangle_y()     = eco_long_slot_2_x()
                               - (eco_long_end_span() + eco_slat_t() / 2);
function eco_frame_center()    = [eco_john_length() / 2, eco_rectangle_y() / 2,
                                  eco_john_height() / 2];
function eco_final_key_x_offset() = eco_john_height() / 2 + eco_final_key_width() / 2;
function eco_final_key_z_offset() = eco_john_height() / 2 + eco_slat_t() / 2;

module eco_assert_valid() {
    assert(eco_john_height() > 0,
           "Ecojoiner: bottle diameter must exceed twice the wood thickness.");
    assert(eco_port_height() == p_bottle_d(),
           "Ecojoiner: port_height must equal canonical bottle_diameter.");
    assert(p_bottle_cap_d() < eco_john_height(), "Ecojoiner: cap hole too large for John height.");
    assert(p_collar_d() < eco_john_height(), "Ecojoiner: collar hole too large for John height.");
    assert(eco_master_slot_depth() >= eco_slot_depth(),
           "Ecojoiner: Master John slot must be at least as deep as a standard slot.");
    assert(eco_master_slot_depth() < eco_john_height(),
           "Ecojoiner: Master John slot would cut through the slat.");
}

// ---- 2D profiles ------------------------------------------------------
module eco_top_slot(center_x, depth)
    translate([center_x - eco_slot_width() / 2, eco_john_height() - depth])
        square([eco_slot_width(), depth + 1]);

module eco_center_hole(diameter)
    translate([eco_john_length() / 2, eco_john_height() / 2]) circle(d = diameter);

module eco_screw_holes_2d() {
    translate([p_screw_side_offset(), eco_screw_y_center()]) circle(d = p_m6_clearance_d());
    translate([eco_john_length() - p_screw_side_offset(), eco_screw_y_center()])
        circle(d = p_m6_clearance_d());
}

module eco_long_john_2d()
    difference() {
        square([eco_john_length(), eco_john_height()]);
        eco_top_slot(eco_long_end_span() + eco_slat_t() / 2, eco_slot_depth());
        eco_top_slot(eco_john_length() - eco_long_end_span() - eco_slat_t() / 2, eco_slot_depth());
        eco_center_hole(p_bottle_cap_d());
    }

module eco_little_john_2d()
    difference() {
        square([eco_john_length(), eco_john_height()]);
        eco_top_slot(eco_little_end_span() + eco_slat_t() / 2, eco_slot_depth());
        eco_top_slot(eco_john_length() - eco_little_end_span() - eco_slat_t() / 2, eco_slot_depth());
        eco_center_hole(p_collar_d());
        eco_screw_holes_2d();
    }

// A Little John with deeper top slots -- the last piece fitted to the frame.
module eco_master_john_2d()
    difference() {
        square([eco_john_length(), eco_john_height()]);
        eco_top_slot(eco_little_end_span() + eco_slat_t() / 2, eco_master_slot_depth());
        eco_top_slot(eco_john_length() - eco_little_end_span() - eco_slat_t() / 2, eco_master_slot_depth());
        eco_center_hole(p_collar_d());
        eco_screw_holes_2d();
    }

// ---- 3D parts -------------------------------------------------------
module eco_long_john(colored = true)
    wood_color("yellow", colored)
        linear_extrude(height = eco_slat_t()) eco_long_john_2d();

module eco_little_john(colored = true)
    wood_color("seagreen", colored)
        linear_extrude(height = eco_slat_t()) eco_little_john_2d();

// Same family as the Little John; darker tint marks the deeper-slotted one.
module eco_master_john(colored = true)
    wood_color([0.13, 0.42, 0.28], colored)
        linear_extrude(height = eco_slat_t()) eco_master_john_2d();

module eco_final_key(colored = true)
    wood_color([0.82, 0.78, 0.05], colored)
        cube([eco_final_key_length(), eco_final_key_width(), eco_slat_t()]);

module eco_presser(colored = true)
    wood_color([0.10, 0.34, 0.20], colored)
        difference() {
            cylinder(d = eco_presser_d(), h = eco_slat_t());
            translate([0, 0, -0.1])
                cylinder(d = p_m6_clearance_d(), h = eco_slat_t() + 0.2);
        }

module eco_presser_with_m6_bolt(colored = true) {
    eco_presser(colored);
    translate([0, 0, -eco_slat_t()])
        m6_bolt_placeholder(grip_length = 2 * eco_slat_t());
}

// ---- vertical Johns + rectangle -----------------------------------
module eco_standing_little_john(target_y = 0, inside_sign = 1,
                               suppress_far_hole_presser = false,
                               suppress_near_hole_presser = false,
                               colored = true,
                               is_master = false) {
    multmatrix([[1, 0, 0, 0],
                [0, 0, 1, target_y - eco_slat_t() / 2],
                [0, 1, 0, 0],
                [0, 0, 0, 1]])
        if (is_master) eco_master_john(colored);
        else eco_little_john(colored);

    inner_face_y = target_y + inside_sign * eco_slat_t() / 2;
    for (hole_x = [p_screw_side_offset(), eco_john_length() - p_screw_side_offset()]) {
        show = !(suppress_far_hole_presser  && hole_x > eco_john_length() / 2)
             && !(suppress_near_hole_presser && hole_x < eco_john_length() / 2);
        if (show)
            translate([hole_x, inner_face_y, eco_screw_y_center()])
                rotate([inside_sign > 0 ? -90 : 90, 0, 0])
                    eco_presser_with_m6_bolt(colored);
        else
            translate([hole_x, inner_face_y, eco_screw_y_center()])
                rotate([inside_sign > 0 ? -90 : 90, 0, 0])
                    translate([0, 0, -eco_slat_t()])
                        m6_bolt_placeholder(grip_length = 2 * eco_slat_t());
    }
}

module eco_standing_flipped_long_john(target_x = 0, colored = true)
    multmatrix([[0, 0, 1, target_x - eco_slat_t() / 2],
                [-1, 0, 0, eco_long_slot_2_x()],
                [0, -1, 0, eco_john_height()],
                [0, 0, 0, 1]])
        eco_long_john(colored);

// master_first_john turns this rectangle's first standing Little John (the one
// at target_y = 0) into the deeper-slotted Master John. Exactly one of the
// three rectangles in eco_ecojoiner_only() sets it.
module eco_john_rectangle(suppress_positive_port_pressers = false,
                          suppress_negative_port_pressers = false,
                          colored = true,
                          master_first_john = false) {
    eco_standing_little_john(0, +1, suppress_positive_port_pressers,
                             suppress_negative_port_pressers, colored,
                             is_master = master_first_john);
    eco_standing_little_john(eco_rectangle_y(), -1, suppress_positive_port_pressers,
                             suppress_negative_port_pressers, colored);
    eco_standing_flipped_long_john(eco_little_slot_1_x(), colored);
    eco_standing_flipped_long_john(eco_little_slot_2_x(), colored);
}

// master_first_john is last so the four positional callers in src/Full_Turtle.scad
// (rot, suppress+, suppress-, colored) are unaffected.
module eco_centered_rectangle(rot = [0, 0, 0],
                              suppress_positive_port_pressers = false,
                              suppress_negative_port_pressers = false,
                              colored = true,
                              master_first_john = false) {
    fc = eco_frame_center();
    translate(fc) rotate(rot) translate([-fc[0], -fc[1], -fc[2]])
        eco_john_rectangle(suppress_positive_port_pressers,
                           suppress_negative_port_pressers, colored,
                           master_first_john = master_first_john);
}

module eco_inserted_final_key(x_offset, z_offset, colored = true) {
    fc = eco_frame_center();
    translate([fc[0] + x_offset - eco_final_key_width() / 2,
               fc[1] - eco_final_key_length() / 2,
               fc[2] + z_offset - eco_slat_t() / 2])
        multmatrix([[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
            eco_final_key(colored);
}

// ---- the standalone artifact --------------------------------------
module eco_ecojoiner_only(colored = true) {
    eco_assert_valid();
    eco_centered_rectangle([0, 0, 0], colored = colored);
    eco_centered_rectangle([0, 90, 90], colored = colored);
    // Third (last-seated) rectangle: its first standing John is the Master John.
    eco_centered_rectangle([90, 0, 90], colored = colored, master_first_john = true);
    for (x = [-eco_final_key_x_offset(), eco_final_key_x_offset()])
        for (z = [-eco_final_key_z_offset(), eco_final_key_z_offset()])
            eco_inserted_final_key(x, z, colored);

    echo("ECOJOINER: John L/H = ", eco_john_length(), eco_john_height(),
         " | slot depth std/master = ", eco_slot_depth(), eco_master_slot_depth(),
         " | slot w = ", eco_slot_width());
    echo("ECOJOINER: final key L/W/T = ", eco_final_key_length(),
         eco_final_key_width(), eco_slat_t(), " | presser dia = ", eco_presser_d());
}
// [bundle] end   <../../lib/ecojoiner.scad>

// Same physical orientation as the full Turtle assembly.
rotate([-90, 0, 0])
    eco_ecojoiner_only(colored = enable_color_coding);
