// ==========================================================================
//  GENERATED FILE -- DO NOT EDIT.
//  Produced by build/build.py from components/Turtle_Bottom_Ballast_Fin_v1.scad
//  Turtle Body version 1.8.3
//  Edit lib/ and src/ instead, then run: python3 build/build.py
// ==========================================================================
/*
 Hope Turtle — standalone ballast attachment. Units: mm.
 License: CERN-OHL-S-2.0.
 Two green core slats, one orange bottom board, two red lock feet, one
 yellow ballast fin. No bottle. Individual pieces lie flat on Z=0;
 the assembly raises its lowest component to Z=0.

 SOURCE FILE — geometry lives in lib/ballast_fin.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

part = "assembly"; // [assembly,core_slat,bottom_board,lock_foot,fin]
enable_color_coding = true;
ballast_fin_inspection_pullout = 0; // mm; 0 seats the fin

// [bundle] begin use <../../lib/ballast_fin.scad>
// ==========================================================================
//  Turtle Body -- bottom ballast attachment  (lib module)
// --------------------------------------------------------------------------
//  Two green core slats, one orange bottom board, two red lock feet, one
//  yellow ballast fin. No bottle. See CLAUDE.md s12.
//
//  Use clear inner-face spacing (= bottle_diameter), not centre spacing, for
//  bottle clearance. The yellow fin's bottle-seat cut is enlarged by one
//  stock thickness so the bottle clears it -- preserved here. Ballast joints
//  keep nominal stock slot widths (the rear fin's 0.2 mm allowance is NOT
//  added here).
//
//  Definitions only. Geometry is emitted by local_ballast_assembly() or the
//  individual part modules.
// ==========================================================================

// [bundle] begin use <params.scad>
// ==========================================================================
//  Turtle Body -- shared dimension contract
// --------------------------------------------------------------------------
//  The single source of truth for every dimension that more than one
//  subsystem depends on. Values are exposed as zero-argument functions so
//  this file can be pulled in with `use <params.scad>` (which ignores
//  top-level variable assignments) without polluting any namespace.
//
//  lib/ modules take these as DEFAULT argument values:
//      module control_cap(roof_t = p_cap_roof_t(), ...) { ... }
//  so a src/ wrapper can still override one value from its customizer block
//  while every other subsystem keeps the shared number.
//
//  Rules:
//   * one function per concept, canonical name (see CLAUDE.md cross-file table)
//   * derived values are functions of other p_*() functions, never re-typed
//   * mm throughout; names say _d (diameter), _r (radius), _t (thickness),
//     _len / _h (axial), _af (hex across-flats)
//   * do NOT add a bare `x = ...;` here -- bundle.py / lint.py will reject it
// ==========================================================================

// ---- tolerances and render quality --------------------------------------
function p_eps()          = 0.02;   // Boolean overlap / cut-through fudge
function p_fit_clearance() = 0.2;   // wood joint: TOTAL extra slot width, centred on the board
function p_fn_plastic()   = 120;    // printed PLA parts (cap, cage, axle, mold)
function p_fn_wood()      = 96;     // cut wooden parts
function p_fn_curve()     = 180;    // fine profile curves (bottle, sails)

// ---- bottle (the foundation reference) ---------------------------------
function p_bottle_d()        = 82;    // outside diameter
function p_bottle_h()        = 305;   // total height incl. ordinary screw cap
function p_bottle_wall_t()   = 0.5;   // modelling assumption, not a measurement
function p_bottle_cap_d()    = 31;    // ordinary screw cap (NOT the control-cap disk)
function p_bottle_cap_h()    = 17;    // ordinary screw cap height (rear-fin / ballast formulas)
function p_collar_d()        = 34;    // bottle collar, independent of cap diameter
function p_top_dome_h()      = 62;
function p_bottom_dome_h()   = 25;
function p_dome_power()      = 2.5;   // superellipse exponent
function p_bottle_neck_h()   = 5;
function p_bottle_collar_h() = 1;
function p_bottle_neck_d()   = p_bottle_cap_d() - 3;   // 28: neck is 3 mm under the cap
function p_bottle_base_ratio() = 0.88; // slightly narrower footprint at the base
function p_bottle_profile_steps() = 16;
// cut bottle (control head): the lower dome is removed and a short socket is
// bored so the control-cap insert slides in. Cut plane sits 5 mm above the
// bottom dome height.
function p_bottle_cut_extra()  = 5;
function p_bottle_cut_height() = p_bottom_dome_h() + p_bottle_cut_extra();   // 30

// nominal bottle interior and the cap insert that enters it
function p_bottle_socket_d() = p_bottle_d() - 2 * p_bottle_wall_t();          // 81
function p_insert_shaft_radial_clearance() = 1;
function p_insert_shaft_d()  = p_bottle_socket_d()
                             - 2 * p_insert_shaft_radial_clearance();          // 79

// ---- wooden stock -----------------------------------------------------
function p_wood_t()          = 12;    // shared board / slat thickness
function p_fin_board_w()     = 93;    // shared fin-system stock width
function p_screw_side_offset() = 25;  // mounting-hole inset from a John end

// ---- Ecojoiner port --------------------------------------------------
// A port must swallow the bottle's tapered top (the top dome) plus a seating
// allowance, so its axial length is DERIVED from the bottle, not fixed. This
// is the same rule the HopeTurtles.org generators use
// (port_length = taper_height + port_allowance); until 2026-09-08 lib carried
// the evaluated constant 82 instead, which silently broke the rule for any
// bottle other than the reference one. Ballast and Ecojoiner both read it.
function p_port_allowance()  = 20;                 // seating allowance beyond the dome
function p_port_length()     = p_top_dome_h() + p_port_allowance();   // 62 + 20 = 82
function p_port_height()     = p_bottle_d();       // opening height == bottle diameter (asserted)

// ---- M6 hardware ---------------------------------------------------
function p_m6_clearance_d()  = 6.4;   // M6 clearance hole
function p_m6_bolt_shaft_d() = 6;     // visual placeholder only
function p_m6_bolt_head_d()  = 12;
function p_m6_bolt_head_t()  = 4;

// ---- control cap (large stationary disk; see CLAUDE.md s7) ----------
//  TB-03 resolution: repository 5 mm roof / 2 mm boss is authoritative;
//  the axle (below) is derived to this datum.
function p_cap_disk_d()      = 100;   // control-cap disk (independent of p_bottle_cap_d)
function p_cap_roof_t()      = 5;     // disk / roof thickness
function p_cap_boss_depth()  = 2;     // extra projection of the centre boss into the hollow cap
function p_cap_boss_d()      = 18;
function p_cap_insert_len()  = 35;    // straight insert shaft length
function p_cap_insert_wall_t() = 4;
function p_cap_entry_chamfer_h()     = 1;
function p_cap_entry_chamfer_delta() = 1;
function p_cap_axle_bore_d() = 8.6;   // 0.3 mm radial clearance to the Ø8 shaft
function p_cap_cage_radial_clearance() = 1;   // cap disk -> cage inner wall (radial)
function p_cap_total_h()     = p_cap_roof_t() + p_cap_insert_len();           // 40
function p_cap_bearing_len() = p_cap_roof_t() + p_cap_boss_depth();           // 7

// buttons (through both cap and cage)
function p_button_upper_d()  = 17;    // clearance hole in the cap
function p_button_axis()     = "y";   // "x" or "y"
function p_button_radius()   = 24;    // radial position of the two button centres (48 mm apart)

// ---- silicone seal grooves + rings (CLAUDE.md s8) ------------------
function p_seal_groove_count()      = 2;
function p_seal_groove_axial_h()    = 2;   // groove height
function p_seal_groove_radial_depth() = 2; // groove depth
function p_seal_groove1_from_shoulder() = 12;  // groove centre, measured from the insert SHOULDER
function p_seal_groove2_from_shoulder() = 25;
function p_seal_ring_axial_t()      = 1.5;  // cast ring thickness
function p_seal_ring_radial_w()     = 5;    // NOT validated; 3.5 was a suggested milder prototype
function p_seal_groove_root_d() = p_insert_shaft_d()
                                - 2 * p_seal_groove_radial_depth();            // 75

// ---- round / hex centre axle (CLAUDE.md s9) -----------------------
//  Derived to the 5/2 cap datum (TB-03/TB-04). round_inside_cap is measured
//  from the roof underside and INCLUDES the boss -- do not add the boss again.
function p_axle_round_d()        = 8;
function p_axle_round_ext()      = 1;    // projection above the cap's outer face
function p_axle_round_inside_cap() = p_cap_insert_len() - 5;  // 30: roof underside to round end (incl. boss)
function p_axle_round_len()      = p_axle_round_inside_cap() + p_cap_roof_t() + p_axle_round_ext();  // 36
function p_axle_hex_af()         = 10.0; // shaft across-flats (0.3 mm to the Ø10.3 cage bore)
function p_axle_hex_len()        = 23;
function p_axle_join_overlap()   = 0.2;  // hex<->round Boolean overlap
function p_axle_total_len()      = p_axle_hex_len() + p_axle_round_len();
function p_axle_hex_corner_d()   = p_axle_hex_af() / cos(30);                  // ~11.55
function p_magnet_d()            = 3;    // AS5600 sensing magnet recess
function p_magnet_t()            = 1;

// ---- axle rotary shaft O-ring (waterproofs the axle bore; cast in the mold) ----
//  A round-section O-ring seated in a gland in the control-cap bore, sealing
//  against the spinning round section of the axle. ID is tied to the shaft.
function p_axle_oring_cs()     = 2.0;                                   // cross-section
function p_axle_oring_id()     = p_axle_round_d();                      // 8 -- hugs the shaft
function p_axle_oring_od()     = p_axle_oring_id() + 2 * p_axle_oring_cs();          // 12
function p_axle_oring_mean_r() = (p_axle_oring_id() + p_axle_oring_cs()) / 2;        // 5
//  gland cut into the cap bore for it
function p_cap_oring_squeeze()      = 0.25;  // radial squeeze on the seal
function p_cap_oring_gland_od()     = p_axle_oring_od() - 2 * p_cap_oring_squeeze(); // 11.5
function p_cap_oring_gland_w()      = 1.3 * p_axle_oring_cs();                       // 2.6 axial
function p_cap_oring_gland_from_face() = 3.5; // gland centre, from the cap outer face, along the bore

// ---- rotating control cage (CLAUDE.md s6) ------------------------
function p_cage_wall_t()     = 6.5;   // radial wall thickness
function p_cage_roof_t()     = 6;     // roof / surface plate thickness
function p_cage_inner_d()    = p_cap_disk_d() + 2 * p_cap_cage_radial_clearance();   // 102
function p_cage_outer_d()    = p_cage_inner_d() + 2 * p_cage_wall_t();               // 115
function p_cage_skirt_depth()   = 44;   // roof underside to the ORIGINAL skirt rim
function p_cage_peak_extension() = 20;  // crest extends this far past the original rim
function p_cage_valley_wall_h()  = 10;  // minimum wall depth between mounts
function p_cage_total_h()    = p_cage_skirt_depth() + p_cage_roof_t();              // 50 (native)
function p_cage_notch_count()   = 4;
function p_cage_notch_w()    = 22.5;  // batten groove width
function p_cage_notch_depth() = 3.7;
function p_cage_wave_segments() = 240;
function p_cage_hub_d()      = 29;
function p_cage_pocket_d()   = 26;    // top clip pocket
function p_cage_pocket_depth() = 4;
function p_cage_hex_bore_af() = 10.3; // central hex bore (0.3 mm to the Ø10.0 shaft)
function p_cage_bearing_d()  = 9;     // hemispherical bearing bump
function p_cage_bearing_count() = 8;
function p_cage_bearing_pcd() = p_cap_disk_d() - p_cage_bearing_d() + 0.5;          // 91.5
function p_cage_top_hole_d() = 18;    // central button / access hole through the roof
function p_cage_mount_hole_d() = 3.2; // two M3 clearance holes per batten / groove
function p_cage_mount_pitch()  = 32;  // vertical pitch of the pair
function p_cage_lower_hole_from_tip() = 10;
// 45-deg outward chamfer on the roof-top outer edge (0 = sharp). The cage
// prints roof-face-down, so this bevel flares OUT from the bed and stays
// printable; it is masked away around each batten groove. See lib/control_cage.scad.
function p_cage_roof_bevel() = 4;

// ---- sail apparatus (CLAUDE.md s10) ---------------------------
function p_side_batten_h()   = 205;
function p_side_batten_w()   = 20;
function p_side_batten_radial_t() = 10;
function p_top_crossbar_len() = 6 * p_bottle_d();   // 492
function p_top_crossbar_w()  = 22;
function p_top_crossbar_t()  = p_wood_t();          // 12
function p_sail_bar_axle_hole_d() = 12;             // Ø12; fits the ~11.55 hex corner dia
function p_bottom_rail_len() = 3 * p_bottle_d();    // 246
function p_bottom_rail_bottle_clearance() = 1;
function p_sail_rail_color()  = [0.56, 0.39, 0.39]; // brown (top AND bottom rails)
function p_c_piece_color()    = [1.0, 0.52, 0.20];  // orange, retained

// ---- rear fin + solar support (CLAUDE.md s11) ----------------
function p_solar_panel_w() = 148;
function p_solar_panel_h() = 223;
function p_solar_panel_t() = 2.5;    // real panel, independent of wood thickness
function p_rear_shaft_len() = p_bottle_h()
                            + (2/3) * (p_fin_board_w() - 2 * p_wood_t())
                            - p_bottle_cap_h();                                 // 334
function p_rear_half_lap_engagement() = 42;   // green/yellow interlock depth
function p_rear_fin_tab_width() = 15;
function p_rear_shaft_width()   = 59;
// TB-07: the green-slat mounting hole follows the mating Ecojoiner John, not a
// fixed 50 mm. Derived from the install transform; the john_length/2 terms
// cancel, leaving a pure function of the shared contract (= 103 at defaults).
function p_rear_shaft_hole_from_front() =
    p_rear_shaft_len() - p_screw_side_offset() - p_bottle_h()
    + p_bottle_cap_h() + p_port_height();

// ---- ballast attachment (CLAUDE.md s12) ---------------------
function p_ballast_core_w()   = p_bottle_d() - 2 * p_wood_t();                  // 58
function p_ballast_core_len() = p_bottle_h() - p_bottle_cap_h() + 6 * p_wood_t();  // 360
function p_ballast_slat_gap() = p_bottle_d();          // clear inner-face gap
function p_ballast_slat_spacing() = p_bottle_d() + p_wood_t();                  // 94
function p_ballast_board_len() = 3.5 * p_bottle_d();   // 287
function p_ballast_fin_len()   = 3 * p_bottle_d();     // 246
function p_ballast_lock_w()    = 5 * p_wood_t();       // 60
// [bundle] end   <params.scad>
// [bundle] begin use <util.scad>
// ==========================================================================
//  Turtle Body -- shared helper modules and functions
// --------------------------------------------------------------------------
//  Small pieces that were copy-pasted across the standalone files. Geometry
//  lives in the per-subsystem lib/ modules; this file is only glue.
//
//  Definitions only -- no top-level geometry, no top-level assignments.
// ==========================================================================

// [bundle] begin use <params.scad>
// [bundle] already inlined: params.scad
// [bundle] end   <params.scad>

// Colour wrapper for wooden parts. When colour coding is off, every wooden
// component renders in one neutral wood tone; bottles, hardware, sails and
// printed parts keep their own colours and never call this.
module wood_color(coded_color, enabled = true, neutral = [0.94, 0.83, 0.62]) {
    color(enabled ? coded_color : neutral) children();
}

// scalar clamp
function clamp(v, lo, hi) = v < lo ? lo : (v > hi ? hi : v);

// Visual-only M6 bolt: plain shaft + hex-less cylindrical head. No thread,
// no torque rating -- a placeholder for fit inspection.
//  Local Z=0 is the underside of the head; the shaft runs toward +Z from Z=0
//  (plus an optional tip_extension), the head sits at Z=-head_t..0. Matches
//  the standalone files.
module m6_bolt_placeholder(grip_length, tip_extension = 1,
                           shaft_d = undef, head_d = undef, head_t = undef,
                           color_rgb = [0.15, 0.15, 0.15], fn = 48) {
    sd = shaft_d == undef ? p_m6_bolt_shaft_d() : shaft_d;
    hd = head_d  == undef ? p_m6_bolt_head_d()  : head_d;
    ht = head_t  == undef ? p_m6_bolt_head_t()  : head_t;
    assert(grip_length > 0, "m6_bolt_placeholder: grip_length must be positive.");
    color(color_rgb)
        union() {
            cylinder(d = sd, h = grip_length + tip_extension, $fn = fn);
            translate([0, 0, -ht])
                cylinder(d = hd, h = ht, $fn = fn);
        }
}

// Regular hexagonal prism specified by across-flats width (OpenSCAD's
// cylinder($fn=6) is specified across corners, which is the usual trap).
module hex_prism_af(across_flats, h, center = false) {
    cylinder(d = across_flats / cos(30), h = h, $fn = 6, center = center);
}
// [bundle] end   <util.scad>

function bl_t()            = p_wood_t();
function bl_core_w()       = p_bottle_d() - 2 * bl_t();                          // 58
function bl_core_h()       = p_bottle_h() - p_bottle_cap_h() + 6.0 * bl_t();     // 360
function bl_lower_lobe()   = 2 * bl_t();
function bl_upper_lobe()   = 2 * bl_t();
function bl_core_slot_h()  = bl_t();
function bl_core_slot_depth() = bl_core_w() / 2;
function bl_neck_w()       = p_bottle_d() - 3 * bl_t();                          // 46
function bl_shoulder_step()   = bl_core_w() - bl_neck_w();                       // 12
function bl_upper_diag_start() = bl_core_h() - p_port_height();
function bl_upper_neck_start() = bl_upper_diag_start() - bl_shoulder_step();
function bl_core_slot_z0() = bl_lower_lobe();
function bl_core_slot_z1() = bl_core_slot_z0() + bl_core_slot_h();
function bl_lower_full_return() = bl_core_slot_z1() + bl_upper_lobe();
function bl_lower_neck_start()  = bl_lower_full_return() + bl_shoulder_step();
function bl_mount_hole_from_top() = p_port_length() + bl_t() - p_screw_side_offset();  // 69
function bl_mount_hole_x()  = bl_core_w() / 2;
function bl_mount_hole_y()  = bl_core_h() - bl_mount_hole_from_top();

function bl_board_len()    = 3.5 * p_bottle_d();                                 // 287
function bl_board_w()      = p_fin_board_w();                                    // 93
function bl_board_slot_w() = bl_t();
function bl_board_slot_depth()  = p_fin_board_w() / 3;
function bl_center_slot_depth() = p_bottle_d() / 2;
function bl_center_slot()  = bl_board_len() / 2;
function bl_slat_spacing() = p_bottle_d() + bl_t();                             // 94
function bl_left_slot()    = bl_center_slot() - bl_slat_spacing() / 2;
function bl_right_slot()   = bl_center_slot() + bl_slat_spacing() / 2;
function bl_end_slot_offset() = 2 * bl_t();
function bl_left_end_slot_x0()  = bl_end_slot_offset();
function bl_right_end_slot_x0() = bl_board_len() - bl_end_slot_offset() - bl_board_slot_w();

function bl_lock_w()       = 5 * bl_t();                                         // 60
function bl_lock_h()       = 5 * bl_t();
function bl_lock_t()       = bl_t();
function bl_lock_slot_depth() = bl_lock_w() / 2;
function bl_lock_slot_h()  = bl_t();
function bl_lock_chamfer() = 1.5 * bl_t();

function bl_fin_len()      = 3 * p_bottle_d();                                   // 246
function bl_fin_h()        = p_fin_board_w();                                    // 93
function bl_fin_t()        = bl_t();
function bl_fin_lower_protrusion() = 2 * bl_t();
function bl_fin_slot_h()   = bl_t();
function bl_fin_slot_depth()   = p_bottle_d() / 2;
function bl_fin_upper_cut_depth() = p_bottle_d() + bl_t();   // +1 stock thickness so the bottle clears
function bl_fin_upper_cut_z0()    = bl_fin_lower_protrusion() + bl_fin_slot_h() + 1.5 * bl_t();
function bl_fin_front_chamfer()   = 1.5 * bl_t();

module bl_assert_valid() {
    t = bl_t();
    assert(p_bottle_h() > p_bottle_cap_h() && t > 0 && p_bottle_d() > 3 * t);
    assert(bl_core_h() - p_bottle_d() - t > 6 * t, "ballast: slat shoulders overlap.");
    assert(p_m6_clearance_d() > 0 && p_m6_clearance_d() < p_bottle_d() - 2 * t);
    assert(bl_mount_hole_from_top() > p_m6_clearance_d() / 2
           && bl_mount_hole_from_top() < p_bottle_d() - p_m6_clearance_d() / 2,
           "ballast: mount hole misses the upper slat end.");
    assert(p_fin_board_w() > max(4.5 * t, p_bottle_d() / 2), "ballast: fin board too narrow.");
    assert(bl_core_w() == p_port_height() - 2 * t,
           "ballast: slat width must use the shared bottle diameter.");
    assert(abs((bl_core_h() - bl_upper_diag_start()) - p_port_height()) < 0.001,
           "ballast: top shoulder cut must begin one port_height below the slat top.");
    assert(abs((bl_slat_spacing() - bl_t()) - p_bottle_d()) < 0.001,
           "ballast: slat inner-face gap must equal the shared bottle diameter.");
    assert(abs(bl_center_slot_depth() - bl_fin_slot_depth()) < 0.001,
           "ballast: orange-base and yellow-fin slots must have equal depth.");
}

// ---- 2D profiles + parts -------------------------------------------
module bl_core_profile_2d()
    polygon([[0, 0], [bl_core_w(), 0],
             [bl_core_w(), bl_core_h()], [0, bl_core_h()],
             [0, bl_upper_diag_start()],
             [bl_shoulder_step(), bl_upper_neck_start()],
             [bl_shoulder_step(), bl_lower_neck_start()],
             [0, bl_lower_full_return()],
             [0, bl_core_slot_z1()],
             [bl_core_slot_depth(), bl_core_slot_z1()],
             [bl_core_slot_depth(), bl_core_slot_z0()],
             [0, bl_core_slot_z0()]]);

module ballast_core_slat_part(colored = true)
    wood_color([0.12, 0.38, 0.20], colored)
        linear_extrude(height = bl_t()) difference() {
            bl_core_profile_2d();
            translate([bl_mount_hole_x(), bl_mount_hole_y()])
                circle(d = p_m6_clearance_d(), $fn = 48);
        }

module ballast_bottom_board_part(colored = true) {
    e = 0.01;
    wood_color([0.90, 0.38, 0.06], colored)
    linear_extrude(height = bl_t()) difference() {
        square([bl_board_len(), bl_board_w()]);
        translate([bl_left_slot() - bl_board_slot_w() / 2, -e])
            square([bl_board_slot_w(), bl_board_slot_depth() + e]);
        translate([bl_center_slot() - bl_board_slot_w() / 2, -e])
            square([bl_board_slot_w(), bl_center_slot_depth() + e]);
        translate([bl_right_slot() - bl_board_slot_w() / 2, -e])
            square([bl_board_slot_w(), bl_board_slot_depth() + e]);
        translate([bl_left_end_slot_x0(), bl_board_w() - bl_board_slot_depth()])
            square([bl_board_slot_w(), bl_board_slot_depth() + e]);
        translate([bl_right_end_slot_x0(), bl_board_w() - bl_board_slot_depth()])
            square([bl_board_slot_w(), bl_board_slot_depth() + e]);
    }
}

module bl_lock_profile_2d() {
    y0 = (bl_lock_h() - bl_lock_slot_h()) / 2;
    y1 = y0 + bl_lock_slot_h();
    ch = bl_lock_chamfer();
    polygon([[0, 0], [bl_lock_w() - ch, 0], [bl_lock_w(), ch],
             [bl_lock_w(), bl_lock_h() - ch], [bl_lock_w() - ch, bl_lock_h()],
             [0, bl_lock_h()], [0, y1], [bl_lock_slot_depth(), y1],
             [bl_lock_slot_depth(), y0], [0, y0]]);
}

module ballast_lock_part(colored = true)
    wood_color([0.70, 0.12, 0.10], colored)
        linear_extrude(height = bl_lock_t()) bl_lock_profile_2d();

module bl_fin_profile_2d() {
    e = 0.01; ch = bl_fin_front_chamfer();
    difference() {
        polygon([[ch, 0], [bl_fin_len(), 0], [bl_fin_len(), bl_fin_h()],
                 [0, bl_fin_h()], [0, ch]]);
        translate([-e, bl_fin_lower_protrusion()])
            square([bl_fin_slot_depth() + e, bl_fin_slot_h()]);
        translate([-e, bl_fin_upper_cut_z0()])
            square([bl_fin_upper_cut_depth() + e, bl_fin_h() - bl_fin_upper_cut_z0() + e]);
    }
}

module ballast_fin_part(colored = true)
    wood_color([0.95, 0.72, 0.02], colored)
        linear_extrude(height = bl_fin_t()) bl_fin_profile_2d();

// ---- local assembly ------------------------------------------------
module bl_installed_green_slat(slot_center_x, colored = true)
    multmatrix([[0, 0, 1, slot_center_x - bl_t() / 2],
                [-1, 0, 0, bl_core_w()],
                [0, 1, 0, -bl_core_slot_z0()],
                [0, 0, 0, 1]])
        ballast_core_slat_part(colored);

module bl_installed_lock(slot_x0, colored = true) {
    lock_center_x = slot_x0 + bl_board_slot_w() / 2;
    lock_origin_y = (bl_board_w() - bl_board_slot_depth()) - bl_lock_slot_depth();
    y0 = (bl_lock_h() - bl_lock_slot_h()) / 2;
    multmatrix([[0, 0, 1, lock_center_x - bl_lock_t() / 2],
                [1, 0, 0, lock_origin_y],
                [0, 1, 0, -y0],
                [0, 0, 0, 1]])
        ballast_lock_part(colored);
}

module bl_installed_fin(inspection_pullout = 0, colored = true) {
    fin_origin_y = bl_center_slot_depth() + bl_fin_slot_depth() + inspection_pullout;
    multmatrix([[0, 0, 1, bl_center_slot() - bl_fin_t() / 2],
                [-1, 0, 0, fin_origin_y],
                [0, 1, 0, -bl_fin_lower_protrusion()],
                [0, 0, 0, 1]])
        ballast_fin_part(colored);
}

module local_ballast_assembly(inspection_pullout = 0, colored = true) {
    bl_assert_valid();
    ballast_bottom_board_part(colored);
    bl_installed_lock(bl_left_end_slot_x0(), colored);
    bl_installed_lock(bl_right_end_slot_x0(), colored);
    bl_installed_green_slat(bl_left_slot(), colored);
    bl_installed_green_slat(bl_right_slot(), colored);
    bl_installed_fin(inspection_pullout, colored);

    echo("BALLAST: slat w/len/t = ", bl_core_w(), bl_core_h(), bl_t(),
         " | inner-face gap = ", bl_slat_spacing() - bl_t(),
         " | M6 from slat top = ", bl_mount_hole_from_top());
}
// [bundle] end   <../../lib/ballast_fin.scad>

if (part == "assembly") {
    translate([0, 0, max(bl_lower_lobe(),
                         (bl_lock_h() - bl_lock_slot_h()) / 2,
                         bl_fin_lower_protrusion())])
        local_ballast_assembly(inspection_pullout = ballast_fin_inspection_pullout,
                               colored = enable_color_coding);
} else if (part == "core_slat") {
    ballast_core_slat_part(colored = enable_color_coding);
} else if (part == "bottom_board") {
    ballast_bottom_board_part(colored = enable_color_coding);
} else if (part == "lock_foot") {
    ballast_lock_part(colored = enable_color_coding);
} else if (part == "fin") {
    ballast_fin_part(colored = enable_color_coding);
} else {
    assert(false, str("Unknown part: ", part));
}
