/*
 Hope Turtle — control cap for the current full-turtle sine cage. Units: mm.
 License: CERN-OHL-S-2.0.
 Cap disk 100 mm; matching cage cavity 102 mm (1 mm radial clearance).
 Print bearing face down at Z=0, open insert + boss facing up.
 5 mm roof + 2 mm internal boss (TB-03).
 The axle bore carries an O-ring gland (rotary seal on the spinning axle
 round section) -- waterproofs the bore. O-ring is cast in Silicone_Ring_Mold.
 Side tabs (two internal cavity ribs + lip extension, on by default) are a
 fit/registration experiment -- not validated. See lib/control_cap.scad.
 Each tab carries a 5 mm wire-routing channel down to the cavity, for
 button wiring.

 SOURCE FILE — geometry lives in lib/control_cap.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Cap body] */
top_disk_thickness  = 5;   // roof / disk thickness
centre_boss_depth   = 1.5; // extra projection of the boss into the hollow cap (was 2; lowered 0.5 mm)
centre_boss_diameter = 18;
cup_wall_thickness  = 4;
insert_total_h      = 35;
entry_chamfer_h     = 1;
entry_chamfer_delta = 1;

/* [Axle and buttons] */
shaft_hole_d   = 8.7;  // 0.35 mm radial clearance to the Ø8 axle (was 8.6 / 0.3 mm)
button_upper_d = 17;
button_axis    = "y"; // [x,y]
hole_spacing_cc = 25;  // radial position of the two button centres (was 24; moved 1 mm out,
                        // shared with the cage's matching bore via p_button_radius())

/* [Axle O-ring gland] */
oring_gland_enable = true;
oring_gland_od = 11.5;      // groove bottom diameter in the bore
oring_gland_width = 2.6;    // groove axial width
oring_gland_from_face = 3.5; // groove centre, below the cap outer face

/* [Silicone band channels] */
band_channels_enable = true;
band_count = 2;             // [0:1:2]
band1_center_z_local = 12;  // groove centre, from the insert shoulder
band2_center_z_local = 25;
band_channel_w = 2.7;      // groove axial height (matches the retuned mold ring)
band_channel_depth = 2;    // groove radial depth

/* [Side tabs] */
// Two internal ribs on the hollow insert cavity's inner wall, on the button
// axis, running the full cavity height then continuing past the top lip as
// a free post with a gradual inward taper. Not validated -- a
// fit/registration experiment; see lib/control_cap.scad.
side_tabs_enable = true;
tab_width  = 22;   // tangential width, measured at the cavity-wall radius
tab_depth  = 2;    // radial projection inward from the cavity wall
tab_top_overhang = 28;  // how far the tabs continue past the top lip
tab_corner_fillet = 4;  // rounds the two bottom edges where the tab meets the floor
tab_tip_taper_gain = 6; // total inward (radial) lean of the inner face by the free tip
tab_taper_start = 10;   // taper begins this far below the lip
tab_rotate = -12;        // extra rotation of the tab pair about Z, off the button
                         // axis (- = clockwise, viewed from above)

/* [Tab wire hole] */
// A 5 mm channel drilled down each tab from its exposed free tip, angled
// so it breaks through into the hollow cavity for routing button wires.
tab_wire_hole_enable = true;
tab_wire_hole_diameter = 5;
tab_wire_hole_exit_from_lip = 15;  // how far below the lip the channel opens into the cavity

/* [Render] */
fn = 120; // [48:8:240]

use <../../lib/control_cap.scad>

color([0.74, 0.77, 0.79])
control_cap(roof_t        = top_disk_thickness,
            boss_d        = centre_boss_diameter,
            boss_depth    = centre_boss_depth,
            insert_len    = insert_total_h,
            insert_wall_t = cup_wall_thickness,
            chamfer_h     = entry_chamfer_h,
            chamfer_delta = entry_chamfer_delta,
            axle_bore_d   = shaft_hole_d,
            button_d      = button_upper_d,
            button_axis   = button_axis,
            button_radius = hole_spacing_cc,
            band_enable   = band_channels_enable,
            band_count    = band_count,
            band_z1       = band1_center_z_local,
            band_z2       = band2_center_z_local,
            band_w        = band_channel_w,
            band_depth    = band_channel_depth,
            oring_gland    = oring_gland_enable,
            oring_gland_od = oring_gland_od,
            oring_gland_w  = oring_gland_width,
            oring_gland_z  = oring_gland_from_face,
            side_tabs      = side_tabs_enable,
            tab_width_p    = tab_width,
            tab_depth_p    = tab_depth,
            tab_overhang_p = tab_top_overhang,
            tab_fillet_p   = tab_corner_fillet,
            tab_taper_gain_p = tab_tip_taper_gain,
            tab_taper_start_p = tab_taper_start,
            tab_rotate_p     = tab_rotate,
            tab_wire_hole    = tab_wire_hole_enable,
            tab_wire_hole_d  = tab_wire_hole_diameter,
            tab_wire_hole_exit_from_lip = tab_wire_hole_exit_from_lip,
            fn            = fn);
