/*
 Hope Turtle — control cap for the current full-turtle sine cage. Units: mm.
 License: CERN-OHL-S-2.0.
 Cap disk 100 mm; matching cage cavity 102 mm (1 mm radial clearance).
 Print bearing face down at Z=0, open insert + boss facing up.
 5 mm roof + 2 mm internal boss (TB-03).
 The axle bore carries an O-ring gland (rotary seal on the spinning axle
 round section) -- waterproofs the bore. O-ring is cast in Silicone_Ring_Mold.

 SOURCE FILE — geometry lives in lib/control_cap.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Cap body] */
top_disk_thickness  = 5;   // roof / disk thickness
centre_boss_depth   = 2;   // extra projection of the boss into the hollow cap
centre_boss_diameter = 18;
cup_wall_thickness  = 4;
insert_total_h      = 35;
entry_chamfer_h     = 1;
entry_chamfer_delta = 1;

/* [Axle and buttons] */
shaft_hole_d   = 8.6;
button_upper_d = 17;
button_axis    = "y"; // [x,y]
hole_spacing_cc = 24;  // radial position of the two button centres

/* [Axle O-ring gland] */
oring_gland_enable = true;
oring_gland_od = 11.5;      // groove bottom diameter in the bore
oring_gland_width = 2.6;    // groove axial width
oring_gland_from_face = 3.5; // groove centre, below the cap outer face

/* [Silicone band channels] */
band_channels_enable = true;
band_count = 2;             // [0:1:2]
band1_center_z_local = 12;  // groove centre, from the insert shoulder
band2_center_z_local = 25;
band_channel_w = 2;        // groove axial height
band_channel_depth = 2;    // groove radial depth

/* [Render] */
fn = 120; // [48:8:240]

use <../../lib/control_cap.scad>

color([0.74, 0.77, 0.79])
control_cap(roof_t        = top_disk_thickness,
            boss_d        = centre_boss_diameter,
            boss_depth    = centre_boss_depth,
            insert_len    = insert_total_h,
            insert_wall_t = cup_wall_thickness,
            chamfer_h     = entry_chamfer_h,
            chamfer_delta = entry_chamfer_delta,
            axle_bore_d   = shaft_hole_d,
            button_d      = button_upper_d,
            button_axis   = button_axis,
            button_radius = hole_spacing_cc,
            band_enable   = band_channels_enable,
            band_count    = band_count,
            band_z1       = band1_center_z_local,
            band_z2       = band2_center_z_local,
            band_w        = band_channel_w,
            band_depth    = band_channel_depth,
            oring_gland    = oring_gland_enable,
            oring_gland_od = oring_gland_od,
            oring_gland_w  = oring_gland_width,
            oring_gland_z  = oring_gland_from_face,
            fn            = fn);
