/*
 Hope Turtle — round/hex centre axle. Units: mm. License: CERN-OHL-S-2.0.
 Hex end on Z=0 for printing; the magnet recess opens upward.
 Round section = 30 mm inside the cavity (incl. boss) + 5 mm cap roof (TB-03)
 + 1 mm proud. Overall length 59 mm.

 SOURCE FILE — geometry lives in lib/hex_shaft.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Round shaft] */
round_shaft_diameter = 8;
round_length_inside_cap = 30; // roof underside -> round end, INCLUDING the boss
round_extension_above_cap = 1;

/* [Hex shaft] */
hex_across_flats = 10;
hex_length = 23;
joining_overlap = 0.2;

/* [Magnet recess] */
magnet_recess_enabled = true;
magnet_diameter = 3;
magnet_thickness = 1;

/* [Render] */
fn = 120; // [48:8:240]

use <../../lib/hex_shaft.scad>

color([0.74, 0.77, 0.79])
control_axle(round_d          = round_shaft_diameter,
             round_inside_cap = round_length_inside_cap,
             round_ext        = round_extension_above_cap,
             hex_af           = hex_across_flats,
             hex_len          = hex_length,
             join_overlap     = joining_overlap,
             magnet           = magnet_recess_enabled,
             magnet_d         = magnet_diameter,
             magnet_t         = magnet_thickness,
             fn               = fn);
