/*
 Hope Turtle — uniform round centre sail shaft. Units: mm. License: CERN-OHL-S-2.0.
 TB-08: one uniform round bar top to bottom, no hex section. Free-spins in
 the cap bore; passes with a light running clearance through the cage hub
 and the top sail bar's own hole; locks to the rotating cage with a single
 M3 set screw through the cage hub (see Bottle_Control_Cage.scad).
 Upper end on Z=0 for printing; the magnet recess opens upward.
 Round-in-cap section = 30 mm inside the cavity (incl. boss) + 5 mm cap roof
 (TB-03) + 1 mm proud. Overall length 59 mm.

 SOURCE FILE — geometry lives in lib/sail_shaft.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Shaft] */
shaft_diameter = 8;
round_length_inside_cap = 30; // roof underside -> lower end, INCLUDING the boss
round_extension_above_cap = 1;
upper_length = 23; // continues up through the cage hub + sail bar

/* [Magnet recess] */
magnet_recess_enabled = true;
magnet_diameter = 3;
magnet_thickness = 1;

/* [Render] */
fn = 120; // [48:8:240]

use <../../lib/sail_shaft.scad>

color([0.74, 0.77, 0.79])
sail_shaft(round_d          = shaft_diameter,
           round_inside_cap = round_length_inside_cap,
           round_ext        = round_extension_above_cap,
           upper_len        = upper_length,
           magnet           = magnet_recess_enabled,
           magnet_d         = magnet_diameter,
           magnet_t         = magnet_thickness,
           fn               = fn);
