/*
 Hope Turtle — scalloped, reinforced PLA cage. Units: mm.
 Matched to the control cap: 100 mm cap disk, 102 mm cavity, 1 mm radial
 clearance. One continuous sinusoidal wall -> four rounded crests roof-down;
 each batten groove + its two M3 holes centred on a crest. No separate tabs.

 FABRICATION: this part is 3D-PRINTED ROOF-FACE-DOWN — the flat top surface
 goes on the printer bed (part="print" flips it). Any change to the roof top
 must stay self-supporting in that pose: bevels flare OUTWARD from the bed
 (<= 45 deg), no undercut, no downward-facing pocket/lip/overhang. Flag any
 change that would need support material instead of making it silently.
 Horizontal M3 bores bridge in the slicer. The recessed clip pocket around
 the axle is OFF by default (top_pocket) while prototyping without a clip.
 TB-08: the central bore is a plain round hole for the uniform round sail
 shaft (see Bottle_Sail_Shaft.scad); a single radial M3 set screw through
 the hub wall locks the shaft to the cage. Prototype: not load-tested.
 Test fit, torsion, bending, layer adhesion, set-screw thread engagement.

 SOURCE FILE — geometry lives in lib/control_cage.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [View] */
part = "print"; // [print,upright]
curve_segments = 120; // [48:12:240]
wave_segments  = 240;  // [120:24:480]

/* [Cage body] */
cage_wall   = 6.5;
cage_roof   = 4;
skirt_height = 44;      // roof underside -> ORIGINAL skirt rim
notch_width = 22.5;
notch_depth = 3.7;
m3_hole_diameter = 3.2;
roof_ring_height = 10;  // minimum skirt depth between mounts
mount_extension  = 20;  // crest past the original rim
lower_hole_from_tip = 10;
roof_bevel = 3;         // 45-deg outward chamfer on the roof-top edge (0 = sharp); prints face-down

/* [Bearings and button] */
bump_d = 9;
button_diameter = 18;
button_r = 24;
button_angle = 90; // [0:0.5:359.5]

/* [Shaft hub, lock screw and clip pocket] */
shaft_hole_diameter = 8.2;  // TB-08: round bore, shaft dia + running clearance (was a hex bore)
cage_hub_d = 29;
setscrew_pilot_diameter = 2.5;  // self-tapping M3 grub-screw pilot, untested thread engagement
setscrew_angle = 0; // [0:0.5:359.5]
top_pocket = false;      // recessed clip pocket around the axle (off while prototyping)
clip_pocket_depth = 4;   // used only when top_pocket = true
pocket_d = 26;           //   "    "    "     "      "

use <../../lib/control_cage.scad>

module _cage()
    control_cage(outer_d = (100 + cage_wall * 2 + 2),  // cap 100 + 2 clearance + 2*wall
                 roof_t = cage_roof,
                 skirt = skirt_height,
                 extension = mount_extension,
                 valley_wall_h = roof_ring_height,
                 notch_w = notch_width,
                 notch_depth = notch_depth,
                 m3_d = m3_hole_diameter,
                 lower_hole_from_tip = lower_hole_from_tip,
                 bump_d = bump_d,
                 hub_d = cage_hub_d,
                 shaft_hole_d = shaft_hole_diameter,
                 setscrew_pilot_d = setscrew_pilot_diameter,
                 setscrew_angle = setscrew_angle,
                 pocket_d = pocket_d,
                 pocket_depth = clip_pocket_depth,
                 top_pocket = top_pocket,
                 button_d = button_diameter,
                 button_r = button_r,
                 button_angle = button_angle,
                 roof_bevel = roof_bevel,
                 wave_segments = wave_segments,
                 fn = curve_segments);

color([0.74, 0.77, 0.79]) {
    if (part == "print")
        translate([0, 0, cage_roof_top_z(bump_d, cage_roof)])
            rotate([180, 0, 0]) _cage();
    else if (part == "upright")
        translate([0, 0, -cage_wall_tip_z(bump_d, skirt_height, mount_extension)])
            _cage();
    else
        assert(false, str("Unknown view: ", part));
}
