/*
 Hope Turtle — silicone ring molds. Units: mm. License: CERN-OHL-S-2.0.

 Two kinds of mold:
  * FLAT INSERT-SEAL RINGS (part = mold / rings) — open-top scrape molds for
    the flat Ø75/Ø85 cap-insert seal rings. Print flat, cavity up, scrape
    flush, peel.
  * AXLE ROTARY-SEAL O-RING (part = oring_bottom / oring_top / oring_pair /
    oring) — a TWO-PART PRESSED mold for the round O-ring that waterproofs the
    control-cap axle bore. Print oring_bottom and oring_top flat (channel up).
    Three male pegs on the bottom half seat in three female holes in the top
    half so the halves stay aligned when pressed together; fill + vent run
    through the top half. O-ring ID is tied to the axle shaft diameter.

 Nominal dimensions; no shrinkage compensation. Seals NOT validated (CLAUDE.md s8).

 SOURCE FILE — geometry lives in lib/silicone_ring_mold.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Output] */
part = "mold"; // [mold,rings,oring_bottom,oring_top,oring_pair,oring,all]
ring_count = 2;
curve_segments = 240; // [120:24:480]

/* [Mold body] */
mold_floor_thickness = 3;
mold_outer_wall = 3;
mold_spacing = 8; // gap between mold bodies

use <../../lib/silicone_ring_mold.scad>

silicone_ring_molds(part = part, ring_count = ring_count,
                    floor_t = mold_floor_thickness,
                    outer_wall = mold_outer_wall,
                    spacing = mold_spacing,
                    fn = curve_segments);
