/*
 Hope Turtle — silicone ring mold. Units: mm. License: CERN-OHL-S-2.0.

 ONE two-part pressed mold that casts, in a single session:
  * ring_count FLAT insert-seal rings (Ø75/Ø85 × 1.5, for the cap insert
    grooves);
  * ring_count round AXLE O-RINGS, one nested in the centre of EVERY flat
    mold, so the default 2-ring mold gives two chances at a good O-ring.
    O-ring ID is tied to the sealing (round) section of the hex-shaft axle.

 The bottom plate has the flat-ring channels + a lower O-ring half-torus
 per ring + 3 male alignment pegs. The top plate has the upper O-ring
 half-tori + 3 female holes + one fill/vent per O-ring. Press together
 (pegs seat in holes), fill, cure, split, peel.

 part=mold lays BOTH plates flat and side by side (working faces up) so the
 one exported STL prints in a single job. mold_bottom / mold_top are the
 same plates alone. Nominal dims; no shrinkage. Seals NOT validated
 (CLAUDE.md s8).

 SOURCE FILE — geometry lives in lib/silicone_ring_mold.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Output] */
part = "mold"; // [mold,mold_bottom,mold_top,rings,oring]
ring_count = 2;
curve_segments = 240; // [120:24:480]

/* [Mold body] */
mold_floor_thickness = 3;
mold_spacing = 8; // gap between flat mold bodies

use <../../lib/silicone_ring_mold.scad>

silicone_ring_molds(part = part, ring_count = ring_count,
                    floor_t = mold_floor_thickness,
                    spacing = mold_spacing,
                    fn = curve_segments);
