/*
 Hope Turtle — silicone ring mold. Units: mm. License: CERN-OHL-S-2.0.

 ONE two-part pressed mold that casts, in a single session:
  * ring_count FLAT insert-seal rings (Ø75/Ø85 × 1.5, for the cap insert
    grooves);
  * ring_count round AXLE O-RINGS, one nested in the centre of EVERY flat
    mold, so the default 2-ring mold gives two chances at a good O-ring.
    O-ring ID is tied to the sealing (round) section of the hex-shaft axle.

 The bottom plate has the flat-ring channels + a lower O-ring half-torus
 per ring + 3 male alignment pegs. The top plate has the upper O-ring
 half-tori + 3 female holes + one fill/vent per O-ring. Press together
 (pegs seat in holes), fill, cure, split, peel.

 part=mold lays BOTH plates flat and side by side (working faces up) so the
 one exported STL prints in a single job. mold_bottom / mold_top are the
 same plates alone. Nominal dims; no shrinkage. Seals NOT validated
 (CLAUDE.md s8).

 SOURCE FILE — geometry lives in lib/silicone_ring_mold.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Output] */
part = "mold"; // [mold,mold_bottom,mold_top,rings,oring]
ring_count = 2;
curve_segments = 240; // [120:24:480]

/* [Mold body] */
mold_floor_thickness = 3;
mold_spacing = 8; // gap between flat mold bodies

/* [Flat seal ring -- the LARGE ring, for the cap insert grooves]
   Tweak these to re-size the flat ring's mold cavity for a one-off STL
   export without touching lib/params.scad (which also feeds the cap
   groove geometry). Defaults below are the as-cast values that match the
   current lib/params.scad groove spec at the 84 mm reference bottle:
   inner Ø57.75 / outer Ø77.75 x 2.6 thick, derived from a 77 mm groove
   root shrunk 25% for stretch-fit tension plus a 10 mm radial width.
   These are literals, not live p_*() calls (OpenSCAD's Customizer needs a
   literal default) -- they must be re-typed by hand after any upstream
   change to p_bottle_d()/p_seal_groove_root_d()/p_seal_ring_radial_w()/
   p_seal_ring_elasticity_reduction(); build/test.py's bounds check is what
   catches a forgotten update. The nested axle O-ring (small ring, ID/OD
   8/12) is not affected by these three values. */
flat_ring_inner_d  = 57.75; // mm, as-cast inner diameter
flat_ring_outer_d  = 77.75; // mm, as-cast outer diameter
flat_ring_axial_t  = 2.6;   // mm, cast thickness

use <../../lib/silicone_ring_mold.scad>

silicone_ring_molds(part = part, ring_count = ring_count,
                    floor_t = mold_floor_thickness,
                    spacing = mold_spacing,
                    fn = curve_segments,
                    ring_inner_d = flat_ring_inner_d,
                    ring_outer_d = flat_ring_outer_d,
                    ring_axial_t = flat_ring_axial_t);
