/*
 Hope Turtle — standalone ballast attachment. Units: mm.
 License: CERN-OHL-S-2.0.
 Two green core slats, one orange bottom board, two red lock feet, one
 yellow ballast fin. No bottle. Individual pieces lie flat on Z=0;
 the assembly raises its lowest component to Z=0.

 SOURCE FILE — geometry lives in lib/ballast_fin.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

part = "assembly"; // [assembly,core_slat,bottom_board,lock_foot,fin]
enable_color_coding = true;
ballast_fin_inspection_pullout = 0; // mm; 0 seats the fin

use <../../lib/ballast_fin.scad>

if (part == "assembly") {
    translate([0, 0, max(bl_lower_lobe(),
                         (bl_lock_h() - bl_lock_slot_h()) / 2,
                         bl_fin_lower_protrusion())])
        local_ballast_assembly(inspection_pullout = ballast_fin_inspection_pullout,
                               colored = enable_color_coding);
} else if (part == "core_slat") {
    ballast_core_slat_part(colored = enable_color_coding);
} else if (part == "bottom_board") {
    ballast_bottom_board_part(colored = enable_color_coding);
} else if (part == "lock_foot") {
    ballast_lock_part(colored = enable_color_coding);
} else if (part == "fin") {
    ballast_fin_part(colored = enable_color_coding);
} else {
    assert(false, str("Unknown part: ", part));
}
