/*
 Hope Turtle — standalone Ecojoiner assembly. Units: mm.
 License: CERN-OHL-S-2.0.
 Six Long Johns, six Little Johns, four Final Keys, twelve pressers with M6
 bolt placeholders. All six ports keep their pressers. No bottles/fins/sails.

 SOURCE FILE — geometry lives in lib/ecojoiner.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

enable_color_coding = true;

use <../../lib/ecojoiner.scad>

// Same physical orientation as the full Turtle assembly.
rotate([-90, 0, 0])
    eco_ecojoiner_only(colored = enable_color_coding);
