/*
 Hope Turtle rear-fin v2. Units: mm. License: CERN-OHL-S-2.0.
 Four wooden pieces: yellow fin, two green bottle-holder shafts, red solar
 crossbar. Panel + bottle are F5 reference only, excluded from F6/STL.
 Shaft length 334. Slot openings 12.2 mm (0.2 mm TOTAL, centred).
 TB-07: green-slat mounting hole is 103 mm from the shaft front, matching
 the assembled Turtle (was a fixed 50 mm).

 SOURCE FILE — geometry lives in lib/rear_fin.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Fit and tuning] */
half_lap_clearance   = 0.2; // TOTAL extra slot width, centred on the board
solar_slot_clearance = 0.2;
exploded = 0;

/* [Display] */
part = "assembly"; // [assembly,fin,solar_holder,shaft]
show_solar_panel = true;   // F5 reference only, excluded from F6/STL
show_bottle_mockup = false; // reserved

/* [Render] */
fn = 96;

use <../../lib/rear_fin.scad>
use <../../lib/params.scad>

module _panel_reference() {
    // width -> Y, height/length -> X, thickness -> Z; extends forward from the crossbar
    x0 = rf_solar_notch_x0() + p_wood_t() - p_solar_panel_h();
    color([0.05, 0.16, 0.4, 0.65])
        translate([x0, -p_solar_panel_w() / 2, rf_fin_height()])
            cube([p_solar_panel_h(), p_solar_panel_w(), p_solar_panel_t()]);
}

if (part == "assembly") {
    rear_fin_assembly(half_lap = half_lap_clearance,
                      solar_clear = solar_slot_clearance,
                      exploded = exploded, fn = fn);
    if (show_solar_panel && exploded == 0) %_panel_reference();
} else if (part == "fin") {
    rear_fin(half_lap = half_lap_clearance, solar_clear = solar_slot_clearance, fn = fn);
} else if (part == "solar_holder") {
    solar_panel_holder(solar_clear = solar_slot_clearance, fn = fn);
} else if (part == "shaft") {
    bottle_holder_shaft(half_lap = half_lap_clearance, fn = fn);
} else {
    assert(false, str("Unknown part: ", part));
}
