/*
 Hope Turtle — standalone sail apparatus. Units: mm. License: CERN-OHL-S-2.0.
 Wooden frame only: top crossbar, four battens, joint strengtheners, orange
 C ends, sails. No bottle/cap/cage/axle. Assembly is an inspection view.
 Both Ø3.2 cage-mount holes kept in every batten; no C-piece M6 bore; no
 non-sail-batten lower bore (TB-01). Bottom rails brown (TB-02).

 SOURCE FILE — geometry lives in lib/sail_frame.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

part = "assembly"; // [assembly,top_bar,sail_batten,non_sail_batten,bottom_bars,strengtheners,c_end_pieces,sails]
wood_thickness = 12;
side_batten_height = 205;
cage_mount_hole_diameter = 3.2;
show_hardware = true;
enable_color_coding = true;

use <../../lib/sail_frame.scad>

sail_frame(part = part,
           board_width = wood_thickness,
           side_batten_height = side_batten_height,
           cage_mount_hole_diameter = cage_mount_hole_diameter,
           show_hardware = show_hardware,
           colored = enable_color_coding);
