// ==========================================================================
//  GENERATED FILE -- DO NOT EDIT.
//  Produced by build/build.py from components/Bottle_Sail_Shaft.scad
//  Turtle Body version 4.0.0
//  Edit lib/ and src/ instead, then run: python3 build/build.py
// ==========================================================================
/*
 Hope Turtle — uniform round centre sail shaft. Units: mm. License: CERN-OHL-S-2.0.
 TB-08: one uniform round bar top to bottom, no hex section. Free-spins in
 the cap bore; passes with a light running clearance through the cage hub
 and the top sail bar's own hole; locks to the rotating cage with a single
 M3 set screw through the cage hub (see Bottle_Control_Cage.scad).
 Upper end on Z=0 for printing; the magnet recess opens upward.
 Round-in-cap section = 30 mm inside the cavity (incl. boss) + 5 mm cap roof
 (TB-03) + 1 mm proud. Overall length 59 mm.

 SOURCE FILE — geometry lives in lib/sail_shaft.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Shaft] */
shaft_diameter = 8;
round_length_inside_cap = 30; // roof underside -> lower end, INCLUDING the boss
round_extension_above_cap = 1;
upper_length = 23; // continues up through the cage hub + sail bar

/* [Magnet recess] */
magnet_recess_enabled = true;
magnet_diameter = 3;
magnet_thickness = 1;

/* [Render] */
fn = 120; // [48:8:240]

// [bundle] begin use <../../lib/sail_shaft.scad>
// ==========================================================================
//  Turtle Body -- sail shaft: uniform round centre axle  (lib module)
// --------------------------------------------------------------------------
//  TB-08: one uniform round bar top to bottom -- no hex section. The lower
//  (round_inside_cap) portion bears/free-spins in the cap's bore; the upper
//  portion continues on up through the cage hub and the top sail bar's own
//  hole with a light running clearance (p_axle_shaft_hole_d()) and is
//  locked to the ROTATING cage by a single radial M3 set screw through the
//  cage hub (see lib/control_cage.scad) instead of a shaped interference
//  fit. Magnet recess opens at the round/lower end for an AS5600 sensing
//  magnet. See CLAUDE.md s9.
//
//  TB-04: derived to the resolved 5 mm cap roof (TB-03). round_inside_cap
//  spans roof underside -> round end, 30 mm, INCLUDING the boss -- do not
//  add the boss again -- + the 5 mm roof + 1 mm proud, so the shaft's
//  lower end still sits 1 mm above the cap's outer face and the overall
//  shaft is 59 mm.
//
//  Definitions only. Geometry is emitted by sail_shaft().
// ==========================================================================

// [bundle] begin use <params.scad>
// ==========================================================================
//  Turtle Body -- shared dimension contract
// --------------------------------------------------------------------------
//  The single source of truth for every dimension that more than one
//  subsystem depends on. Values are exposed as zero-argument functions so
//  this file can be pulled in with `use <params.scad>` (which ignores
//  top-level variable assignments) without polluting any namespace.
//
//  lib/ modules take these as DEFAULT argument values:
//      module control_cap(roof_t = p_cap_roof_t(), ...) { ... }
//  so a src/ wrapper can still override one value from its customizer block
//  while every other subsystem keeps the shared number.
//
//  Rules:
//   * one function per concept, canonical name (see CLAUDE.md cross-file table)
//   * derived values are functions of other p_*() functions, never re-typed
//   * mm throughout; names say _d (diameter), _r (radius), _t (thickness),
//     _len / _h (axial), _af (hex across-flats)
//   * do NOT add a bare `x = ...;` here -- bundle.py / lint.py will reject it
// ==========================================================================

// ---- tolerances and render quality --------------------------------------
function p_eps()          = 0.02;   // Boolean overlap / cut-through fudge
function p_fit_clearance() = 0.2;   // wood joint: TOTAL extra slot width, centred on the board
function p_fn_plastic()   = 120;    // printed PLA parts (cap, cage, axle, mold)
function p_fn_wood()      = 96;     // cut wooden parts
function p_fn_curve()     = 180;    // fine profile curves (bottle, sails)

// ---- bottle (the foundation reference) ---------------------------------
function p_bottle_d()        = 84;    // outside diameter (was 86, and 82 before that; other bottle dims held)
function p_bottle_h()        = 305;   // total height incl. ordinary screw cap
function p_bottle_wall_t()   = 0.5;   // modelling assumption, not a measurement
function p_bottle_cap_d()    = 31;    // ordinary screw cap (NOT the control-cap disk)
function p_bottle_cap_h()    = 17;    // ordinary screw cap height (rear-fin / ballast formulas)
function p_collar_d()        = 34;    // bottle collar, independent of cap diameter
function p_top_dome_h()      = 62;
function p_bottom_dome_h()   = 25;
function p_dome_power()      = 2.5;   // superellipse exponent
function p_bottle_neck_h()   = 5;
function p_bottle_collar_h() = 1;
function p_bottle_neck_d()   = p_bottle_cap_d() - 3;   // 28: neck is 3 mm under the cap
function p_bottle_base_ratio() = 0.88; // slightly narrower footprint at the base
function p_bottle_profile_steps() = 16;
// cut bottle (control head): the lower dome is removed and a short socket is
// bored so the control-cap insert slides in. Cut plane sits 5 mm above the
// bottom dome height.
function p_bottle_cut_extra()  = 5;
function p_bottle_cut_height() = p_bottom_dome_h() + p_bottle_cut_extra();   // 30

// nominal bottle interior and the cap insert that enters it
function p_bottle_socket_d() = p_bottle_d() - 2 * p_bottle_wall_t();          // 81
function p_insert_shaft_radial_clearance() = 1;
function p_insert_shaft_d()  = p_bottle_socket_d()
                             - 2 * p_insert_shaft_radial_clearance();          // 79

// ---- wooden stock -----------------------------------------------------
function p_wood_t()          = 12;    // shared board / slat thickness
function p_fin_board_w()     = 93;    // shared fin-system stock width
function p_screw_side_offset() = 25;  // mounting-hole inset from a John end

// ---- Ecojoiner port --------------------------------------------------
// A port must swallow the bottle's tapered top (the top dome) plus a seating
// allowance, so its axial length is DERIVED from the bottle, not fixed. This
// is the same rule the HopeTurtles.org generators use
// (port_length = taper_height + port_allowance); until 2026-09-08 lib carried
// the evaluated constant 82 instead, which silently broke the rule for any
// bottle other than the reference one. Ballast and Ecojoiner both read it.
function p_port_allowance()  = 20;                 // seating allowance beyond the dome
function p_port_length()     = p_top_dome_h() + p_port_allowance();   // 62 + 20 = 82
function p_port_height()     = p_bottle_d();       // opening height == bottle diameter (asserted)

// ---- M6 hardware ---------------------------------------------------
function p_m6_clearance_d()  = 6.4;   // M6 clearance hole
function p_m6_bolt_shaft_d() = 6;     // visual placeholder only
function p_m6_bolt_head_d()  = 12;
function p_m6_bolt_head_t()  = 4;

// ---- control cap (large stationary disk; see CLAUDE.md s7) ----------
//  TB-03 resolution: repository 5 mm roof / 2 mm boss is authoritative;
//  the axle (below) is derived to this datum.
function p_cap_disk_d()      = 100;   // control-cap disk (independent of p_bottle_cap_d)
function p_cap_roof_t()      = 5;     // disk / roof thickness
function p_cap_boss_depth()  = 1.5;   // extra projection of the centre boss into the hollow cap
                                       // (was 2; lowered 0.5 mm -> 6.5 mm axle bearing length)
function p_cap_boss_d()      = 18;
function p_cap_insert_len()  = 35;    // straight insert shaft length
function p_cap_insert_wall_t() = 4;
function p_cap_entry_chamfer_h()     = 1;
function p_cap_entry_chamfer_delta() = 1;
function p_cap_axle_bore_d() = 8.7;   // 0.35 mm radial clearance to the Ø8 shaft (was 8.6 / 0.3 mm)
function p_cap_cage_radial_clearance() = 1;   // cap disk -> cage inner wall (radial)
function p_cap_total_h()     = p_cap_roof_t() + p_cap_insert_len();           // 40
function p_cap_bearing_len() = p_cap_roof_t() + p_cap_boss_depth();           // 6.5 (was 7)

// buttons (through both cap and cage)
function p_button_upper_d()  = 17;    // clearance hole in the cap
function p_button_axis()     = "y";   // "x" or "y"
function p_button_radius()   = 25;    // radial position of the two button centres (50 mm apart;
                                       // was 24 / 48 mm -- shared with the cage's matching bore)

// ---- silicone seal grooves + rings (CLAUDE.md s8) ------------------
function p_seal_groove_count()      = 2;
function p_seal_groove_axial_h()    = 2.7; // groove height (was 3.5; retuned to just clear
                                            // the 2.6 mm ring axial thickness below, 0.1 mm margin)
function p_seal_groove_radial_depth() = 2; // groove depth
function p_seal_groove1_from_shoulder() = 12;  // groove centre, measured from the insert SHOULDER
function p_seal_groove2_from_shoulder() = 25;
function p_seal_ring_axial_t()      = 2.6;  // cast ring thickness (was 3)
function p_seal_ring_radial_w()     = 10;   // cast ring radial width (was 5; doubled). NOT validated.
function p_seal_ring_elasticity_reduction() = 0.25;
    // Cast the ring's inner diameter this fraction SMALLER than the groove
    // root it mates to, so real (stretchy) silicone is under tension --
    // and therefore actually grips -- once stretched onto the cap, instead
    // of sitting at a 1:1 as-cast fit. Tweak this here as real silicone
    // behaviour is characterized; NOT validated (see lib/silicone_ring_mold.scad).
function p_seal_groove_root_d() = p_insert_shaft_d()
                                - 2 * p_seal_groove_radial_depth();            // 79 at the 86 mm bottle

// ---- sail shaft: uniform round centre axle (CLAUDE.md s9) ----------
//  Derived to the 5/2 cap datum (TB-03/TB-04). round_inside_cap is measured
//  from the roof underside and INCLUDES the boss -- do not add the boss again.
//  TB-08: the shaft is now one uniform round bar top to bottom -- no hex
//  section. It free-spins in the cap bore (p_cap_axle_bore_d) and passes
//  with a light running clearance through the cage hub bore and the top
//  sail bar's own hole (both p_axle_shaft_hole_d()); it locks to the
//  ROTATING cage with a single M3 set screw through the cage hub
//  (p_cage_setscrew_pilot_d()) rather than a shaped (hex) interference fit.
function p_axle_round_d()        = 8;
function p_axle_round_ext()      = 1;    // projection above the cap's outer face
function p_axle_round_inside_cap() = p_cap_insert_len() - 5;  // 30: roof underside to round end (incl. boss)
function p_axle_round_len()      = p_axle_round_inside_cap() + p_cap_roof_t() + p_axle_round_ext();  // 36
function p_axle_upper_len()      = 23;   // continues up through the cage hub + sail bar (was the hex length)
function p_axle_total_len()      = p_axle_upper_len() + p_axle_round_len();
function p_axle_shaft_clearance() = 0.2; // light running clearance, diametral: any hole the shaft passes
                                          // (but does not bear in) is p_axle_round_d() + this
function p_axle_shaft_hole_d()   = p_axle_round_d() + p_axle_shaft_clearance();  // 8.2
function p_magnet_d()            = 3;    // AS5600 sensing magnet recess
function p_magnet_t()            = 1;

// ---- axle rotary shaft O-ring (waterproofs the axle bore; cast in the mold) ----
//  A round-section O-ring seated in a gland in the control-cap bore, sealing
//  against the spinning round section of the axle. ID is tied to the shaft.
function p_axle_oring_cs()     = 2.0;                                   // cross-section
function p_axle_oring_id()     = p_axle_round_d();                      // 8 -- hugs the shaft
function p_axle_oring_od()     = p_axle_oring_id() + 2 * p_axle_oring_cs();          // 12
function p_axle_oring_mean_r() = (p_axle_oring_id() + p_axle_oring_cs()) / 2;        // 5
//  gland cut into the cap bore for it
function p_cap_oring_squeeze()      = 0.25;  // radial squeeze on the seal
function p_cap_oring_gland_od()     = p_axle_oring_od() - 2 * p_cap_oring_squeeze(); // 11.5
function p_cap_oring_gland_w()      = 1.3 * p_axle_oring_cs();                       // 2.6 axial
function p_cap_oring_gland_from_face() = 3.5; // gland centre, from the cap outer face, along the bore

// ---- rotating control cage (CLAUDE.md s6) ------------------------
function p_cage_wall_t()     = 6.5;   // radial wall thickness
function p_cage_roof_t()     = 4;     // roof / surface plate thickness
function p_cage_inner_d()    = p_cap_disk_d() + 2 * p_cap_cage_radial_clearance();   // 102
function p_cage_outer_d()    = p_cage_inner_d() + 2 * p_cage_wall_t();               // 115
function p_cage_skirt_depth()   = 44;   // roof underside to the ORIGINAL skirt rim
function p_cage_peak_extension() = 20;  // crest extends this far past the original rim
function p_cage_valley_wall_h()  = 10;  // minimum wall depth between mounts
function p_cage_total_h()    = p_cage_skirt_depth() + p_cage_roof_t();              // 48 (native)
function p_cage_notch_count()   = 4;
function p_cage_notch_w()    = 22.5;  // batten groove width
function p_cage_notch_depth() = 3.7;
function p_cage_wave_segments() = 240;
function p_cage_hub_d()      = 29;
function p_cage_pocket_d()   = 26;    // top clip pocket (control_cage top_pocket, OFF by default)
function p_cage_pocket_depth() = 4;   //   "        "     "
// TB-08: hex bore replaced by a plain round bore (p_axle_shaft_hole_d(),
// shared with the sail bar) + a radial M3 set screw that locks the cage to
// the shaft -- see p_cage_setscrew_*() below.
function p_cage_bearing_d()  = 9;     // hemispherical bearing bump
function p_cage_bearing_count() = 8;
function p_cage_bearing_pcd() = p_cap_disk_d() - p_cage_bearing_d() + 0.5;          // 91.5
function p_cage_top_hole_d() = 18;    // central button / access hole through the roof
function p_cage_mount_hole_d() = 3.2; // two M3 clearance holes per batten / groove
function p_cage_mount_pitch()  = 32;  // vertical pitch of the pair
function p_cage_lower_hole_from_tip() = 10;
// Single radial M3 set (grub) screw through the hub wall, pressing on the
// shaft to lock cage <-> shaft rotation (TB-08). Self-tapping into the
// printed PLA hub -- not a clearance hole for a separate nut, unlike the
// batten/mount M3 holes above. Pilot diameter is an untested starting
// point (typical M3-into-rigid-plastic self-tap pilots run 2.5-2.8 mm) --
// verify real thread engagement and tapping torque before relying on it.
function p_cage_setscrew_pilot_d() = 2.5;
function p_cage_setscrew_angle()   = 0;    // radial angle of the lock screw around the hub
// 45-deg outward chamfer on the roof-top outer edge (0 = sharp). The cage
// prints roof-face-down, so this bevel flares OUT from the bed and stays
// printable; it runs the full perimeter, batten grooves included. See
// lib/control_cage.scad.
function p_cage_roof_bevel() = 3;

// ---- sail apparatus (CLAUDE.md s10) ---------------------------
function p_side_batten_h()   = 205;
function p_side_batten_w()   = 20;
function p_side_batten_radial_t() = 10;
function p_top_crossbar_len() = 6 * p_bottle_d();   // 492
function p_top_crossbar_w()  = 22;
function p_top_crossbar_t()  = p_wood_t();          // 12
function p_sail_bar_axle_hole_d() = p_axle_shaft_hole_d();  // TB-08: Ø8.2, same running
                                                              // clearance as the cage hub bore (was Ø12 for the hex corners)
function p_bottom_rail_len() = 3 * p_bottle_d();    // 246
function p_bottom_rail_bottle_clearance() = 1;
function p_sail_rail_color()  = [0.56, 0.39, 0.39]; // brown (top AND bottom rails)
function p_c_piece_color()    = [1.0, 0.52, 0.20];  // orange, retained

// ---- rear fin + solar support (CLAUDE.md s11) ----------------
function p_solar_panel_w() = 148;
function p_solar_panel_h() = 223;
function p_solar_panel_t() = 2.5;    // real panel, independent of wood thickness
function p_rear_shaft_len() = p_bottle_h()
                            + (2/3) * (p_fin_board_w() - 2 * p_wood_t())
                            - p_bottle_cap_h();                                 // 334
function p_rear_half_lap_engagement() = 42;   // green/yellow interlock depth
function p_rear_fin_tab_width() = 15;
function p_rear_shaft_width()   = 59;
// TB-07: the green-slat mounting hole follows the mating Ecojoiner John, not a
// fixed 50 mm. Derived from the install transform; the john_length/2 terms
// cancel, leaving a pure function of the shared contract (= 103 at defaults).
function p_rear_shaft_hole_from_front() =
    p_rear_shaft_len() - p_screw_side_offset() - p_bottle_h()
    + p_bottle_cap_h() + p_port_height();

// ---- ballast attachment (CLAUDE.md s12) ---------------------
function p_ballast_core_w()   = p_bottle_d() - 2 * p_wood_t();                  // 58
function p_ballast_core_len() = p_bottle_h() - p_bottle_cap_h() + 6 * p_wood_t();  // 360
function p_ballast_slat_gap() = p_bottle_d();          // clear inner-face gap
function p_ballast_slat_spacing() = p_bottle_d() + p_wood_t();                  // 94
function p_ballast_board_len() = 3.5 * p_bottle_d();   // 287
function p_ballast_fin_len()   = 3 * p_bottle_d();     // 246
function p_ballast_lock_w()    = 5 * p_wood_t();       // 60

// ---- neutral wood shades (used when enable_color_coding = false) -------
// With the full colour code off, every wooden subsystem still renders in its
// OWN shade of brown so the parts stay visually separable. All are warm browns
// (R > G > B) spaced by lightness. The two large fins share one darker shade so
// they read as a matched pair, distinct from the rest of their own assembly.
function p_wood_shade_sail()     = [0.85, 0.66, 0.47]; // sail frame  (lightest)
function p_wood_shade_rear_fin() = [0.72, 0.50, 0.33]; // rear-fin shafts + solar holder
function p_wood_shade_eco()      = [0.62, 0.44, 0.28]; // Ecojoiner core
function p_wood_shade_ballast()  = [0.52, 0.34, 0.22]; // ballast slats / board / locks
function p_wood_shade_fin()      = [0.40, 0.26, 0.17]; // rear fin + ballast fin, shared (darkest)
// [bundle] end   <params.scad>

module sail_shaft(round_d          = p_axle_round_d(),
                  round_inside_cap = p_axle_round_inside_cap(),  // 30, roof underside -> round end
                  round_ext        = p_axle_round_ext(),         // 1, proud of the cap face
                  cap_roof_t       = p_cap_roof_t(),              // 5 (TB-03)
                  upper_len        = p_axle_upper_len(),          // 23, continues up through cage + sail bar
                  magnet           = true,
                  magnet_d         = p_magnet_d(),
                  magnet_t         = p_magnet_t(),
                  fn               = undef) {
    nn        = fn == undef ? p_fn_plastic() : fn;
    round_len = round_inside_cap + cap_roof_t + round_ext;
    total_len = upper_len + round_len;

    // ---- interface asserts (inputs from the shared contract) ----
    assert(round_d > 0 && round_d < p_cap_axle_bore_d(),
           "sail_shaft: shaft must clear the cap bore.");
    assert(round_d < p_axle_shaft_hole_d(),
           "sail_shaft: shaft must clear the cage hub / sail bar running hole.");
    assert(round_inside_cap > 0 && cap_roof_t > 0 && round_ext >= 0 && upper_len > 0);
    assert(round_inside_cap > p_cap_boss_depth(),
           "sail_shaft: shaft must pass the boss.");
    assert(round_inside_cap < p_cap_insert_len(),
           "sail_shaft: keep the lower end inside the cap's open insert rim.");
    assert(upper_len + round_ext >
           p_cage_bearing_d() / 2 + p_cage_roof_t() + p_top_crossbar_t(),
           "sail_shaft: shaft must reach through the cage roof and sail bar.");
    assert(!magnet || (magnet_d > 0 && magnet_d < round_d
           && magnet_t > 0 && magnet_t < round_inside_cap));

    $fn = nn;
    difference() {
        cylinder(d = round_d, h = total_len);
        if (magnet)
            translate([0, 0, total_len - magnet_t])
                cylinder(d = magnet_d, h = magnet_t + p_eps());
    }

    echo("SAIL SHAFT: total / round-in-cap / upper length = ", total_len, round_len, upper_len);
    echo("SAIL SHAFT: diameter (uniform, no hex) = ", round_d);
}

// Print pose: either end can sit flat on the bed (a bare cylinder); modelled
// with the upper (cage-lock) end at Z=0 and the magnet opening up, matching
// the as-modelled orientation used before TB-08 -- no reseat module needed.
// [bundle] end   <../../lib/sail_shaft.scad>

color([0.74, 0.77, 0.79])
sail_shaft(round_d          = shaft_diameter,
           round_inside_cap = round_length_inside_cap,
           round_ext        = round_extension_above_cap,
           upper_len        = upper_length,
           magnet           = magnet_recess_enabled,
           magnet_d         = magnet_diameter,
           magnet_t         = magnet_thickness,
           fn               = fn);
