// ==========================================================================
//  GENERATED FILE -- DO NOT EDIT.
//  Produced by build/build.py from components/Bottle_Control_Cap.scad
//  Turtle Body version 4.0.0
//  Edit lib/ and src/ instead, then run: python3 build/build.py
// ==========================================================================
/*
 Hope Turtle — control cap for the current full-turtle sine cage. Units: mm.
 License: CERN-OHL-S-2.0.
 Cap disk 100 mm; matching cage cavity 102 mm (1 mm radial clearance).
 Print bearing face down at Z=0, open insert + boss facing up.
 5 mm roof + 2 mm internal boss (TB-03).
 The axle bore carries an O-ring gland (rotary seal on the spinning axle
 round section) -- waterproofs the bore. O-ring is cast in Silicone_Ring_Mold.
 Side tabs (two internal cavity ribs + lip extension, on by default) are a
 fit/registration experiment -- not validated. See lib/control_cap.scad.
 Each tab carries a 5 mm wire-routing channel down to the cavity, for
 button wiring.

 SOURCE FILE — geometry lives in lib/control_cap.scad + lib/params.scad.
 The committed self-contained file is generated by build/build.py.
*/

/* [Cap body] */
top_disk_thickness  = 5;   // roof / disk thickness
centre_boss_depth   = 1.5; // extra projection of the boss into the hollow cap (was 2; lowered 0.5 mm)
centre_boss_diameter = 18;
cup_wall_thickness  = 4;
insert_total_h      = 35;
entry_chamfer_h     = 1;
entry_chamfer_delta = 1;

/* [Axle and buttons] */
shaft_hole_d   = 8.7;  // 0.35 mm radial clearance to the Ø8 axle (was 8.6 / 0.3 mm)
button_upper_d = 17;
button_axis    = "y"; // [x,y]
hole_spacing_cc = 25;  // radial position of the two button centres (was 24; moved 1 mm out,
                        // shared with the cage's matching bore via p_button_radius())

/* [Axle O-ring gland] */
oring_gland_enable = true;
oring_gland_od = 11.5;      // groove bottom diameter in the bore
oring_gland_width = 2.6;    // groove axial width
oring_gland_from_face = 3.5; // groove centre, below the cap outer face

/* [Silicone band channels] */
band_channels_enable = true;
band_count = 2;             // [0:1:2]
band1_center_z_local = 12;  // groove centre, from the insert shoulder
band2_center_z_local = 25;
band_channel_w = 2.7;      // groove axial height (matches the retuned mold ring)
band_channel_depth = 2;    // groove radial depth

/* [Side tabs] */
// Two internal ribs on the hollow insert cavity's inner wall, on the button
// axis, running the full cavity height then continuing past the top lip as
// a free post with a gradual inward taper. Not validated -- a
// fit/registration experiment; see lib/control_cap.scad.
side_tabs_enable = true;
tab_width  = 22;   // tangential width, measured at the cavity-wall radius
tab_depth  = 2;    // radial projection inward from the cavity wall
tab_top_overhang = 28;  // how far the tabs continue past the top lip
tab_corner_fillet = 4;  // rounds the two bottom edges where the tab meets the floor
tab_tip_taper_gain = 6; // total inward (radial) lean of the inner face by the free tip
tab_taper_start = 10;   // taper begins this far below the lip
tab_rotate = -12;        // extra rotation of the tab pair about Z, off the button
                         // axis (- = clockwise, viewed from above)

/* [Tab wire hole] */
// A 5 mm channel drilled down each tab from its exposed free tip, angled
// so it breaks through into the hollow cavity for routing button wires.
tab_wire_hole_enable = true;
tab_wire_hole_diameter = 5;
tab_wire_hole_exit_from_lip = 15;  // how far below the lip the channel opens into the cavity

/* [Render] */
fn = 120; // [48:8:240]

// [bundle] begin use <../../lib/control_cap.scad>
// ==========================================================================
//  Turtle Body -- control cap  (lib module)
// --------------------------------------------------------------------------
//  The large stationary disk. Its insert enters the cut bottle body; the
//  rotating cage sits above its flat outer face. NOT the bottle's Ø31 screw
//  cap. See CLAUDE.md s7 / s8.
//
//  TB-03: 5 mm roof + 2 mm internal boss (7 mm axle bearing length).
//  The boss is joined to the roof with a Boolean overlap and survives the
//  cavity subtraction; the central bore passes through both.
//
//  The bore carries an O-RING GLAND (`oring_gland`, on by default): an
//  annular groove in the bore wall that seats a round-section rotary-seal
//  O-ring against the spinning axle round section, waterproofing the bore.
//  The O-ring is cast in lib/silicone_ring_mold.scad; its ID is tied to the
//  axle shaft (p_axle_oring_id() = p_axle_round_d()).
//
//  Optional SIDE TABS (`side_tabs`, off by default in this module but ON in
//  the wrapper): two internal ribs on the hollow insert cavity's inner wall,
//  rooted at the cavity floor, that continue past the top lip as a free
//  full-wall-thickness post with a gradual inward taper. See cap_side_tabs()
//  below. Not validated -- a fit/registration experiment.
//
//  Optional TAB WIRE HOLE (`tab_wire_hole`, off by default, ON in the
//  wrapper alongside side_tabs): a round channel drilled down each side
//  tab from its exposed free tip to a point inside the cap body, breaking
//  through the tab's inner face into the hollow cavity -- for routing
//  button wires from outside, down through the tab, into the cap interior.
//
//  Definitions only. Geometry is emitted by control_cap().
// ==========================================================================

// [bundle] begin use <params.scad>
// ==========================================================================
//  Turtle Body -- shared dimension contract
// --------------------------------------------------------------------------
//  The single source of truth for every dimension that more than one
//  subsystem depends on. Values are exposed as zero-argument functions so
//  this file can be pulled in with `use <params.scad>` (which ignores
//  top-level variable assignments) without polluting any namespace.
//
//  lib/ modules take these as DEFAULT argument values:
//      module control_cap(roof_t = p_cap_roof_t(), ...) { ... }
//  so a src/ wrapper can still override one value from its customizer block
//  while every other subsystem keeps the shared number.
//
//  Rules:
//   * one function per concept, canonical name (see CLAUDE.md cross-file table)
//   * derived values are functions of other p_*() functions, never re-typed
//   * mm throughout; names say _d (diameter), _r (radius), _t (thickness),
//     _len / _h (axial), _af (hex across-flats)
//   * do NOT add a bare `x = ...;` here -- bundle.py / lint.py will reject it
// ==========================================================================

// ---- tolerances and render quality --------------------------------------
function p_eps()          = 0.02;   // Boolean overlap / cut-through fudge
function p_fit_clearance() = 0.2;   // wood joint: TOTAL extra slot width, centred on the board
function p_fn_plastic()   = 120;    // printed PLA parts (cap, cage, axle, mold)
function p_fn_wood()      = 96;     // cut wooden parts
function p_fn_curve()     = 180;    // fine profile curves (bottle, sails)

// ---- bottle (the foundation reference) ---------------------------------
function p_bottle_d()        = 84;    // outside diameter (was 86, and 82 before that; other bottle dims held)
function p_bottle_h()        = 305;   // total height incl. ordinary screw cap
function p_bottle_wall_t()   = 0.5;   // modelling assumption, not a measurement
function p_bottle_cap_d()    = 31;    // ordinary screw cap (NOT the control-cap disk)
function p_bottle_cap_h()    = 17;    // ordinary screw cap height (rear-fin / ballast formulas)
function p_collar_d()        = 34;    // bottle collar, independent of cap diameter
function p_top_dome_h()      = 62;
function p_bottom_dome_h()   = 25;
function p_dome_power()      = 2.5;   // superellipse exponent
function p_bottle_neck_h()   = 5;
function p_bottle_collar_h() = 1;
function p_bottle_neck_d()   = p_bottle_cap_d() - 3;   // 28: neck is 3 mm under the cap
function p_bottle_base_ratio() = 0.88; // slightly narrower footprint at the base
function p_bottle_profile_steps() = 16;
// cut bottle (control head): the lower dome is removed and a short socket is
// bored so the control-cap insert slides in. Cut plane sits 5 mm above the
// bottom dome height.
function p_bottle_cut_extra()  = 5;
function p_bottle_cut_height() = p_bottom_dome_h() + p_bottle_cut_extra();   // 30

// nominal bottle interior and the cap insert that enters it
function p_bottle_socket_d() = p_bottle_d() - 2 * p_bottle_wall_t();          // 81
function p_insert_shaft_radial_clearance() = 1;
function p_insert_shaft_d()  = p_bottle_socket_d()
                             - 2 * p_insert_shaft_radial_clearance();          // 79

// ---- wooden stock -----------------------------------------------------
function p_wood_t()          = 12;    // shared board / slat thickness
function p_fin_board_w()     = 93;    // shared fin-system stock width
function p_screw_side_offset() = 25;  // mounting-hole inset from a John end

// ---- Ecojoiner port --------------------------------------------------
// A port must swallow the bottle's tapered top (the top dome) plus a seating
// allowance, so its axial length is DERIVED from the bottle, not fixed. This
// is the same rule the HopeTurtles.org generators use
// (port_length = taper_height + port_allowance); until 2026-09-08 lib carried
// the evaluated constant 82 instead, which silently broke the rule for any
// bottle other than the reference one. Ballast and Ecojoiner both read it.
function p_port_allowance()  = 20;                 // seating allowance beyond the dome
function p_port_length()     = p_top_dome_h() + p_port_allowance();   // 62 + 20 = 82
function p_port_height()     = p_bottle_d();       // opening height == bottle diameter (asserted)

// ---- M6 hardware ---------------------------------------------------
function p_m6_clearance_d()  = 6.4;   // M6 clearance hole
function p_m6_bolt_shaft_d() = 6;     // visual placeholder only
function p_m6_bolt_head_d()  = 12;
function p_m6_bolt_head_t()  = 4;

// ---- control cap (large stationary disk; see CLAUDE.md s7) ----------
//  TB-03 resolution: repository 5 mm roof / 2 mm boss is authoritative;
//  the axle (below) is derived to this datum.
function p_cap_disk_d()      = 100;   // control-cap disk (independent of p_bottle_cap_d)
function p_cap_roof_t()      = 5;     // disk / roof thickness
function p_cap_boss_depth()  = 1.5;   // extra projection of the centre boss into the hollow cap
                                       // (was 2; lowered 0.5 mm -> 6.5 mm axle bearing length)
function p_cap_boss_d()      = 18;
function p_cap_insert_len()  = 35;    // straight insert shaft length
function p_cap_insert_wall_t() = 4;
function p_cap_entry_chamfer_h()     = 1;
function p_cap_entry_chamfer_delta() = 1;
function p_cap_axle_bore_d() = 8.7;   // 0.35 mm radial clearance to the Ø8 shaft (was 8.6 / 0.3 mm)
function p_cap_cage_radial_clearance() = 1;   // cap disk -> cage inner wall (radial)
function p_cap_total_h()     = p_cap_roof_t() + p_cap_insert_len();           // 40
function p_cap_bearing_len() = p_cap_roof_t() + p_cap_boss_depth();           // 6.5 (was 7)

// buttons (through both cap and cage)
function p_button_upper_d()  = 17;    // clearance hole in the cap
function p_button_axis()     = "y";   // "x" or "y"
function p_button_radius()   = 25;    // radial position of the two button centres (50 mm apart;
                                       // was 24 / 48 mm -- shared with the cage's matching bore)

// ---- silicone seal grooves + rings (CLAUDE.md s8) ------------------
function p_seal_groove_count()      = 2;
function p_seal_groove_axial_h()    = 2.7; // groove height (was 3.5; retuned to just clear
                                            // the 2.6 mm ring axial thickness below, 0.1 mm margin)
function p_seal_groove_radial_depth() = 2; // groove depth
function p_seal_groove1_from_shoulder() = 12;  // groove centre, measured from the insert SHOULDER
function p_seal_groove2_from_shoulder() = 25;
function p_seal_ring_axial_t()      = 2.6;  // cast ring thickness (was 3)
function p_seal_ring_radial_w()     = 10;   // cast ring radial width (was 5; doubled). NOT validated.
function p_seal_ring_elasticity_reduction() = 0.25;
    // Cast the ring's inner diameter this fraction SMALLER than the groove
    // root it mates to, so real (stretchy) silicone is under tension --
    // and therefore actually grips -- once stretched onto the cap, instead
    // of sitting at a 1:1 as-cast fit. Tweak this here as real silicone
    // behaviour is characterized; NOT validated (see lib/silicone_ring_mold.scad).
function p_seal_groove_root_d() = p_insert_shaft_d()
                                - 2 * p_seal_groove_radial_depth();            // 79 at the 86 mm bottle

// ---- sail shaft: uniform round centre axle (CLAUDE.md s9) ----------
//  Derived to the 5/2 cap datum (TB-03/TB-04). round_inside_cap is measured
//  from the roof underside and INCLUDES the boss -- do not add the boss again.
//  TB-08: the shaft is now one uniform round bar top to bottom -- no hex
//  section. It free-spins in the cap bore (p_cap_axle_bore_d) and passes
//  with a light running clearance through the cage hub bore and the top
//  sail bar's own hole (both p_axle_shaft_hole_d()); it locks to the
//  ROTATING cage with a single M3 set screw through the cage hub
//  (p_cage_setscrew_pilot_d()) rather than a shaped (hex) interference fit.
function p_axle_round_d()        = 8;
function p_axle_round_ext()      = 1;    // projection above the cap's outer face
function p_axle_round_inside_cap() = p_cap_insert_len() - 5;  // 30: roof underside to round end (incl. boss)
function p_axle_round_len()      = p_axle_round_inside_cap() + p_cap_roof_t() + p_axle_round_ext();  // 36
function p_axle_upper_len()      = 23;   // continues up through the cage hub + sail bar (was the hex length)
function p_axle_total_len()      = p_axle_upper_len() + p_axle_round_len();
function p_axle_shaft_clearance() = 0.2; // light running clearance, diametral: any hole the shaft passes
                                          // (but does not bear in) is p_axle_round_d() + this
function p_axle_shaft_hole_d()   = p_axle_round_d() + p_axle_shaft_clearance();  // 8.2
function p_magnet_d()            = 3;    // AS5600 sensing magnet recess
function p_magnet_t()            = 1;

// ---- axle rotary shaft O-ring (waterproofs the axle bore; cast in the mold) ----
//  A round-section O-ring seated in a gland in the control-cap bore, sealing
//  against the spinning round section of the axle. ID is tied to the shaft.
function p_axle_oring_cs()     = 2.0;                                   // cross-section
function p_axle_oring_id()     = p_axle_round_d();                      // 8 -- hugs the shaft
function p_axle_oring_od()     = p_axle_oring_id() + 2 * p_axle_oring_cs();          // 12
function p_axle_oring_mean_r() = (p_axle_oring_id() + p_axle_oring_cs()) / 2;        // 5
//  gland cut into the cap bore for it
function p_cap_oring_squeeze()      = 0.25;  // radial squeeze on the seal
function p_cap_oring_gland_od()     = p_axle_oring_od() - 2 * p_cap_oring_squeeze(); // 11.5
function p_cap_oring_gland_w()      = 1.3 * p_axle_oring_cs();                       // 2.6 axial
function p_cap_oring_gland_from_face() = 3.5; // gland centre, from the cap outer face, along the bore

// ---- rotating control cage (CLAUDE.md s6) ------------------------
function p_cage_wall_t()     = 6.5;   // radial wall thickness
function p_cage_roof_t()     = 4;     // roof / surface plate thickness
function p_cage_inner_d()    = p_cap_disk_d() + 2 * p_cap_cage_radial_clearance();   // 102
function p_cage_outer_d()    = p_cage_inner_d() + 2 * p_cage_wall_t();               // 115
function p_cage_skirt_depth()   = 44;   // roof underside to the ORIGINAL skirt rim
function p_cage_peak_extension() = 20;  // crest extends this far past the original rim
function p_cage_valley_wall_h()  = 10;  // minimum wall depth between mounts
function p_cage_total_h()    = p_cage_skirt_depth() + p_cage_roof_t();              // 48 (native)
function p_cage_notch_count()   = 4;
function p_cage_notch_w()    = 22.5;  // batten groove width
function p_cage_notch_depth() = 3.7;
function p_cage_wave_segments() = 240;
function p_cage_hub_d()      = 29;
function p_cage_pocket_d()   = 26;    // top clip pocket (control_cage top_pocket, OFF by default)
function p_cage_pocket_depth() = 4;   //   "        "     "
// TB-08: hex bore replaced by a plain round bore (p_axle_shaft_hole_d(),
// shared with the sail bar) + a radial M3 set screw that locks the cage to
// the shaft -- see p_cage_setscrew_*() below.
function p_cage_bearing_d()  = 9;     // hemispherical bearing bump
function p_cage_bearing_count() = 8;
function p_cage_bearing_pcd() = p_cap_disk_d() - p_cage_bearing_d() + 0.5;          // 91.5
function p_cage_top_hole_d() = 18;    // central button / access hole through the roof
function p_cage_mount_hole_d() = 3.2; // two M3 clearance holes per batten / groove
function p_cage_mount_pitch()  = 32;  // vertical pitch of the pair
function p_cage_lower_hole_from_tip() = 10;
// Single radial M3 set (grub) screw through the hub wall, pressing on the
// shaft to lock cage <-> shaft rotation (TB-08). Self-tapping into the
// printed PLA hub -- not a clearance hole for a separate nut, unlike the
// batten/mount M3 holes above. Pilot diameter is an untested starting
// point (typical M3-into-rigid-plastic self-tap pilots run 2.5-2.8 mm) --
// verify real thread engagement and tapping torque before relying on it.
function p_cage_setscrew_pilot_d() = 2.5;
function p_cage_setscrew_angle()   = 0;    // radial angle of the lock screw around the hub
// 45-deg outward chamfer on the roof-top outer edge (0 = sharp). The cage
// prints roof-face-down, so this bevel flares OUT from the bed and stays
// printable; it runs the full perimeter, batten grooves included. See
// lib/control_cage.scad.
function p_cage_roof_bevel() = 3;

// ---- sail apparatus (CLAUDE.md s10) ---------------------------
function p_side_batten_h()   = 205;
function p_side_batten_w()   = 20;
function p_side_batten_radial_t() = 10;
function p_top_crossbar_len() = 6 * p_bottle_d();   // 492
function p_top_crossbar_w()  = 22;
function p_top_crossbar_t()  = p_wood_t();          // 12
function p_sail_bar_axle_hole_d() = p_axle_shaft_hole_d();  // TB-08: Ø8.2, same running
                                                              // clearance as the cage hub bore (was Ø12 for the hex corners)
function p_bottom_rail_len() = 3 * p_bottle_d();    // 246
function p_bottom_rail_bottle_clearance() = 1;
function p_sail_rail_color()  = [0.56, 0.39, 0.39]; // brown (top AND bottom rails)
function p_c_piece_color()    = [1.0, 0.52, 0.20];  // orange, retained

// ---- rear fin + solar support (CLAUDE.md s11) ----------------
function p_solar_panel_w() = 148;
function p_solar_panel_h() = 223;
function p_solar_panel_t() = 2.5;    // real panel, independent of wood thickness
function p_rear_shaft_len() = p_bottle_h()
                            + (2/3) * (p_fin_board_w() - 2 * p_wood_t())
                            - p_bottle_cap_h();                                 // 334
function p_rear_half_lap_engagement() = 42;   // green/yellow interlock depth
function p_rear_fin_tab_width() = 15;
function p_rear_shaft_width()   = 59;
// TB-07: the green-slat mounting hole follows the mating Ecojoiner John, not a
// fixed 50 mm. Derived from the install transform; the john_length/2 terms
// cancel, leaving a pure function of the shared contract (= 103 at defaults).
function p_rear_shaft_hole_from_front() =
    p_rear_shaft_len() - p_screw_side_offset() - p_bottle_h()
    + p_bottle_cap_h() + p_port_height();

// ---- ballast attachment (CLAUDE.md s12) ---------------------
function p_ballast_core_w()   = p_bottle_d() - 2 * p_wood_t();                  // 58
function p_ballast_core_len() = p_bottle_h() - p_bottle_cap_h() + 6 * p_wood_t();  // 360
function p_ballast_slat_gap() = p_bottle_d();          // clear inner-face gap
function p_ballast_slat_spacing() = p_bottle_d() + p_wood_t();                  // 94
function p_ballast_board_len() = 3.5 * p_bottle_d();   // 287
function p_ballast_fin_len()   = 3 * p_bottle_d();     // 246
function p_ballast_lock_w()    = 5 * p_wood_t();       // 60

// ---- neutral wood shades (used when enable_color_coding = false) -------
// With the full colour code off, every wooden subsystem still renders in its
// OWN shade of brown so the parts stay visually separable. All are warm browns
// (R > G > B) spaced by lightness. The two large fins share one darker shade so
// they read as a matched pair, distinct from the rest of their own assembly.
function p_wood_shade_sail()     = [0.85, 0.66, 0.47]; // sail frame  (lightest)
function p_wood_shade_rear_fin() = [0.72, 0.50, 0.33]; // rear-fin shafts + solar holder
function p_wood_shade_eco()      = [0.62, 0.44, 0.28]; // Ecojoiner core
function p_wood_shade_ballast()  = [0.52, 0.34, 0.22]; // ballast slats / board / locks
function p_wood_shade_fin()      = [0.40, 0.26, 0.17]; // rear fin + ballast fin, shared (darkest)
// [bundle] end   <params.scad>
// [bundle] begin use <util.scad>
// ==========================================================================
//  Turtle Body -- shared helper modules and functions
// --------------------------------------------------------------------------
//  Small pieces that were copy-pasted across the standalone files. Geometry
//  lives in the per-subsystem lib/ modules; this file is only glue.
//
//  Definitions only -- no top-level geometry, no top-level assignments.
// ==========================================================================

// [bundle] begin use <params.scad>
// [bundle] already inlined: params.scad
// [bundle] end   <params.scad>

// Colour wrapper for wooden parts. When colour coding is off, every wooden
// component renders in one neutral wood tone; bottles, hardware, sails and
// printed parts keep their own colours and never call this.
module wood_color(coded_color, enabled = true, neutral = [0.94, 0.83, 0.62]) {
    color(enabled ? coded_color : neutral) children();
}

// scalar clamp
function clamp(v, lo, hi) = v < lo ? lo : (v > hi ? hi : v);

// Visual-only M6 bolt: plain shaft + hex-less cylindrical head. No thread,
// no torque rating -- a placeholder for fit inspection.
//  Local Z=0 is the underside of the head; the shaft runs toward +Z from Z=0
//  (plus an optional tip_extension), the head sits at Z=-head_t..0. Matches
//  the standalone files.
module m6_bolt_placeholder(grip_length, tip_extension = 1,
                           shaft_d = undef, head_d = undef, head_t = undef,
                           color_rgb = [0.15, 0.15, 0.15], fn = 48) {
    sd = shaft_d == undef ? p_m6_bolt_shaft_d() : shaft_d;
    hd = head_d  == undef ? p_m6_bolt_head_d()  : head_d;
    ht = head_t  == undef ? p_m6_bolt_head_t()  : head_t;
    assert(grip_length > 0, "m6_bolt_placeholder: grip_length must be positive.");
    color(color_rgb)
        union() {
            cylinder(d = sd, h = grip_length + tip_extension, $fn = fn);
            translate([0, 0, -ht])
                cylinder(d = hd, h = ht, $fn = fn);
        }
}

// Regular hexagonal prism specified by across-flats width (OpenSCAD's
// cylinder($fn=6) is specified across corners, which is the usual trap).
module hex_prism_af(across_flats, h, center = false) {
    cylinder(d = across_flats / cos(30), h = h, $fn = 6, center = center);
}
// [bundle] end   <util.scad>

function cap_taper_od_at(z_local, top_od, bot_od, insert_len) =
    top_od + (bot_od - top_od) * (z_local / insert_len);

// solid outer form: disk + straight insert + entry chamfer, less the seal grooves
module cap_plug_outer(disk_od, roof_t, insert_len, insert_od,
                      chamfer_h, chamfer_delta,
                      band_enable, band_count, band_z1, band_z2,
                      band_w, band_depth) {
    top_od = insert_od;
    bot_od = insert_od;
    straight_h = insert_len - chamfer_h;

    module base_body() {
        union() {
            cylinder(h = roof_t, d = disk_od);
            translate([0, 0, roof_t])
                cylinder(h = straight_h, d1 = top_od,
                         d2 = cap_taper_od_at(straight_h, top_od, bot_od, insert_len));
            if (chamfer_h > 0)
                translate([0, 0, roof_t + straight_h])
                    cylinder(h = chamfer_h,
                             d1 = cap_taper_od_at(straight_h, top_od, bot_od, insert_len),
                             d2 = max(0.1, bot_od - chamfer_delta));
        }
    }

    module one_groove(center_z) {
        z0 = clamp(center_z - band_w / 2, 0, insert_len);
        z1 = clamp(center_z + band_w / 2, 0, insert_len);
        if (z1 > z0)
            difference() {
                translate([0, 0, roof_t + z0])
                    cylinder(h = z1 - z0,
                             d1 = cap_taper_od_at(z0, top_od, bot_od, insert_len) + p_eps(),
                             d2 = cap_taper_od_at(z1, top_od, bot_od, insert_len) + p_eps());
                translate([0, 0, roof_t + z0 - p_eps() / 2])
                    cylinder(h = z1 - z0 + p_eps(),
                             d1 = max(0.1, cap_taper_od_at(z0, top_od, bot_od, insert_len) - 2 * band_depth),
                             d2 = max(0.1, cap_taper_od_at(z1, top_od, bot_od, insert_len) - 2 * band_depth));
            }
    }

    difference() {
        base_body();
        if (band_enable) {
            if (band_count >= 1) one_groove(band_z1);
            if (band_count >= 2) one_groove(band_z2);
        }
    }
}

module cap_cavity_cut(roof_t, insert_len, insert_od, insert_wall_t,
                      chamfer_h, chamfer_delta) {
    inner_top_od = max(1, insert_od - 2 * insert_wall_t);
    inner_bot_od = inner_top_od;
    inner_tip_od = max(0.5, inner_bot_od - max(0, chamfer_delta));
    straight_h = insert_len - chamfer_h;
    union() {
        translate([0, 0, roof_t - p_eps()])
            cylinder(h = straight_h + 2 * p_eps(), d1 = inner_top_od, d2 = inner_bot_od);
        if (chamfer_h > 0)
            translate([0, 0, roof_t + straight_h])
                cylinder(h = chamfer_h + p_eps(), d1 = inner_bot_od, d2 = inner_tip_od);
    }
}

module cap_button_holes_cut(roof_t, button_d, axis, radius) {
    module hole(x, y)
        translate([x, y, -p_eps()]) cylinder(h = roof_t + 2 * p_eps(), d = button_d);
    if (axis == "x") { hole(radius, 0); hole(-radius, 0); }
    else             { hole(0, radius); hole(0, -radius); }
}

// Two internal ribs ("side tabs") on the hollow insert cavity's inner
// wall, one on each side along the button axis. Each tab has two stacked
// segments. Only the OUTER face (the one that would otherwise poke past
// the cap's own round wall) is curved to match that wall; the INNER face
// and the two tangential SIDE faces stay flat/straight, parallel-sided,
// exactly as in the original flat-cube tab:
//   - RIB (Z = roof_t .. roof_t + lip_h): rooted at the cavity floor (the
//     "inside bottom" where the hollow meets the solid roof/boss), thin --
//     spans from (cavity wall radius - tab_depth) out to the cavity wall
//     radius, i.e. filling in the sides of the circular interior locally.
//     Built as a flat tab_width x tab_depth block, then INTERSECTED with a
//     cylinder at the cavity-wall radius -- this only clips the block's
//     far outer corners back onto the wall's arc; the flat inner face and
//     flat parallel sides are untouched (the intersection doesn't reach
//     them).
//   - LIP EXTENSION (Z = roof_t + lip_h .. + tab_overhang): above the top
//     lip (chamfer tip) there is no cap material at all, so this segment
//     is widened to run the FULL insert wall thickness -- same flat
//     parallel sides as the rib -- then intersected with a cylinder at the
//     insert's own outer wall radius, so only ITS outer corners get clipped
//     onto that (larger) arc.
// Above tab_taper_start_offset mm BELOW the lip, the INNER face stops being
// flat: from that Z up to the free tip it leans inward (radially), gaining
// tab_taper_gain (total, radially) by the tip, as ONE continuous linear
// slope -- the widening step at the lip only changes which cylinder the
// OUTER face is clipped to (r_outer inside the cavity, r_wall above it), it
// does not break the taper. Below the taper-start Z the inner face is still
// the plain flat rib. Each tapered stretch is a hull() of two thin end
// slices, so it stays a single flat sloped face -- a shallow, gradual,
// self-supporting overhang, not a step -- while the outer face and the two
// tangential side faces stay flat/vertical exactly as before.
// The two bottom edges of the rib (where its flat SIDE faces meet the
// cavity floor) are rounded with a tab_fillet_r quarter-round, cut with a
// corner-sliver subtraction (only the floor-facing edges; the lip
// extension doesn't touch the floor, so it stays unrounded).
// The finished pair is placed along the button axis (axis "x"/"y") and then
// rotated an extra tab_rotate_deg about Z -- positive = counter-clockwise,
// negative = clockwise, viewed from above (+Z looking down at the boss/
// insert side) -- to swing both tabs off that axis together.
// Not a cut: this ADDS material into the cavity (and, above the lip, past
// the cap's normal outer profile).
//
// WIRE HOLE (`wire_hole`, off by default here): a round channel drilled
// down each tab for routing button wires. It runs from the exposed free
// tip (open air above the cap, where a wire is fed in) down to a point
// `wire_hole_exit_from_lip` mm below the lip, comfortably inside the cap
// body -- not straight, but angled so its lower end sits at least one hole
// diameter inboard of the tab's own inner face at that height, breaking
// through into the real hollow cavity rather than dead-ending in solid
// rib/lip material. Modelled as a hull of two spheres (a capsule) between
// the entry and exit points -- simplest way to get a smooth round tunnel
// between two off-axis points. Only ever removes tab material (the
// breakout point is already inside the cavity's own empty radius, so nothing
// else needs cutting).
module cap_side_tabs(wall_d, outer_wall_d, roof_t, lip_h, tab_width, tab_depth, tab_overhang, axis, tab_fillet_r = 0, tab_taper_gain = 0, tab_taper_start_offset = 0, tab_rotate_deg = 0, wire_hole = false, wire_hole_d = 5, wire_hole_exit_from_lip = 15, fn = 48) {
    r_outer = wall_d / 2;        // cavity wall radius -- rib's outer clip radius
    r_wall  = outer_wall_d / 2;  // insert's outer wall radius -- lip-extension's outer clip radius
    r_inner = r_outer - tab_depth; // rib's flat inner face at/below the taper start

    lip_z    = roof_t + lip_h;                                   // top of the rooted rib
    tip_z    = lip_z + tab_overhang;                              // free tip
    taper0_z = max(roof_t, lip_z - tab_taper_start_offset);       // where the inward lean begins
    taper_span = tip_z - taper0_z;                                // > 0 whenever tab_overhang > 0

    // linear inner-face radius at height z, valid for z in [taper0_z, tip_z]
    function r_at(z) = r_inner - tab_taper_gain * (z - taper0_z) / taper_span;
    r_lip = r_at(lip_z);          // inner-face radius exactly at the lip (the r1 hand-off point)
    r_tip = r_inner - tab_taper_gain;

    // wire-hole entry (top, at the tip) / exit (breaking into the cavity)
    wire_exit_z    = lip_z - wire_hole_exit_from_lip;
    wire_entry_r   = (r_tip + r_wall) / 2;                  // centred in the tip's radial thickness
    wire_inner_r_at_exit = (wire_exit_z >= taper0_z) ? r_at(wire_exit_z) : r_inner;
    wire_exit_r    = max(0, wire_inner_r_at_exit - wire_hole_d);  // a full diameter past the inner face

    // flat, parallel-sided block: X in [-tab_width/2, tab_width/2],
    // radial coordinate (named Y here) in [r0,r1], axial in [z0,z1].
    // Built along the local +Y axis; one_tab() places it at +/-Y (or, for
    // axis="x", the whole pair is rotated 90 deg afterwards).
    module raw_block(sign, r0, r1, z0, z1) {
        translate([-tab_width / 2, sign > 0 ? r0 : -r1, z0])
            cube([tab_width, r1 - r0, z1 - z0]);
    }

    // Same footprint as raw_block, but the inner face (r0) moves linearly
    // from r0_bot at z0 to r0_top at z1 while the outer face (r1) stays
    // put -- a single flat sloped inner face, built as a hull of two thin
    // end slices so it stays a plain linear taper (no bulge).
    module raw_block_tapered(sign, r0_bot, r0_top, r1, z0, z1) {
        hull() {
            translate([-tab_width / 2, sign > 0 ? r0_bot : -r1, z0])
                cube([tab_width, max(p_eps(), r1 - r0_bot), p_eps()]);
            translate([-tab_width / 2, sign > 0 ? r0_top : -r1, z1 - p_eps()])
                cube([tab_width, max(p_eps(), r1 - r0_top), p_eps()]);
        }
    }

    // clips a solid to a circle of radius r_clip (only trims material that
    // sticks out past that radius -- flat faces already inside it are
    // untouched, so this only rounds the far/outer corners of raw_block).
    module curved_clip(r_clip, z0, z1) {
        translate([0, 0, z0])
            cylinder(r = r_clip, h = z1 - z0);
    }

    // corner-sliver cutter: rounds the edge where local X=0 meets local
    // Z=0 (material assumed at X>0, Z>0) over length `len` along Y, to a
    // quarter-round of radius r.
    module side_sliver(len, r, fn = 48) {
        difference() {
            cube([r, len, r]);
            translate([r, -0.5, r])
                rotate([-90, 0, 0])
                    cylinder(r = r, h = len + 1, $fn = fn);
        }
    }

    // capsule-shaped wire channel: a hull of two spheres between the tip
    // entry point and the cavity-breakout exit point, both at local X=0,
    // Y = sign * radius (matching the raw_block sign convention above).
    module wire_channel(sign) {
        hull() {
            translate([0, sign * wire_entry_r, tip_z])
                sphere(d = wire_hole_d, $fn = fn);
            translate([0, sign * wire_exit_r, wire_exit_z])
                sphere(d = wire_hole_d, $fn = fn);
        }
    }

    module one_tab(sign) {
        rib_y0 = sign > 0 ? r_inner : -r_outer; // start of the rib's radial span
        difference() {
            union() {
                // A: plain flat rib, floor up to the taper start (skipped
                // when the taper starts at/below the floor).
                if (taper0_z - roof_t > p_eps())
                    intersection() {
                        raw_block(sign, r_inner, r_outer, roof_t, taper0_z + p_eps());
                        curved_clip(r_outer, roof_t - p_eps(), taper0_z + 2 * p_eps());
                    }
                // B: taper begins, still inside the cavity (outer face still
                // clipped to the cavity wall, r_outer) -- skipped when the
                // taper starts exactly at the lip (tab_taper_start_offset = 0).
                if (lip_z - taper0_z > p_eps())
                    intersection() {
                        raw_block_tapered(sign, r_inner, r_lip, r_outer, taper0_z, lip_z + p_eps());
                        curved_clip(r_outer, taper0_z - p_eps(), lip_z + 2 * p_eps());
                    }
                // C: lip extension proper -- outer face widens to the
                // insert's own outer wall (r_wall); taper continues from
                // r_lip (whatever it reached at the lip) to r_tip.
                intersection() {
                    raw_block_tapered(sign, r_lip, r_tip, r_wall, lip_z, tip_z);
                    curved_clip(r_wall, lip_z - p_eps(), tip_z + p_eps());
                }
            }
            if (tab_fillet_r > 0) {
                // left side (X = -tab_width/2): material at X > -tab_width/2
                translate([-tab_width / 2, rib_y0, roof_t])
                    side_sliver(r_outer - r_inner, tab_fillet_r);
                // right side (X = +tab_width/2): material at X < +tab_width/2 -> mirror
                translate([tab_width / 2, rib_y0, roof_t])
                    mirror([1, 0, 0])
                        side_sliver(r_outer - r_inner, tab_fillet_r);
            }
            if (wire_hole)
                wire_channel(sign);
        }
    }

    base_rot = (axis == "x") ? 90 : 0;
    rotate([0, 0, base_rot + tab_rotate_deg]) { one_tab(1); one_tab(-1); }
}

module control_cap(disk_od       = p_cap_disk_d(),
                   roof_t        = p_cap_roof_t(),
                   boss_d        = p_cap_boss_d(),
                   boss_depth    = p_cap_boss_depth(),
                   insert_len    = p_cap_insert_len(),
                   insert_od     = p_insert_shaft_d(),
                   insert_wall_t = p_cap_insert_wall_t(),
                   chamfer_h     = p_cap_entry_chamfer_h(),
                   chamfer_delta = p_cap_entry_chamfer_delta(),
                   axle_bore_d   = p_cap_axle_bore_d(),
                   button_d      = p_button_upper_d(),
                   button_axis   = p_button_axis(),
                   button_radius = p_button_radius(),
                   band_enable   = true,
                   band_count    = undef,
                   band_z1       = p_seal_groove1_from_shoulder(),
                   band_z2       = p_seal_groove2_from_shoulder(),
                   band_w        = p_seal_groove_axial_h(),
                   band_depth    = p_seal_groove_radial_depth(),
                   oring_gland   = true,   // rotary seal on the axle round section
                   oring_gland_od = p_cap_oring_gland_od(),
                   oring_gland_w  = p_cap_oring_gland_w(),
                   oring_gland_z  = p_cap_oring_gland_from_face(),
                   side_tabs      = false,  // two internal cavity ribs + lip extension
                   tab_width_p    = 22,
                   tab_depth_p    = 2,
                   tab_overhang_p = 14,    // how far the lip extension runs past the top lip
                   tab_fillet_p   = 0,     // rounds the rib's two bottom (floor) edges
                   tab_taper_gain_p = 0,   // total inward (radial) lean of the inner face by
                                           // the free tip, vs. the plain rib thickness
                   tab_taper_start_p = 0,  // taper begins this far BELOW the lip (0 = at the lip)
                   tab_rotate_p     = 0,   // extra rotation of the tab pair about Z, off the
                                           // button axis (+ = CCW, - = CW, viewed from above)
                   tab_wire_hole    = false, // drill a wire-routing channel down each tab
                   tab_wire_hole_d  = 5,
                   tab_wire_hole_exit_from_lip = 15, // how far below the lip the channel breaks
                                                      // through into the hollow cavity
                   fn            = undef) {
    bc = band_count == undef ? p_seal_groove_count() : band_count;
    nn = fn == undef ? p_fn_plastic() : fn;
    inner_top_od = max(1, insert_od - 2 * insert_wall_t);

    // ---- fit / sanity asserts (kept from the standalone) ----
    assert(disk_od > insert_od && insert_od > 2 * insert_wall_t);
    assert(roof_t > 0 && insert_len > chamfer_h && chamfer_h >= 0);
    assert(insert_wall_t > band_depth && band_depth >= 0);
    assert(band_w > 0 && bc >= 0 && bc <= 2);
    if (band_enable)
        for (z = bc == 2 ? [band_z1, band_z2] : bc == 1 ? [band_z1] : [])
            assert(z - band_w / 2 > 0 && z + band_w / 2 < insert_len - chamfer_h,
                   "control_cap: seal groove must stay inside the straight insert body.");
    if (band_enable && bc == 2)
        assert(abs(band_z2 - band_z1) > band_w, "control_cap: seal grooves overlap.");
    assert(axle_bore_d > 0 && button_radius - button_d / 2 > axle_bore_d / 2);
    assert(button_radius + button_d / 2 < disk_od / 2);
    assert(button_axis == "x" || button_axis == "y");
    assert(boss_depth > 0 && boss_depth < insert_len);
    assert(boss_d > axle_bore_d && boss_d < inner_top_od);
    assert(boss_d / 2 < button_radius - button_d / 2,
           "control_cap: centre boss must clear the button openings.");
    if (oring_gland) {
        assert(oring_gland_od > axle_bore_d && oring_gland_od < boss_d - 1,
               "control_cap: O-ring gland OD must sit between the bore and the boss wall.");
        assert(oring_gland_z - oring_gland_w / 2 > 0.5
               && oring_gland_z + oring_gland_w / 2 < roof_t + boss_depth - 0.5,
               "control_cap: O-ring gland + lands do not fit the axle bore column (deepen the boss or move the gland).");
    }
    if (side_tabs) {
        assert(tab_depth_p > 0 && tab_depth_p < (inner_top_od - boss_d) / 2,
               "control_cap: side tab depth must stay clear of the centre boss.");
        assert(tab_width_p > 0 && tab_width_p < inner_top_od,
               "control_cap: side tab width does not fit the cavity wall.");
        assert(tab_overhang_p > 0,
               "control_cap: side tab overhang must be positive.");
        assert(tab_fillet_p >= 0,
               "control_cap: side tab fillet radius cannot be negative.");
        assert(tab_taper_gain_p >= 0
               && tab_taper_gain_p < inner_top_od / 2 - tab_depth_p - boss_d / 2,
               "control_cap: side tab taper gain must stay clear of the centre boss.");
        assert(tab_taper_start_p >= 0,
               "control_cap: side tab taper start offset cannot be negative.");
        // The rib runs the full insert_len (floor to top lip); the lip
        // extension then continues tab_overhang_p further, widened to the
        // full insert wall thickness (see cap_side_tabs). Both are
        // deliberately outside the plain cylindrical cavity envelope. The
        // inner face tapers inward by tab_taper_gain_p (total, by the free
        // tip) starting tab_taper_start_p mm below the lip (0 = at the lip).
        if (tab_wire_hole) {
            assert(tab_wire_hole_d > 0, "control_cap: wire hole diameter must be positive.");
            assert(tab_wire_hole_exit_from_lip > 0
                   && roof_t + insert_len - tab_wire_hole_exit_from_lip > roof_t,
                   "control_cap: wire hole exit point must land inside the cap body, above the floor.");
        }
    }

    $fn = nn;
    difference() {
        union() {
            difference() {
                cap_plug_outer(disk_od, roof_t, insert_len, insert_od,
                               chamfer_h, chamfer_delta,
                               band_enable, bc, band_z1, band_z2, band_w, band_depth);
                cap_cavity_cut(roof_t, insert_len, insert_od, insert_wall_t,
                               chamfer_h, chamfer_delta);
            }
            // boss, overlapped into the roof so it is one solid body
            translate([0, 0, roof_t - 2 * p_eps()])
                cylinder(d = boss_d, h = boss_depth + 2 * p_eps());
            // internal cavity side tabs, rooted at the cavity floor,
            // widening into a full-thickness lip extension past the top lip
            if (side_tabs)
                cap_side_tabs(inner_top_od, insert_od, roof_t, insert_len,
                              tab_width_p, tab_depth_p, tab_overhang_p, button_axis,
                              tab_fillet_p, tab_taper_gain_p, tab_taper_start_p, tab_rotate_p,
                              tab_wire_hole, tab_wire_hole_d, tab_wire_hole_exit_from_lip, nn);
        }
        // central bore through roof + boss
        translate([0, 0, -p_eps()])
            cylinder(h = roof_t + boss_depth + 2 * p_eps(), d = axle_bore_d);
        // O-ring gland: an annular groove in the bore wall, centred oring_gland_z
        // below the cap outer face, that seats the axle rotary-seal O-ring.
        if (oring_gland)
            translate([0, 0, oring_gland_z - oring_gland_w / 2])
                rotate_extrude($fn = nn)
                    translate([axle_bore_d / 2 - p_eps(), 0])
                        square([oring_gland_od / 2 - axle_bore_d / 2 + p_eps(),
                                oring_gland_w]);
        cap_button_holes_cut(roof_t, button_d, button_axis, button_radius);
    }

    echo("CAP: disk / insert dia / total height = ",
         disk_od, insert_od, roof_t + insert_len);
    echo("CAP: roof / boss depth / axle bearing length = ",
         roof_t, boss_depth, roof_t + boss_depth);
    if (oring_gland)
        echo("CAP: axle O-ring gland -- bore ", axle_bore_d, " -> groove OD ",
             oring_gland_od, " x ", oring_gland_w, " wide, centred ", oring_gland_z,
             " mm below the outer face. Seals a ", p_axle_oring_cs(),
             " mm-CS O-ring (ID ", p_axle_oring_id(), ") on the axle round section.");
    if (side_tabs)
        echo("CAP: side tabs -- width ", tab_width_p, " x rib depth ", tab_depth_p,
             ", rib height ", insert_len, " (floor to lip) + ", tab_overhang_p,
             " mm full-thickness lip extension, inner face tapers +", tab_taper_gain_p,
             " mm radially starting ", tab_taper_start_p, " mm below the lip, ",
             tab_fillet_p, " mm bottom-edge fillet, on the ", button_axis,
             " axis rotated ", tab_rotate_p, " deg.");
    if (side_tabs && tab_wire_hole)
        echo("CAP: tab wire hole -- ", tab_wire_hole_d,
             " mm dia, from the tip down to ", tab_wire_hole_exit_from_lip,
             " mm below the lip, where it breaks into the cavity.");
}
// [bundle] end   <../../lib/control_cap.scad>

color([0.74, 0.77, 0.79])
control_cap(roof_t        = top_disk_thickness,
            boss_d        = centre_boss_diameter,
            boss_depth    = centre_boss_depth,
            insert_len    = insert_total_h,
            insert_wall_t = cup_wall_thickness,
            chamfer_h     = entry_chamfer_h,
            chamfer_delta = entry_chamfer_delta,
            axle_bore_d   = shaft_hole_d,
            button_d      = button_upper_d,
            button_axis   = button_axis,
            button_radius = hole_spacing_cc,
            band_enable   = band_channels_enable,
            band_count    = band_count,
            band_z1       = band1_center_z_local,
            band_z2       = band2_center_z_local,
            band_w        = band_channel_w,
            band_depth    = band_channel_depth,
            oring_gland    = oring_gland_enable,
            oring_gland_od = oring_gland_od,
            oring_gland_w  = oring_gland_width,
            oring_gland_z  = oring_gland_from_face,
            side_tabs      = side_tabs_enable,
            tab_width_p    = tab_width,
            tab_depth_p    = tab_depth,
            tab_overhang_p = tab_top_overhang,
            tab_fillet_p   = tab_corner_fillet,
            tab_taper_gain_p = tab_tip_taper_gain,
            tab_taper_start_p = tab_taper_start,
            tab_rotate_p     = tab_rotate,
            tab_wire_hole    = tab_wire_hole_enable,
            tab_wire_hole_d  = tab_wire_hole_diameter,
            tab_wire_hole_exit_from_lip = tab_wire_hole_exit_from_lip,
            fn            = fn);
